/* FLAIR MASTER CONFIG | auto-generated at 2016-12-21T02:13:37-0800 (ISO-8601) */ 
flair.load__by_id = function() {
	for (var key in flair.names) {
		if (flair.names.hasOwnProperty(key)) {
			var data = key.split(' ');
			
			var orig_id = data[2];
			
			if (orig_id.substring(0, 'a'.length) === 'a') {
				orig_id = orig_id.substring(1);
			}
			if (orig_id.substring(orig_id.length - 'm'.length) === 'm') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'o'.length) === 'o') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'x'.length) === 'x') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'y'.length) === 'y') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 1).match(/[a-z]/i) &&
				orig_id.substring(0, orig_id.length - 1).match(/^\d+$/)) {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			
			flair.by_id[data[2]] = {
				key: key,
				spritepos: data[0],
				sheet: data[1],
				flair_id: data[2],
				orig_id: orig_id,
				flair_name: flair.names[key],
				flair_class: ' flair-'+data[0] + ' flair-'+data[1] + ' flair-'+data[2]
			}
		}
	}
}
flair.by_id = {}
flair.names = {
/* [STANDARD] */
	
	/* Prime Warframes (0-21) */
	"0 primewarframesflair ash-prime": "Ash Prime",
	"15 primewarframesflair banshee-prime": "Banshee Prime",
	"1 primewarframesflair ember-prime": "Ember Prime",
	"2 primewarframesflair excalibur-prime": "Excalibur Prime (PC Founders exclusive)",
	"3 primewarframesflair frost-prime": "Frost Prime",
	"20 primewarframesflair hydroid-prime": "Hydroid Prime",
	"4 primewarframesflair loki-prime": "Loki Prime",
	"5 primewarframesflair mag-prime": "Mag Prime",
	"6 primewarframesflair nekros-prime": "Nekros Prime",
	"7 primewarframesflair nova-prime": "Nova Prime",
	"8 primewarframesflair nyx-prime": "Nyx Prime",
	"17 primewarframesflair oberon-prime": "Oberon Prime",
	"18 primewarframesflair oberon-prime-alt": "Oberon Prime (alternate picture)",
	"9 primewarframesflair rhino-prime": "Rhino Prime",
	"10 primewarframesflair saryn-prime": "Saryn Prime",
	"11 primewarframesflair trinity-prime": "Trinity Prime",
	"12 primewarframesflair vauban-prime": "Vauban Prime",
	"13 primewarframesflair volt-prime": "Volt Prime",
	"14 primewarframesflair valkyr-prime": "Valkyr Prime",
	
	
	/* Regular Warframes (0-68) */
	"0 regularwarframesflair ash": "Ash",
	"1 regularwarframesflair atlas": "Atlas",
	"2 regularwarframesflair banshee": "Banshee",
	"3 regularwarframesflair chroma": "Chroma",
	"4 regularwarframesflair ember": "Ember",
	"5 regularwarframesflair equinox": "Equinox",
	"6 regularwarframesflair excalibur": "Excalibur",
	"7 regularwarframesflair frost": "Frost",
	"67 regularwarframesflair gara": "Gara",
	"65 regularwarframesflair harrow": "Harrow",
	"8 regularwarframesflair hydroid": "Hydroid",
	"9 regularwarframesflair inaros": "Inaros",
	"10 regularwarframesflair ivara": "Ivara",
	"11 regularwarframesflair limbo": "Limbo",
	"12 regularwarframesflair loki": "Loki",
	"13 regularwarframesflair mag": "Mag",
	"14 regularwarframesflair mesa": "Mesa",
	"15 regularwarframesflair mirage": "Mirage",
	"16 regularwarframesflair nekros": "Nekros",
	"17 regularwarframesflair nezha": "Nezha",
	"18 regularwarframesflair nidus": "Nidus",
	"19 regularwarframesflair nova": "Nova",
	"20 regularwarframesflair nyx": "Nyx",
	"21 regularwarframesflair oberon": "Oberon",
	"31 regularwarframesflair octavia": "Octavia",
	"22 regularwarframesflair rhino": "Rhino",
	"23 regularwarframesflair saryn": "Saryn",
	"24 regularwarframesflair titania": "Titania",
	"25 regularwarframesflair trinity": "Trinity",
	"26 regularwarframesflair valkyr": "Valkyr",
	"27 regularwarframesflair vauban": "Vauban",
	"28 regularwarframesflair volt": "Volt",
	"29 regularwarframesflair wukong": "Wukong",
	"30 regularwarframesflair zephyr": "Zephyr",
	"32 regularwarframesflair ash-alt": "Ash (alternate picture)",
	"33 regularwarframesflair banshee-alt": "Banshee (alternate picture)",
	"34 regularwarframesflair ember-alt": "Ember (alternate picture)",
	"35 regularwarframesflair excalibur-alt": "Excalibur (alternate picture)",
	"36 regularwarframesflair frost-alt": "Frost (alternate picture)",
	"68 regularwarframesflair gara-bundle": "Gara (collection)",
	"37 regularwarframesflair loki-alt": "Loki (alternate picture)",
	"38 regularwarframesflair mag-alt": "Mag (alternate picture)",
	"39 regularwarframesflair mesa-alt": "Mesa (alternate picture)",
	"40 regularwarframesflair nyx-alt": "Nyx (alternate picture)",
	"41 regularwarframesflair rhino-alt": "Rhino (alternate picture)",
	"42 regularwarframesflair saryn-alt": "Saryn (alternate picture)",
	"43 regularwarframesflair trinity-alt": "Trinity (alternate picture)",
	"44 regularwarframesflair volt-alt": "Volt (alternate picture)",
	"45 regularwarframesflair atlas-bundle": "Atlas (Brawler Bundle)",
	"46 regularwarframesflair chroma-bundle": "Chroma (Dragon Bundle)",
	"47 regularwarframesflair equinox-bundle": "Equinox (Mega Pack)",
	"48 regularwarframesflair excalibur-bundle-1": "Excalibur (Continuity Collection)",
	"49 regularwarframesflair excalibur-bundle-2": "Excalibur (Destreza Finesse Pack)",
	"50 regularwarframesflair excalibur-bundle-3": "Excalibur (Gazal Complete Collection)",
	"64 regularwarframesflair excalibur-bundle-4": "Excalibur (Towsun skin Collection)",
	"51 regularwarframesflair hydroid-bundle": "Hydroid (Update 13 Mega Pack)",
	"52 regularwarframesflair inaros-bundle": "Inaros (Sands of Inaros Bundle)",
	"53 regularwarframesflair ivara-bundle": "Ivara (Huntress Bundle)",
	"66 regularwarframesflair harrow-bundle": "Harrow (collection)",
	"54 regularwarframesflair limbo-bundle": "Limbo (bundle)",
	"55 regularwarframesflair mesa-bundle": "Mesa (Gunslinger Bundle)",
	"56 regularwarframesflair mirage-bundle": "Mirage (bundle)",
	"57 regularwarframesflair nekros-bundle": "Nekros (Update 10 Mega Bundle)",
	"58 regularwarframesflair nidus-bundle": "Nidus (collection)",
	"59 regularwarframesflair oberon-bundle": "Oberon (Paladin Bundle)",
	"60 regularwarframesflair octavia-bundle": "Octavia (collection)",
	"61 regularwarframesflair titania-bundle": "Titania (The Silver Grove Bundle)",
	"62 regularwarframesflair valkyr-bundle": "Valkyr (Berserker Bundle)",
	"63 regularwarframesflair zephyr-bundle": "Zephyr (Update 12 Mega Bundle)",

		
	/* Deluxe Warframe Skins (0-26)*/
	"0 deluxewarframeskinsflair ash-koga-skin": "Ash Koga skin",
	"12 deluxewarframeskinsflair ash-koga-deluxe-skin-bundle": "Ash Koga deluxe skin (bundle)",
	"1 deluxewarframeskinsflair banshee-soprana-skin": "Banshee Soprana skin",
	"13 deluxewarframeskinsflair banshee-soprana-deluxe-skin-bundle": "Banshee Soprana deluxe skin (collection)",
	"23 deluxewarframeskinsflair chroma-dynasty-skin-alt": "Chroma Dynasty deluxe skin (alternate picture)",
	"24 deluxewarframeskinsflair chroma-dynasty-deluxe-skin-bundle-alt": "Chroma Dynasty deluxe skin (collection, alternate picture)",
	"21 deluxewarframeskinsflair ember-vermillion-deluxe-skin": "Ember Vermillion deluxe skin",
	"22 deluxewarframeskinsflair ember-vermillion-deluxe-skin-bundle": "Ember Vermillion deluxe skin (collection)",
	"2 deluxewarframeskinsflair excalibur-proto-skin": "Excalibur Proto skin",
	"11 deluxewarframeskinsflair frost-harka-skin": "Frost Harka skin",
	"14 deluxewarframeskinsflair frost-harka-deluxe-skin-bundle": "Frost Harka deluxe skin (bundle)",
	"15 deluxewarframeskinsflair frost-harka-deluxe-skin-bundle-alt": "Frost Harka deluxe skin (bundle alternate picture)",
	"3 deluxewarframeskinsflair loki-knave-skin": "Loki Knave skin",
	"25 deluxewarframeskinsflair nekros-irkalla-deluxe-skin": "Nekros Irkalla deluxe skin",
	"26 deluxewarframeskinsflair nekros-irkalla-deluxe-skin-bundle": "Nekros Irkalla deluxe skin (collection)",
	"4 deluxewarframeskinsflair nova-asuri-skin": "Nova Asuri skin",
	"16 deluxewarframeskinsflair nova-asuri-deluxe-skin-bundle": "Nova Asuri deluxe skin (collection)",
	"5 deluxewarframeskinsflair nyx-nemesis-skin": "Nyx Nemesis skin",
	"6 deluxewarframeskinsflair oberon-feyarch-skin": "Oberon Feyarch skin",
	"17 deluxewarframeskinsflair oberon-feyarch-deluxe-skin-bundle": "Oberon Feyarch deluxe skin (collection)",
	"7 deluxewarframeskinsflair rhino-palatine-skin": "Rhino Palatine skin",
	"18 deluxewarframeskinsflair rhino-palatine-deluxe-skin-bundle": "Rhino Palatine deluxe skin (pack)",
	"8 deluxewarframeskinsflair saryn-orphid-skin": "Saryn Orphid skin",
	"19 deluxewarframeskinsflair saryn-orphid-deluxe-skin-bundle": "Saryn Orphid deluxe skin (collection)",
	"9 deluxewarframeskinsflair trinity-strega-skin": "Trinity Strega skin",
	"20 deluxewarframeskinsflair trinity-strega-deluxe-skin-bundle": "Trinity Strega deluxe skin (collection)",
	"10 deluxewarframeskinsflair valkyr-gersemi-skin": "Valkyr Gersemi skin",

		
	/* TennoGen Warframe Skins (0-61)*/
	"33 tennogenwarframeskinsflair ash-bai-hu-skin": "Ash Bai Hu skin (by Hitsu San)",
	"47 tennogenwarframeskinsflair ash-tsukuyomi-skin": "Ash Tsukuyomi Skin (by Yatus)",
	"56 tennogenwarframeskinsflair atlas-graxx-skin": "Atlas Graxx skin (by Faven)",
	"48 tennogenwarframeskinsflair atlas-monolith-skin": "Atlas Monolith Skin (by stenchfury)",
	"0 tennogenwarframeskinsflair chroma-drevni-skin": "Chroma Drevni skin (by Volkovyi)",
	"1 tennogenwarframeskinsflair chroma-vojnik-skin": "Chroma Vojnik Battle-Damaged skin (by Volkovyi)",
	"2 tennogenwarframeskinsflair ember-graxx-skin": "Ember Graxx skin (by Faven_PS)",
	"40 tennogenwarframeskinsflair ember-ignition-skin": "Ember Ignition skin (by Kaiceps)",
	"41 tennogenwarframeskinsflair ember-magesty-skin": "Ember Magesty skin (by Prosetisen and Cheshire)",
	"49 tennogenwarframeskinsflair equinox-insomnia-skin": "Equinox Insomnia Skin (by prosetisen)",
	"3 tennogenwarframeskinsflair excalibur-apex-skin": "Excalibur Apex skin (by antoineflemming)",
	"4 tennogenwarframeskinsflair excalibur-caduto-skin": "Excalibur Caduto skin (by Hitsu San)",
	"5 tennogenwarframeskinsflair excalibur-graxx-skin": "Excalibur Graxx skin (by Faven_PS)",
	"6 tennogenwarframeskinsflair excalibur-sentient slayer-skin": "Excalibur Sentient Slayer skin (by CommanderApocalypse)",
	"7 tennogenwarframeskinsflair excalibur-vespula gold-skin": "Excalibur Vespula Gold skin (by polygonmonster)",
	"8 tennogenwarframeskinsflair frost-emperor-skin": "Frost Emperor skin (by Hitsu San)",
	"9 tennogenwarframeskinsflair frost-grost-skin": "Frost Grost skin (by Faven_PS)",
	"10 tennogenwarframeskinsflair frost-hailstorm-skin": "Frost Hailstorm skin (by Arsenal)",
	"11 tennogenwarframeskinsflair frost-vojnik-skin": "Frost Vojnik Battle-Damaged skin (by Volkovyi)",
	"50 tennogenwarframeskinsflair hydroid-graxx-skin": "Hydroid Graxx Skin (by Faven_PS)",
	"42 tennogenwarframeskinsflair ivara-arcuata-skin": "Ivara Arcuata skin (by Stenchfury)",
	"43 tennogenwarframeskinsflair ivara-youkai-skin": "Ivara Youkai skin (by HitsuSan)",
	"44 tennogenwarframeskinsflair limbo-vasiona-skin": "Limbo Vasiona skin (by Volkovyi)",
	"57 tennogenwarframeskinsflair limbo-vistyxio-skin": "Limbo Vistyxio skin (by led2012 and Hydroxate)",
	"34 tennogenwarframeskinsflair loki-incubus-skin": "Loki Incubus skin (by Volkovyi)",
	"12 tennogenwarframeskinsflair mag-alata-skin": "Mag Alata skin (by Hitsu San)",
	"51 tennogenwarframeskinsflair mag-graxx-skin": "Mag Graxx Skin (by Faven_PS)",
	"13 tennogenwarframeskinsflair mag-knaita-skin": "Mag Knaita skin (by prosetisen)",
	"14 tennogenwarframeskinsflair mag-orbit-skin": "Mag Orbit skin (by Del)",
	"58 tennogenwarframeskinsflair mesa-devil-ranger-skin": "Mesa Devil Ranger skin (by Mz-3)",
	"35 tennogenwarframeskinsflair mesa-graxx-skin": "Mesa Graxx skin (by Faven_PS)",
	"15 tennogenwarframeskinsflair mirage-graxx-skin": "Mirage Graxx skin (by Faven_PS)",
	"36 tennogenwarframeskinsflair mirage-morgaine-skin": "Mirage Morgaine skin (by artarrwen)",
	"16 tennogenwarframeskinsflair mirage-sigyn-skin": "Mirage Sigyn skin (by Novabjorn)",
	"52 tennogenwarframeskinsflair nezha-devine-skin": "Nezha Devine Skin (by polygonmonster)",
	"59 tennogenwarframeskinsflair nezha-yaksha-skin": "Nezha Yaksha skin (by Faven and SilverBones)",
	"17 tennogenwarframeskinsflair nova-cygni-skin": "Nova Cygni skin (by Arsenal)",
	"18 tennogenwarframeskinsflair nova-device-skin": "Nova Device skin (by posetisen)",
	"19 tennogenwarframeskinsflair nova-gnova-skin": "Nova Gnova skin (by Faven_PS)",
	"53 tennogenwarframeskinsflair nova-graxx": "Nova Graxx skin (by Faven_PS)",
	"20 tennogenwarframeskinsflair nova-lamia-skin": "Nova Lamia skin (by Mz-3)",
	"21 tennogenwarframeskinsflair nova-stinger-skin": "Nova Stinger skin (by Cheshire)",
	"22 tennogenwarframeskinsflair nova-visage-skin": "Nova Visage skin (by Hitsu San)",
	"23 tennogenwarframeskinsflair nyx-athena-skin": "Nyx Athena skin (by prosetisen)",
	"54 tennogenwarframeskinsflair nyx-carnifex-skin": "Nyx Carnifex Skin (by Vulbjorn the Walrus Rider.)",
	"24 tennogenwarframeskinsflair nyx-graxx-skin": "Nyx Graxx skin (by Faven_PS)",
	"37 tennogenwarframeskinsflair nyx-saikou-skin": "Nyx Saikou skin skin (by malayu)",
	"25 tennogenwarframeskinsflair rhino-graxx-skin": "Rhino Graxx skin (by Faven_PS)",
	"26 tennogenwarframeskinsflair rhino-vojnik-skin": "Rhino Vojnik Battle-Damaged skin (by Volkovyi)",
	"55 tennogenwarframeskinsflair saryn-amalgama-skin": "Saryn Amalgama Skin (by prosetisen)",
	"27 tennogenwarframeskinsflair saryn-graxx-skin": "Saryn Graxx skin (by Faven_PS)",
	"38 tennogenwarframeskinsflair saryn-integra-skin": "Saryn Integra skin (by Cheshire)",
	"60 tennogenwarframeskinsflair titania-unseelie-skin": "Titania Unseelie skin (by Rekkou)",
	"61 tennogenwarframeskinsflair valkyr-delusion-skin": "Valkyr Delusion skin (by prosetisen)",
	"28 tennogenwarframeskinsflair valkyr-graxx-skin": "Valkyr Graxx skin (by Faven_PS)",
	"39 tennogenwarframeskinsflair vauban-suppressor-skin": "Vauban Suppressor skin (by Cheshire and prosetisen)",
	"29 tennogenwarframeskinsflair volt-amp-skin": "Volt Amp skin (by Faven_PS)",
	"45 tennogenwarframeskinsflair volt-capacitor-skin": "Volt Capacitor skin (by Del)",
	"30 tennogenwarframeskinsflair volt-graxx-skin": "Volt Graxx skin (by Faven_PS)",
	"46 tennogenwarframeskinsflair volt-zener-skin": "Volt Zener skin (by Rekkou)",
	"31 tennogenwarframeskinsflair zephyr-hagoromo-skin": "Zephyr Hagoromo skin (by Hitsu San)",
	"32 tennogenwarframeskinsflair zephyr-skeiron-skin": "Zephyr Skeiron skin (by novadragon01)",


	/* Immortal Warframe Skins (0-26) */
	"0 immortalwarframeskinsflair ash-immortal-skin": "Ash Immortal skin",
	"17 immortalwarframeskinsflair ash-immortal-skin-alt": "Ash Immortal Skin (alternate picture)",
	"1 immortalwarframeskinsflair banshee-immortal-skin": "Banshee Immortal skin",
	"18 immortalwarframeskinsflair banshee-immortal-skin-alt": "Banshee Immortal Skin (alternate picture)",
	"2 immortalwarframeskinsflair ember-immortal-skin": "Ember Immortal skin",
	"3 immortalwarframeskinsflair excalibur-immortal-skin": "Excalibur Immortal skin",
	"19 immortalwarframeskinsflair excalibur-immortal-skin-alt": "Excalibur Immortal Skin (alternate picture)",
	"4 immortalwarframeskinsflair frost-immortal-skin": "Frost Immortal skin",
	"25 immortalwarframeskinsflair hydroid-immortal-skin": "Hydroid Immortal skin",
	"5 immortalwarframeskinsflair loki-immortal-skin": "Loki Immortal skin",
	"6 immortalwarframeskinsflair mag-immortal-skin": "Mag Immortal skin",
	"20 immortalwarframeskinsflair mag-immortal-skin-alt": "Mag Immortal Skin (alternate picture)",
	"7 immortalwarframeskinsflair nekros-immortal-skin": "Nekros Immortal skin",
	"8 immortalwarframeskinsflair nova-immortal-skin": "Nova Immortal skin",
	"9 immortalwarframeskinsflair nyx-immortal-skin": "Nyx Immortal skin",
	"21 immortalwarframeskinsflair nyx-immortal-skin-alt": "Nyx Immortal Skin (alternate picture)",
	"10 immortalwarframeskinsflair oberon-immortal-skin": "Oberon Immortal skin",
	"11 immortalwarframeskinsflair rhino-immortal-skin": "Rhino Immortal skin",
	"22 immortalwarframeskinsflair rhino-immortal-skin-alt": "Rhino Immortal Skin (alternate picture)",
	"12 immortalwarframeskinsflair saryn-immortal-skin": "Saryn Immortal skin",
	"23 immortalwarframeskinsflair saryn-immortal-skin-alt": "Saryn Immortal Skin (alternate picture)",
	"13 immortalwarframeskinsflair trinity-immortal-skin": "Trinity Immortal skin",
	"14 immortalwarframeskinsflair valkyr-immortal-skin": "Valkyr Immortal skin",
	"15 immortalwarframeskinsflair vauban-immortal-skin": "Vauban Immortal skin",
	"24 immortalwarframeskinsflair vauban-immortal-skin-alt": "Vauban Immortal Skin (alternate picture)",
	"16 immortalwarframeskinsflair volt-immortal-skin": "Volt Immortal skin",
	"26 immortalwarframeskinsflair zephyr-immortal-skin": "Zephyr Immortal skin",

		
	/* Other Warframe Skins (0-12) */
	"0 otherwarframeskinsflair excalibur-jade-skin": "Excalibur Jade skin (XB1 exclusive)",
	"1 otherwarframeskinsflair excalibur-obsidian-skin": "Excalibur Obsidian skin (PS4 exclusive)",
	"8 otherwarframeskinsflair excalibur-obsidian-skin-alt": "Excalibur Obsidian skin (PS4 exclusive, alternate picture)",
	"2 otherwarframeskinsflair excalibur-obsidian-azura-skin": "Excalibur Obsidian Azura skin (PS4 exclusive)",
	"3 otherwarframeskinsflair excalibur-prisma-skin": "Excalibur Prisma skin",
	"9 otherwarframeskinsflair excalibur-twitch-skin": "Excalibur Twitch skin",
	"10 otherwarframeskinsflair frost-festive-skin": "Frost Festive skin (winter exclusive)",
	"13 otherwarframeskinsflair ivara-obisidian-azura-skin": "Obsidian Azura Ivara skin (PS4 Renown Pack exclusive)",
	"11 otherwarframeskinsflair mirage-winter-skin": "Mirage Winter skin (winter exclusive)",
	"4 otherwarframeskinsflair rhino-rubedo-skin": "Rhino Rubedo skin (Steam exclusive)",
	"5 otherwarframeskinsflair titania-solstice-skin": "Titania Solstice skin (winter exclusive)",
	"12 otherwarframeskinsflair titania-solstice-skin-alt": "Titania Solstice skin (winter exclusive, alternate picture)",
	"6 otherwarframeskinsflair vauban-phased-skin": "Vauban Phased skin (Steam exclusive)",
	"7 otherwarframeskinsflair vauban-phased-skin-alt": "Vauban Phased skin (alternate picture)",

		
	/* Warframe Helmets */
	"16 primewarframesflair banshee-prime-helmet": "Banshee Prime helmet",
	"21 primewarframesflair hydroid-prime-helmet": "Hydroid Prime helmet",
	"19 primewarframesflair oberon-prime-helmet": "Oberon Prime helmet",
	"79 otherwarframehelmetsflair harrow-helmet": "Harrow helmet",
	"71 otherwarframehelmetsflair limbo-helmet": "Limbo helmet",
	"72 otherwarframehelmetsflair nyx-helmet": "Nyx helmet",
	"73 otherwarframehelmetsflair octavia-helmet": "Octavia helmet",
	"81 otherwarframehelmetsflair gara-helmet": "Gara helmet",

	
	/* Deluxe Warframe Helmets (50-56, 61, 71)*/
	"50 deluxewarframehelmetsflair ash-koga-helmet": "Ash Koga helmet",
	"51 deluxewarframehelmetsflair banshee-soprana-helmet": "Banshee Soprana helmet",
	"71 deluxewarframehelmetsflair chroma-dynasty-helmet": "Chroma Dynasty helmet",
	"53 deluxewarframehelmetsflair ember-vermillion-helmet": "Ember Vermillion helmet",
	"52 deluxewarframehelmetsflair excalibur-proto-helmet": "Excalibur Proto helmet",
	"61 deluxewarframehelmetsflair frost-harka-helmet": "Frost Harka helmet",
	"54 deluxewarframehelmetsflair nekros-irkalla-helmet": "Nekros Irkalla helmet",
	"55 deluxewarframehelmetsflair nyx-nemesis-helmet": "Nyx Nemesis helmet",
	"56 deluxewarframehelmetsflair oberon-feyarch-helmet": "Oberon Feyarch helmet",
	/*"57 deluxewarframehelmetsflair rhino-palatine-helmet": "Rhino Palatine helmet",*/
	/*"58 deluxewarframehelmetsflair saryn-orphid-helmet": "Saryn Orphid helmet",*/
	/*"59 deluxewarframehelmetsflair trinity-strega-helmet": "Trinity Strega helmet",*/
	/*"60 deluxewarframehelmetsflair valkyr-gersemi-helmet": "Valkyr Gersemi helmet",*/
	
	
	/* TennoGen Warframe Helmets (0-96)*/
	"67 tennogenwarframehelmetsflair ash-bai-hu-helmet": "Ash Bai Hu helmet (by Hitsu San)",
	"0 tennogenwarframehelmetsflair ash-carabid-helmet": "Ash Carabid helmet (by artarrwen)",
	"88 tennogenwarframehelmetsflair ash-tsukuyomi-helmet": "Ash Tsukuyomi Helmet (by Yatus)",
	"1 tennogenwarframehelmetsflair atlas-arhat-helmet": "Atlas Arhat helmet (by Rekkou)",
	"97 tennogenwarframehelmetsflair atlas-graxx-helmet": "Atlas Graxx helmet (by Faven)",
	"89 tennogenwarframehelmetsflair atlas-monolith-helmet": "Atlas Monolith Helmet (by stenchfury)",
	"2 tennogenwarframehelmetsflair atlas-telamon-helmet": "Atlas Telamon helmet (by artarrwen)",
	"98 tennogenwarframehelmetsflair banshee-dominia-helmet": "Banshee Dominia helmet (by led2012)",
	"3 tennogenwarframehelmetsflair banshee-echo-helmet": "Banshee Echo helmet (by Rekkou)",
	/*"4 tennogenwarframehelmetsflair chroma-drevni-helmet": "Chroma Drevni helmet (by Volkovyi)",*/
	"5 tennogenwarframehelmetsflair chroma-kaiju-helmet": "Chroma Kaiju helmet (by [k a z])",
	"6 tennogenwarframehelmetsflair chroma-tarrasque-helmet": "Chroma Tarrasque helmet (by artarrwen)",
	/*"7 tennogenwarframehelmetsflair chroma-vojnik-helmet": "Chroma Vojnik Battle-Damaged helmet (by Volkovyi)",*/
	"8 tennogenwarframehelmetsflair ember-graxx-helmet": "Ember Graxx helmet (by Faven_PS)",
	"77 tennogenwarframehelmetsflair ember-ignition-helmet": "Ember Ignition helmet (by Kaiceps)",
	"78 tennogenwarframehelmetsflair ember-magesty-helmet": "Ember Magesty helmet (by Prosetisen and Cheshire)",
	"90 tennogenwarframehelmetsflair equinox-insomnia-helmet": "Equinox Insomnia Helmet (by prosetisen)",
	"9 tennogenwarframehelmetsflair excalibur-apex-helmet": "Excalibur Apex helmet (by antoineflemming)",
	"10 tennogenwarframehelmetsflair excalibur-arturius-helmet": "Excalibur Arturius helmet (by [k a z])",
	"11 tennogenwarframehelmetsflair excalibur-caduto-helmet": "Excalibur Caduto helmet (by Hitsu San)",
	"12 tennogenwarframehelmetsflair excalibur-graxx-helmet": "Excalibur Graxx helmet (by Faven_PS)",
	"13 tennogenwarframehelmetsflair excalibur-graxx-alt-helmet": "Excalibur Graxx-v2 helmet (by Faven_PS)",
	"14 tennogenwarframehelmetsflair excalibur-isurus-helmet": "Excalibur Isurus helmet (by Coridium)",
	"15 tennogenwarframehelmetsflair excalibur-ogrant-helmet": "Excalibur Ogrant helmet (by lokimonkeye)",
	"16 tennogenwarframehelmetsflair excalibur-sentient-slayer-helmet": "Excalibur Sentient Slayer helmet (by CommanderApocalypse)",
	"17 tennogenwarframehelmetsflair excalibur-vespula-gold-helmet": "Excalibur Vespula Gold helmet (by polygonmonster)",
	"18 tennogenwarframehelmetsflair frost-emperor-helmet": "Frost Emperor helmet (by Hitsu San)",
	"19 tennogenwarframehelmetsflair frost-grost-helmet": "Frost Grost helmet (by Faven_PS)",
	"20 tennogenwarframehelmetsflair frost-hailstorm-helmet": "Frost Hailstorm helmet (by Arsenal)",
	"99 tennogenwarframehelmetsflair frost-himavat-helmet": "Frost Himavat helmet (by VoidPunch)",
	"21 tennogenwarframehelmetsflair frost-jotun-helmet": "Frost Jotun helmet (by malayu)",
	"22 tennogenwarframehelmetsflair frost-summit-helmet": "Frost Summit helmet (by artarrwen)",
	"23 tennogenwarframehelmetsflair frost-vojnik-helmet": "Frost Vojnik Battle-Damaged helmet (by Volkovyi)",
	"24 tennogenwarframehelmetsflair frost-zastruga-helmet": "Frost Zastruga helmet (by Rekkou)",
	"91 tennogenwarframehelmetsflair hydroid-graxx-helmet": "Hydroid Graxx Helmet (by Faven_PS)",
	"68 tennogenwarframehelmetsflair hydroid-rorqual-helmet": "Hydroid Rorqual helmet (by Rekkou)",
	"79 tennogenwarframehelmetsflair ivara-arcuata-helmet": "Ivara Arcuata helmet (by Stenchfury)",
	"80 tennogenwarframehelmetsflair ivara-youkai-helmet": "Ivara Youkai helmet (by HitsuSan)",
	"69 tennogenwarframehelmetsflair limbo-aureolus-helmet": "Limbo Aureolus helmet (by artarrwen)",
	"81 tennogenwarframehelmetsflair limbo-vasiona-helmet": "Limbo Vasiona helmet (by Volkovyi)",
	"100 tennogenwarframehelmetsflair limbo-venari-helmet": "Limbo Venari helmet (by Volkovyi and Sab531)",
	"101 tennogenwarframehelmetsflair limbo-vistyxio-helmet": "Limbo Vistyxio helmet (by led2012 and Hydroxate)",
	"25 tennogenwarframehelmetsflair loki-ersatz-helmet": "Loki Ersatz helmet (by Rekkou)",
	"70 tennogenwarframehelmetsflair loki-incubus-helmet": "Loki Incubus helmet (by Volkovyi)",
	"26 tennogenwarframehelmetsflair loki-rogue-helmet": "Loki Rogue helmet (by artarrwen)",
	"27 tennogenwarframehelmetsflair mag-alata-helmet": "Mag Alata helmet (by Hitsu San)",
	"28 tennogenwarframehelmetsflair mag-anthro-helmet": "Mag Anthro helmet (by Pior)",
	"92 tennogenwarframehelmetsflair mag-graxx-helmet": "Mag Graxx Helmet (by Faven_PS)",
	"29 tennogenwarframehelmetsflair mag-induction-helmet": "Mag Induction helmet (by Pior)",
	"30 tennogenwarframehelmetsflair mag-knaita-helmet": "Mag Knaita helmet (by prosetisen)",
	"31 tennogenwarframehelmetsflair mag-orbit-helmet": "Mag Orbit helmet (by Del)",
	"32 tennogenwarframehelmetsflair mag-toroidal-helmet": "Mag Toroidal helmet (by prosetisen)",
	"33 tennogenwarframehelmetsflair mesa-deadeye-helmet": "Mesa Deadeye helmet (by NotYou)",
	"102 tennogenwarframehelmetsflair mesa-devil-ranger-helmet": "Mesa Devil Ranger helmet (by Mz-3)",
	"34 tennogenwarframehelmetsflair mesa-falcon-helmet": "Mesa Falcon helmet (by prosetisen)",
	"71 tennogenwarframehelmetsflair mesa-graxx-helmet": "Mesa Graxx helmet (by Faven_PS)",
	"35 tennogenwarframehelmetsflair mirage-graxx-helmet": "Mirage Graxx helmet (by Faven_PS)",
	"36 tennogenwarframehelmetsflair mirage-jolli-helmet": "Mirage Jolli helmet (by Cheshire)",
	"72 tennogenwarframehelmetsflair mirage-morgaine-helmet": "Mirage Morgaine helmet (by artarrwen)",
	"37 tennogenwarframehelmetsflair mirage-sigyn-helmet": "Mirage Sigyn helmet (by Novabjorn)",
	"38 tennogenwarframehelmetsflair nekros-lazarus-helmet": "Nekros Lazarus helmet (by [k a z])",
	"93 tennogenwarframehelmetsflair nezha-devine-helmet": "Nezha Devine Helmet (by polygonmonster)",
	"103 tennogenwarframehelmetsflair nezha-yaksha-helmet": "Nezha Yaksha helmet (by Faven and SilverBones)",
	"39 tennogenwarframehelmetsflair nova-cygni-helmet": "Nova Cygni helmet (by Arsenal)",
	"40 tennogenwarframehelmetsflair nova-device-helmet": "Nova Device helmet (by prosetisen)",
	"41 tennogenwarframehelmetsflair nova-fusion-helmet": "Nova Fusion helmet (by Coridium)",
	"42 tennogenwarframehelmetsflair nova-gnova-helmet": "Nova Gnova helmet (by Faven_PS)",
	"94 tennogenwarframehelmetsflair nova-graxx": "Nova Graxx (by Faven_PS)",
	"43 tennogenwarframehelmetsflair nova-lamia-helmet": "Nova Lamia helmet (by Mz-3)",
	"44 tennogenwarframehelmetsflair nova-stinger-helmet": "Nova Stinger helmet (by Cheshire)",
	"45 tennogenwarframehelmetsflair nova-tachyon-helmet": "Nova Tachyon helmet (by Rekkou)",
	"46 tennogenwarframehelmetsflair nova-visage-helmet": "Nova Visage helmet (by Hitsu San)",
	"82 tennogenwarframehelmetsflair nyx-ampulex-helmet": "Nyx Ampulex helmet (by Vulbjorn, the walrus rider.)",
	"47 tennogenwarframehelmetsflair nyx-athena-helmet": "Nyx Athena helmet (by prosetisen)",
	"95 tennogenwarframehelmetsflair nyx-carnifex-helmet": "Nyx Carnifex Helmet (by Vulbjorn the Walrus Rider.)",
	"48 tennogenwarframehelmetsflair nyx-graxx-helmet": "Nyx Graxx helmet (by Faven_PS)",
	"73 tennogenwarframehelmetsflair nyx-saikou-helmet": "Nyx Saikou helmet helmet (by malayu)",
	"49 tennogenwarframehelmetsflair oberon-destrier-helmet": "Oberon Destrier helmet (by Rekkou)",
	"50 tennogenwarframehelmetsflair rhino-graxx-helmet": "Rhino Graxx helmet (by Faven_PS)",
	"74 tennogenwarframehelmetsflair rhino-teutonic-helmet": "Rhino Teutonic helmet (by Faven_PS)",
	/*"51 tennogenwarframehelmetsflair rhino-vojnik-helmet": "Rhino Vojnik Battle-Damaged helmet (by Volkovyi)",*/
	"83 tennogenwarframehelmetsflair rhino-warlust-helmet": "Rhino Warlust helmet (by Stenchfury)",
	"96 tennogenwarframehelmetsflair saryn-amalgama-helmet": "Saryn Amalgama Helmet (by prosetisen)",
	"84 tennogenwarframehelmetsflair saryn-belladonna-helmet": "Saryn Belladonna helmet (by Malayu)",
	"52 tennogenwarframehelmetsflair saryn-graxx-helmet": "Saryn Graxx helmet (by Faven_PS)",
	"75 tennogenwarframehelmetsflair saryn-integra-helmet": "Saryn Integra helmet (by Cheshire)",
	"104 tennogenwarframehelmetsflair titania-unseelie-helmet": "Titania Unseelie helmet (by Rekkou)",
	"85 tennogenwarframehelmetsflair trinity-ancyra-helmet": "Trinity Ancyra helmet (by Arsenal)",
	"53 tennogenwarframehelmetsflair trinity-messiah-helmet": "Trinity Messiah helmet (by Cheshire)",
	"54 tennogenwarframehelmetsflair valkyr-cheetah-helmet": "Valkyr Cheetah helmet (by Cheshire)",
	"105 tennogenwarframehelmetsflair valkyr-delusion-helmet": "Valkyr Delusion helmet (by prosetisen)",
	"55 tennogenwarframehelmetsflair valkyr-graxx-helmet": "Valkyr Graxx helmet (by Faven_PS)",
	"106 tennogenwarframehelmetsflair valkyr-ion-helmet": "Valkyr Ion helmet (by Yatus)",
	"56 tennogenwarframehelmetsflair vauban-chapelon-helmet": "Vauban Chapelon helmet (by Rekkou)",
	"76 tennogenwarframehelmetsflair vauban-suppressor-helmet": "Vauban Suppressor helmet (by Cheshire and prosetisen)",
	"57 tennogenwarframehelmetsflair volt-amp-helmet": "Volt Amp helmet (by Faven_PS)",
	"58 tennogenwarframehelmetsflair volt-arrester-helmet": "Volt Arrester helmet (by Rekkou)",
	"86 tennogenwarframehelmetsflair volt-capacitor-helmet": "Volt Capacitor helmet (by Del)",
	"59 tennogenwarframehelmetsflair volt-graxx-helmet": "Volt Graxx helmet (by Faven_PS)",
	"60 tennogenwarframehelmetsflair volt-relay-helmet": "Volt Relay helmet (by DespicableCheese)",
	"61 tennogenwarframehelmetsflair volt-thales-helmet": "Volt Thales helmet (by Arsenal)",
	"87 tennogenwarframehelmetsflair volt-zener-helmet": "Volt Zener helmet (by Rekkou)",
	"62 tennogenwarframehelmetsflair wukong-xingzhe-helmet": "Wukong Xingzhe helmet (by Rekkou)",
	"63 tennogenwarframehelmetsflair zephyr-hagoromo-helmet": "Zephyr Hagoromo helmet (by Hitsu San)",
	"64 tennogenwarframehelmetsflair zephyr-migisi-helmet": "Zephyr Migisi helmet (by FrellingHazmot)",
	"65 tennogenwarframehelmetsflair zephyr-monsoon-helmet": "Zephyr Monsoon helmet (by artarrwen)",
	"66 tennogenwarframehelmetsflair zephyr-skeiron-helmet": "Zephyr Skeiron helmet (by novadragon01)",


	/* Other Warframe Helmets (0-71) */
	"0 otherwarframehelmetsflair ash-locust-helmet": "Ash Locust helmet",
	"1 otherwarframehelmetsflair ash-scorpion-helmet": "Ash Scorpion helmet",
	"2 otherwarframehelmetsflair atlas-shikoro-helmet": "Atlas Shikoro helmet",
	"3 otherwarframehelmetsflair atlas-tartarus-helmet": "Atlas Tartarus helmet",
	"4 otherwarframehelmetsflair banshee-chorus-helmet": "Banshee Chorus helmet",
	"5 otherwarframehelmetsflair banshee-reverb-helmet": "Banshee Reverb helmet",
	"6 otherwarframehelmetsflair chroma-amaru-helmet": "Chroma Amaru helmet",
	"7 otherwarframehelmetsflair chroma-drac-helmet": "Chroma Drac helmet",
	"8 otherwarframehelmetsflair ember-backdraft-helmet": "Ember Backdraft helmet",
	"9 otherwarframehelmetsflair ember-phoenix-helmet": "Ember Phoenix helmet",
	"68 otherwarframehelmetsflair equinox-day-helmet": "Equinox Day helmet",
	"69 otherwarframehelmetsflair equinox-night-helmet": "Equinox Night helmet",
	"10 otherwarframehelmetsflair equinox-solstice-helmet": "Equinox Solstice helmet",
	"11 otherwarframehelmetsflair excalibur-avalon-helmet": "Excalibur Avalon helmet",
	/*"12 otherwarframehelmetsflair excalibur-jade-helmet": "Excalibur Jade helmet (XB1 exclusive)",*/
	"13 otherwarframehelmetsflair excalibur-mordred-helmet": "Excalibur Mordred helmet",
	"14 otherwarframehelmetsflair excalibur-obsidian-helmet": "Excalibur Obsidian helmet (PS4 exclusive)",
	"15 otherwarframehelmetsflair excalibur-obsidian-azura-helmet": "Excalibur Obsidian Azura helmet (PS4 exclusive)",
	"16 otherwarframehelmetsflair excalibur-pendragon-helmet": "Excalibur Pendragon helmet",
	"17 otherwarframehelmetsflair excalibur-prisma-helmet": "Excalibur Prisma helmet",
	"18 otherwarframehelmetsflair excalibur-prisma-avalon-helmet": "Excalibur Prisma Avalon helmet",
	"19 otherwarframehelmetsflair excalibur-prisma-pendragon-helmet": "Excalibur Prisma Pendragon helmet",
	"74 otherwarframehelmetsflair excalibur-twitch-helmet": "Excalibur Twitch helmet",
	"20 otherwarframehelmetsflair frost-aurora-helmet": "Frost Aurora helmet",
	"21 otherwarframehelmetsflair frost-squall-helmet": "Frost Squall helmet",
	"82 otherwarframehelmetsflair gara-suffragan-helmet": "Gara Virago helmet",
	"80 otherwarframehelmetsflair harrow-suffragan-helmet": "Harrow Suffragan helmet",
	"22 otherwarframehelmetsflair hydroid-ketos-helmet": "Hydroid Ketos helmet",
	"23 otherwarframehelmetsflair hydroid-triton-helmet": "Hydroid Triton helmet",
	"24 otherwarframehelmetsflair inaros-anubis-helmet": "Inaros Anubis helmet",
	"66 otherwarframehelmetsflair inaros-canopic-helmet": "Inaros Canopic helmet",
	"25 otherwarframehelmetsflair ivara-loxley-helmet": "Ivara Loxley helmet",
	"83 otherwarframehelmetsflair ivara-obsidian-azura-helmet": "Obsidian Azura Ivara helmet (PS4 Renown Pack exclusive)",
	"67 otherwarframehelmetsflair ivara-zirastra-helmet": "Ivara Zirastra helmet",
	"26 otherwarframehelmetsflair limbo-aristeas-helmet": "Limbo Aristeas helmet",
	"27 otherwarframehelmetsflair limbo-magrite-helmet": "Limbo Magrite helmet",
	"28 otherwarframehelmetsflair loki-enigma-helmet": "Loki Enigma helmet",
	"29 otherwarframehelmetsflair loki-essence-helmet": "Loki Essence helmet",
	"30 otherwarframehelmetsflair loki-swindle-helmet": "Loki Swindle helmet",
	"31 otherwarframehelmetsflair mag-coil-helmet": "Mag Coil helmet",
	"32 otherwarframehelmetsflair mag-gauss-helmet": "Mag Gauss helmet",
	"33 otherwarframehelmetsflair mesa-longhorn-helmet": "Mesa Longhorn helmet",
	"34 otherwarframehelmetsflair mesa-ovis-helmet": "Mesa Ovis helmet",
	"35 otherwarframehelmetsflair mirage-harlequin-helmet": "Mirage Harlequin helmet",
	"36 otherwarframehelmetsflair mirage-trivelin-helmet": "Mirage Trivelin helmet",
	"37 otherwarframehelmetsflair nekros-raknis-helmet": "Nekros Raknis helmet",
	"38 otherwarframehelmetsflair nekros-shroud-helmet": "Nekros Shroud helmet",
	"39 otherwarframehelmetsflair nezha-circa-helmet": "Nezha Circa helmet",
	"40 otherwarframehelmetsflair nidus-prion-helmet": "Nidus Prion helmet",
	"41 otherwarframehelmetsflair nova-flux-helmet": "Nova Flux helmet",
	"42 otherwarframehelmetsflair nova-quantum-helmet": "Nova Quantum helmet",
	"43 otherwarframehelmetsflair nova-slipstream-helmet": "Nova Slipstream helmet",
	"44 otherwarframehelmetsflair nyx-menticide-helmet": "Nyx Menticide helmet",
	"45 otherwarframehelmetsflair nyx-vespa-helmet": "Nyx Vespa helmet",
	"46 otherwarframehelmetsflair oberon-markhor-helmet": "Oberon Markhor helmet",
	"47 otherwarframehelmetsflair oberon-oryx-helmet": "Oberon Oryx helmet",
	"75 otherwarframehelmetsflair octavia-cadenza-helmet": "Octavia Cadenza helmet",
	"48 otherwarframehelmetsflair rhino-rubedo-helmet": "Rhino Rubedo helmet (Steam exclusive)",
	"49 otherwarframehelmetsflair rhino-thrak-helmet": "Rhino Thrak helmet",
	"50 otherwarframehelmetsflair rhino-vanguard-helmet": "Rhino Vanguard helmet",
	"51 otherwarframehelmetsflair saryn-chlora-helmet": "Saryn Chlora helmet",
	"52 otherwarframehelmetsflair saryn-hemlock-helmet": "Saryn Hemlock helmet",
	"53 otherwarframehelmetsflair titania-aurai-helmet": "Titania Aurai helmet",
	"54 otherwarframehelmetsflair trinity-aura-helmet": "Trinity Aura helmet",
	"55 otherwarframehelmetsflair trinity-meridian-helmet": "Trinity Meridian helmet",
	"56 otherwarframehelmetsflair valkyr-bastet-helmet": "Valkyr Bastet helmet",
	"76 otherwarframehelmetsflair valkyr-bastet-helmet-alt": "Valkyr Bastet helmet (alternate picture)",
	"57 otherwarframehelmetsflair valkyr-kara-helmet": "Valkyr Kara helmet",
	"58 otherwarframehelmetsflair vauban-armistice-helmet": "Vauban Armistice helmet",
	"59 otherwarframehelmetsflair vauban-esprit-helmet": "Vauban Esprit helmet",
	"60 otherwarframehelmetsflair vauban-gambit-helmet": "Vauban Gambit helmet",
	"70 otherwarframehelmetsflair vauban-phased-helmet": "Vauban Phased helmet",
	"61 otherwarframehelmetsflair volt-pulse-helmet": "Volt Pulse helmet",
	"62 otherwarframehelmetsflair volt-storm-helmet": "Volt Storm helmet",
	"63 otherwarframehelmetsflair wukong-dasheng-helmet": "Wukong Dasheng helmet",
	"77 otherwarframehelmetsflair wukong-macak-helmet-alt": "Wukong Macak helmet",
	"64 otherwarframehelmetsflair zephyr-cierzo-helmet": "Zephyr Cierzo helmet",
	"65 otherwarframehelmetsflair zephyr-tengu-helmet": "Zephyr Tengu helmet",
	"78 otherwarframehelmetsflair dullahan-mask": "Dullahan Mask (Halloween exclusive)",
	
	
	/* Archwings (100-108) */
	"100 archwingsflair odonata-prime": "Odonata Prime",
	"101 archwingsflair amesha": "Amesha",
	"102 archwingsflair elytron": "Elytron",
	"103 archwingsflair itzal": "Itzal",
	"104 archwingsflair odonata": "Odonata",
	"105 archwingsflair elytron-bundle": "Elytron (Ultimatum Bundle)",
	"106 archwingsflair itzal-bundle": "Itzal (Raider Pack)",
	"107 archwingsflair itzal-jade-skin": "Itzal Jade skin (XB1 exclusive)",
	"108 archwingsflair odonata-obsidian-skin": "Odonata Obsidian skin (PS4 exclusive)",
	
	
	/* Operators (150-156) */	
	"150 operatorsflair saita-prime-operator-hood": "Saita Prime operator hood",
	"151 operatorsflair zariman-operator-hood": "Zariman operator hood",
	"152 operatorsflair koppra-operator-suit": "Koppra operator suit",
	"153 operatorsflair manduka-operator-suit": "Manduka operator suit",
	"154 operatorsflair varida-operator-suit": "Varida operator suit",
	"155 operatorsflair koppra-operator-suit-bundle": "Koppra operator suit (Operator Suit Collection)",
	"156 operatorsflair varida-operator-suit-bundle": "Varida operator suit (Operator Suit Collection)",

	
	/* Companions (0-79) */
	"0 sentinelsflair carrier-prime": "Carrier Prime",
	"79 sentinelsflair helios-prime": "Helios Prime",
	"1 sentinelsflair wyrm-prime": "Wyrm Prime",
	"2 sentinelsflair shade-prisma": "Shade Prisma skin",
	"3 sentinelsflair carrier": "Carrier",
	"4 sentinelsflair dethcube": "Dethcube",
	"32 sentinelsflair dethcube-bundle": "Dethcube (Sentinel Accessory Pack)",
	"5 sentinelsflair diriga": "Diriga",
	"6 sentinelsflair djinn": "Djinn",
	"7 sentinelsflair helios": "Helios",
	"33 sentinelsflair helios-bundle": "Helios (Ictus Sentinel Pack)",
	"8 sentinelsflair shade": "Shade",
	"34 sentinelsflair shade-bundle": "Shade (Sentinel Accessory Pack 2)",
	"9 sentinelsflair taxon": "Taxon",
	"10 sentinelsflair wyrm": "Wyrm",
	"80 sentinelsflair carrier-jade-skin": "Carrier Jade skin (XB1 Prestige Pack exclusive)",
	"11 sentinelsflair carrier-para-skin": "Carrier Para skin",
	"12 sentinelsflair carrier-para-bundle": "Carrier Para (Update 13 Mega Pack)",
	"13 sentinelsflair dethcube-carabus-skin": "Dethcube Carabus skin",
	"14 sentinelsflair dethcube-forest-camo-skin": "Dethcube Forest-Camo skin",
	"15 sentinelsflair dethcube-jade-skin": "Dethcube Jade skin (XB1 exclusive)",
	"81 sentinelsflair dethcube-jade-skin-alt": "Dethcube Jade skin (XB1 Prestige Pack exclusive)",
	"16 sentinelsflair diriga-nightwatch-skin": "Diriga Nightwatch skin",
	"17 sentinelsflair djinn-gazal-skin": "Djinn Gazal skin",
	"18 sentinelsflair helios-obsidian-skin": "Helios Obsidian skin (PS4 exclusive)",
	"19 sentinelsflair helios-simaris-skin": "Helios Simaris skin",
	"20 sentinelsflair shade-sprite-skin": "Shade Sprite skin",
	"21 sentinelsflair wyrm-obsidian-skin": "Wyrm Obsidian skin (PS4 exclusive)",
	
	"35 companionsflair helminth-charger": "Helminth Charger",
	"36 companionsflair helminth-charger-alt": "Helminth Charger (alternate picture)",
	"37 companionsflair helminth-charger-degenerate-pattern": "Helminth Charger Degenerate pattern",
	
	"38 kavatsflair adarza-kavat": "Adarza Kavat",
	"39 kavatsflair smeeta-kavat": "Smeeta Kavat",
	"40 kavatsflair feral-kavat": "Feral Kavat",
	"41 kavatsflair hyekka": "Hyekka",
	"42 kavatsflair kavat-hyekka-skin": "Kavat Hyekka skin",
	"43 kavatsflair kavat-day-of-the-dead-wysar-armor": "Kavat Day of the Dead Wysar armor (Halloween exclusive)",
	"44 kavatsflair kavat-ki’teer-armor": "Kavat Ki’Teer armor",
	"45 kavatsflair kavat-kuva-armor": "Kavat Kuva armor",
	"46 kavatsflair kavat-myrdin-armor": "Kavat Myrdin armor",
	"47 kavatsflair kavat-saraba-armor": "Kavat Saraba armor",
	"48 kavatsflair kavat-wysar-armor": "Kavat Wysar armor",
	"49 kavatsflair kavat-argyl-fur-pattern": "Kavat Argyl fur pattern",
	"82 kavatsflair kavat-feral-pattern": "Kavat Feral fur pattern",
	"50 kavatsflair kavat-krest-fur-pattern": "Kavat Krest fur pattern",
	"51 kavatsflair kavat-nesyr-fur-pattern": "Kavat Nesyr fur pattern",
	"52 kavatsflair kavat-nexus-fur-pattern": "Kavat Nexus fur pattern",
	"53 kavatsflair kavat-solstice-fur-pattern": "Kavat Solstice fur pattern (winter exclusive)",
	"22 kavatsflair kavat-a": "Kavat",
	"23 kavatsflair kavat-b": "Kavat",
	"24 kavatsflair kavat-c": "Kavat",
	"25 kavatsflair kavat-d": "Kavat",
	
	"54 kubrowsflair kubrow-kavasa-fur-pattern": "Kubrow Kavasa fur pattern",
	"26 kubrowsflair kubrow": "Kubrow",
	"55 kubrowsflair kubrow-alt": "Kubrow (alternate picture)",
	"27 kubrowsflair kubrow-chesa": "Chesa Kubrow",
	"28 kubrowsflair kubrow-huras": "Huras Kubrow",
	"29 kubrowsflair kubrow-raksa": "Raksa Kubrow",
	"30 kubrowsflair kubrow-sahasa": "Sahasa Kubrow",
	"31 kubrowsflair kubrow-sunika": "Sunika Kubrow",
	"56 kubrowsflair drahk": "Drahk",
	"57 kubrowsflair feral-kubrow": "Feral Kubrow",
	"58 kubrowsflair kubrow-kavasa-prime-armor": "Kubrow Kavasa Prime armor",
	"59 kubrowsflair kubrow-bruja-armor": "Kubrow Bruja armor",
	"60 kubrowsflair kubrow-ifrit-armor": "Kubrow Ifrit armor",
	"61 kubrowsflair kubrow-jade-armor": "Kubrow Jade armor (XB1 exclusive)",
	"87 kubrowsflair kubrow-jade-valinn-armor": "Kubrow Jade Valinn armor (XB1 Prestige Pack exclusive)",
	"62 kubrowsflair kubrow-ki’teer-armor": "Kubrow Ki’Teer armor",
	"63 kubrowsflair kubrow-kuva-armor": "Kubrow Kuva armor",
	"64 kubrowsflair kubrow-pakal-armor": "Kubrow Pakal armor",
	"65 kubrowsflair kubrow-rostam-armor": "Kubrow Rostam armor",
	"66 kubrowsflair kubrow-valinn-armor": "Kubrow Valinn armor",
	"67 kubrowsflair kubrow-little-helper-hat": "Kubrow Little Helper Hat (winter exclusive)",
	"68 kubrowsflair kubrow-arklut-fur-pattern": "Kubrow Arklut fur pattern",
	"69 kubrowsflair kubrow-atrox-fur-pattern": "Kubrow Atrox fur pattern",
	"70 kubrowsflair kubrow-bold-fur-pattern": "Kubrow Bold fur pattern",
	"83 kubrowsflair kubrow-drahk-pattern": "Kubrow Drahk fur pattern",
	"84 kubrowsflair kubrow-drahk-pattern-alt": "Kubrow Drahk fur pattern (gene-masking kit)",
	"85 kubrowsflair kubrow-feral-pattern": "Kubrow Feral fur pattern",
	"71 kubrowsflair kubrow-lotus-fur-pattern": "Kubrow Lotus fur pattern",
	"72 kubrowsflair kubrow-nart-deer-fur-pattern": "Kubrow Nart-Deer fur pattern (winter exclusive)",
	"73 kubrowsflair kubrow-nexus-fur-pattern": "Kubrow Nexus fur pattern",
	"74 kubrowsflair kubrow-nistlebrush-fur-pattern": "Kubrow Nistlebrush fur pattern (winter exclusive)",
	"75 kubrowsflair kubrow-savenga-fur-pattern": "Kubrow Savenga fur pattern",
	"76 kubrowsflair kubrow-solstice-fur-pattern": "Kubrow Solstice fur pattern (winter exclusive)",
	"77 kubrowsflair kubrow-telmatian-fur-pattern": "Kubrow Telmatian fur pattern",
	"78 kubrowsflair kubrow-tigrol-fur-pattern": "Kubrow Tigrol fur pattern",
	"86 kubrowsflair kubrow-underbrush-pattern": "Kubrow Underbrush fur pattern",

	
	/* glyphs (0-77) */
	"0 glyphsflair ash-in-action-glyph": "Ash in Action glyph",
	"52 glyphsflair banshee-in-action-glyph": "Banshee in Action glyph",
	"1 glyphsflair blood-lotus-glyph": "Blood Lotus glyph",
	"2 glyphsflair butterfly-varna-glyph": "Butterfly Varna glyph",
	"3 glyphsflair ceph-pinacoid-glyph": "Ceph Pinacoid glyph",
	"4 glyphsflair clem-in-action-glyph": "Clem in Action glyph",
	"60 glyphsflair donwyn-glyph-i": "Donwyn glyph I (Valentine’s Day exclusive)",
	"61 glyphsflair donwyn-glyph-ii": "Donwyn glyph II (Valentine’s Day exclusive)",
	"62 glyphsflair donwyn-glyph-iii": "Donwyn glyph III (Valentine’s Day exclusive)",
	"63 glyphsflair donwyn-glyph-iv": "Donwyn glyph IV (Valentine’s Day exclusive)",
	"64 glyphsflair donwyn-glyph-v-": "Donwyn glyph V (Valentine’s Day exclusive)",
	"5 glyphsflair ember-in-action-glyph": "Ember in Action glyph",
	"6 glyphsflair excalibur-in-action-glyph": "Excalibur in Action glyph",
	"77 glyphsflair jade-excalibur-in-action-glyph": "Jade Excalibur in Action glyph",
	"7 glyphsflair excalibur-noggle-glyph": "Excalibur noggle glyph",
	"53 glyphsflair frost-in-action-glyph": "Frost in Action glyph",
	"8 glyphsflair ginger-kubrow-varna-glyph": "Ginger Kubrow Varna glyph",
	"9 glyphsflair grey-kubrow-varna-glyph": "Grey Kubrow Varna glyph",
	"10 glyphsflair grineer-queens-glyph": "Grineer Queens glyph",
	"71 glyphsflair halftone-nidus-glyph": "Nidus Halftone glyph",
	"72 glyphsflair halftone-inaros-glyph": "Inaros Halftone glyph",
	"73 glyphsflair halftone-octavia-glyph": "Octavia Halftone glyph",
	"74 glyphsflair halftone-ivara-glyph": "Ivara Halftone glyph",
	"75 glyphsflair halftone-maroo-glyph": "Maroo Halftone glyph",
	"76 glyphsflair halftone-atlas-glyph": "Atlas Halftone glyph",
	"11 glyphsflair hydroid-submerged-glyph": "Hydroid Submerged glyph",
	"12 glyphsflair isochronon-glyph": "Isochronon glyph",
	"13 glyphsflair kavat-enamel-glyph": "Kavat Enamel glyph",
	"14 glyphsflair kubrow-enamel-glyph": "Kubrow Enamel glyph",
	"15 glyphsflair kuria-glyph": "Kuria glyph",
	"16 glyphsflair kuria-idolized-glyph": "Kuria Idolized glyph",
	"17 glyphsflair loki-in-action-glyph": "Loki in Action glyph",
	"18 glyphsflair loki-noggle-glyph": "Loki noggle glyph",
	"19 glyphsflair lotus-balance-glyph": "Lotus Balance glyph",
	"20 glyphsflair lotus-noggle-glyph": "Lotus noggle glyph",
	"21 glyphsflair lunaro-glyph": "Lunaro glyph",
	"22 glyphsflair mag-in-action-glyph": "Mag in Action glyph",
	"23 glyphsflair mag-noggle-glyph": "Mag noggle glyph",
	"65 glyphsflair memetica-greedy-milk-glyph": "Greedy Milk Memetica glyph",
	"66 glyphsflair memetica-potato-glyph": "Potato Memetica glyph",
	"67 glyphsflair memetica-prodman-glyph": "Prodman Memetica glyph",
	"68 glyphsflair memetica-pink-shorts-glyph": "Pink Shorts Memetica glyph",
	"24 glyphsflair mesa-fixated-glyph": "Mesa Fixated glyph",
	"25 glyphsflair moon-crest-glyph": "Moon Crest glyph",
	"26 glyphsflair mythic-balance-glyph": "Mythic Balance glyph",
	"27 glyphsflair nekros-day-of-the-dead-glyph": "Nekros Day of the Dead glyph",
	"54 glyphsflair nekros-in-action-glyph": "Nekros in Action glyph",
	"55 glyphsflair nova-in-action-glyph": "Nova in Action glyph",
	"56 glyphsflair nyx-in-action-glyph": "Nyx in Action glyph",
	"28 glyphsflair orbital-cathode-glyph": "Orbital Cathode glyph",
	"69 glyphsflair prisma-glyph": "Prisma glyph",
	"29 glyphsflair rhino-in-action-glyph": "Rhino in Action glyph",
	"30 glyphsflair rhino-noggle-glyph": "Rhino noggle glyph",
	"57 glyphsflair saryn-in-action-glyph": "Saryn in Action glyph",
	"31 glyphsflair scarab-varna-glyph": "Scarab Varna glyph",
	"32 glyphsflair solstice-i-glyph": "Solstice I glyph (winter exclusive)",
	"33 glyphsflair solstice-ii-glyph": "Solstice II glyph (winter exclusive)",
	"34 glyphsflair solstice-iii-glyph": "Solstice III glyph (winter exclusive)",
	"35 glyphsflair solstice-iv-glyph": "Solstice IV glyph (winter exclusive)",
	"36 glyphsflair solunar-glyph": "Solunar glyph",
	"37 glyphsflair sooty-kubrow-varna-glyph": "Sooty Kubrow Varna glyph",
	"38 glyphsflair sun-crest-glyph": "Sun Crest glyph",
	"39 glyphsflair tenno-refractal-glyph": "Tenno Refractal glyph",
	"70 glyphsflair tennocon-2017-glyph": "TennoCon 2017 glyph",
	"40 glyphsflair teshin-glyph": "Teshin glyph",
	"41 glyphsflair threshcone-varna-glyph": "Threshcone Varna glyph",
	"42 glyphsflair trinity-in-action-glyph": "Trinity in Action glyph",
	"58 glyphsflair valkyr-in-action-glyph": "Valkyr in Action glyph",
	"59 glyphsflair vauban-in-action-glyph": "Vauban in Action glyph",
	"43 glyphsflair volt-in-action-glyph": "Volt in Action glyph",
	"44 glyphsflair vor-varna-glyph": "Vor Varna glyph",
	"45 glyphsflair winter-i-glyph": "Winter I glyph (winter exclusive)",
	"46 glyphsflair winter-ii-glyph": "Winter II glyph (winter exclusive)",
	"47 glyphsflair winter-iii-glyph": "Winter III glyph (winter exclusive)",
	"48 glyphsflair winter-iv-glyph": "Winter IV glyph (winter exclusive)",
	"49 glyphsflair winter-v-glyph": "Winter V glyph (winter exclusive)",
	"50 glyphsflair winter-vi-glyph": "Winter VI glyph (winter exclusive)",
	"51 glyphsflair winter-vii-glyph": "Winter VII glyph (winter exclusive)",

	
	
	/* sigils (0-210)*/	
	"198 sigilsflair assassin-grustrag-3-sigil": "Grustrag 3 sigil",
	"199 sigilsflair assassin-stalker-sigil-red": "Stalker sigil (red)",
	"200 sigilsflair assassin-stalker-sigil": "Stalker sigil",
	"201 sigilsflair assassin-zanuka-hunter-sigil": "Zanuka Hunter sigil",
	"0 sigilsflair boss-alad-v-sigil": "Alad V sigil",
	"1 sigilsflair boss-ambulas-sigil": "Ambulas sigil",
	"2 sigilsflair boss-captain-vor-sigil": "Captain Vor sigil",
	"3 sigilsflair boss-councilor-vey-hek-sigil": "Councilor Vey Hek sigil",
	"4 sigilsflair boss-general-sargas-ruk-sigil": "General Sargas Ruk sigil",
	"5 sigilsflair boss-hyena-pack-sigil": "Hyena Pack sigil",
	"6 sigilsflair boss-jackal-sigil": "Jackal sigil",
	"7 sigilsflair boss-kela-de-thaym-sigil": "Kela De Thaym sigil",
	"8 sigilsflair boss-lephantis-sigil": "Lephantis sigil",
	"9 sigilsflair boss-lieutenant-lech-kril-sigil": "Lieutenant Lech Kril sigil",
	"10 sigilsflair boss-lynx-sigil": "Lynx sigil",
	"11 sigilsflair boss-nef-anyo-sigil": "Nef Anyo sigil",
	"12 sigilsflair boss-phorid-sigil": "Phorid sigil",
	"13 sigilsflair boss-raptor-sigil": "Raptor sigil",
	"14 sigilsflair boss-tyl-regor-sigil": "Tyl Regor sigil",
	"132 sigilsflair syndicate-arbiters-of-hexis-sigil-grey": "Arbiters of Hexis sigil (grey)",
	"133 sigilsflair syndicate-arbiters-of-hexis-level-1-sigil-grey": "Arbiters of Hexis Guiding Path sigil (grey)",
	"134 sigilsflair syndicate-arbiters-of-hexis-level-2-sigil-grey": "Arbiters of Hexis Bending Will sigil (grey)",
	"135 sigilsflair syndicate-arbiters-of-hexis-level-3-sigil-grey": "Arbiters of Hexis Discipline sigil (grey)",
	"136 sigilsflair syndicate-arbiters-of-hexis-level-4-sigil-grey": "Arbiters of Hexis Will sigil (grey)",
	"137 sigilsflair syndicate-arbiters-of-hexis-level-5-sigil-grey": "Arbiters of Hexis Choice sigil (grey)",
	"138 sigilsflair syndicate-arbiters-of-hexis-level-6-sigil-grey": "Arbiters of Hexis Growth sigil (grey)",
	"139 sigilsflair syndicate-arbiters-of-hexis-level-7-sigil-grey": "Arbiters of Hexis Potential sigil (grey)",
	"140 sigilsflair syndicate-arbiters-of-hexis-level-8-sigil-grey": "Arbiters of Hexis Succession sigil (grey)",
	"141 sigilsflair syndicate-arbiters-of-hexis-level-9-sigil-grey": "Arbiters of Hexis Surpassing sigil (grey)",
	"142 sigilsflair syndicate-arbiters-of-hexis-level-10-sigil-grey": "Arbiters of Hexis Truth sigil (grey)",
	"27 sigilsflair syndicate-cephalon-simaris-gold-sigil": "Cephalon Simaris sigil (gold)",
	"143 sigilsflair syndicate-cephalon-suda-sigil-yellow": "Cephalon Suda sigil (yellow)",
	"144 sigilsflair syndicate-cephalon-suda-level-1-sigil-yellow": "Cephalon Suda Query sigil (yellow)",
	"145 sigilsflair syndicate-cephalon-suda-level-2-sigil-yellow": "Cephalon Suda Searching sigil (yellow)",
	"146 sigilsflair syndicate-cephalon-suda-level-3-sigil-yellow": "Cephalon Suda Pattern Match sigil (yellow)",
	"147 sigilsflair syndicate-cephalon-suda-level-4-sigil-yellow": "Cephalon Suda Atomic sigil (yellow)",
	"148 sigilsflair syndicate-cephalon-suda-level-5-sigil-yellow": "Cephalon Suda Manifold sigil (yellow)",
	"149 sigilsflair syndicate-cephalon-suda-level-6-sigil-yellow": "Cephalon Suda Fractal sigil (yellow)",
	"150 sigilsflair syndicate-cephalon-suda-level-7-sigil-yellow": "Cephalon Suda Multivariate sigil (yellow)",
	"151 sigilsflair syndicate-cephalon-suda-level-8-sigil-yellow": "Cephalon Suda Labryinth sigil (yellow)",
	"152 sigilsflair syndicate-cephalon-suda-level-9-sigil-yellow": "Cephalon Suda Hexan sigil (yellow)",
	"153 sigilsflair syndicate-cephalon-suda-level-10-sigil-yellow": "Cephalon Suda Oracle sigil (yellow)",
	"39 sigilsflair syndicate-conclave-sigil": "Conclave sigil",
	"40 sigilsflair syndicate-conclave-level-1-sigil": "Conclave Awakening sigil",
	"41 sigilsflair syndicate-conclave-level-2-sigil": "Conclave Perception sigil",
	"42 sigilsflair syndicate-conclave-level-3-sigil": "Conclave Awareness sigil",
	"43 sigilsflair syndicate-conclave-level-4-sigil": "Conclave Revelation sigil",
	"44 sigilsflair syndicate-conclave-level-5-sigil": "Conclave Diligence sigil",
	"45 sigilsflair syndicate-conclave-level-6-sigil": "Conclave Enlightenment sigil",
	"46 sigilsflair syndicate-conclave-level-7-sigil": "Conclave Prudence sigil",
	"47 sigilsflair syndicate-conclave-level-8-sigil": "Conclave Discretion sigil",
	"48 sigilsflair syndicate-conclave-level-9-sigil": "Conclave Ambition sigil",
	"49 sigilsflair syndicate-conclave-level-10-sigil": "Conclave Volition sigil",
	"50 sigilsflair syndicate-conclave-level-11-sigil": "Conclave Discovery sigil",
	"51 sigilsflair syndicate-conclave-level-12-sigil": "Conclave Accord sigil",
	"52 sigilsflair syndicate-conclave-level-13-sigil": "Conclave Insight sigil",
	"53 sigilsflair syndicate-conclave-level-14-sigil": "Conclave Empathy sigil",
	"54 sigilsflair syndicate-conclave-level-15-sigil": "Conclave Unity sigil",
	"55 sigilsflair syndicate-conclave-level-16-sigil": "Conclave Freedom sigil",
	"154 sigilsflair syndicate-new-loka-sigil-green": "New Loka sigil (green)",
	"155 sigilsflair syndicate-new-loka-level-1-sigil-green": "New Loka Sacrifice sigil (green)",
	"156 sigilsflair syndicate-new-loka-level-2-sigil-green": "New Loka Seed sigil (green)",
	"157 sigilsflair syndicate-new-loka-level-3-sigil-green": "New Loka Rebirth sigil (green)",
	"158 sigilsflair syndicate-new-loka-level-4-sigil-green": "New Loka Growth sigil (green)",
	"159 sigilsflair syndicate-new-loka-level-5-sigil-green": "New Loka Clarity sigil (green)",
	"160 sigilsflair syndicate-new-loka-level-6-sigil-green": "New Loka Bloom sigil (green)",
	"161 sigilsflair syndicate-new-loka-level-7-sigil-green": "New Loka Purity sigil (green)",
	"162 sigilsflair syndicate-new-loka-level-8-sigil-green": "New Loka Gaia sigil (green)",
	"163 sigilsflair syndicate-new-loka-level-9-sigil-green": "New Loka Bounty sigil (green)",
	"164 sigilsflair syndicate-new-loka-level-10-sigil-green": "New Loka Humanity sigil (green)",
	"165 sigilsflair syndicate-red-veil-sigil-red": "Red Veil sigil (red)",
	"166 sigilsflair syndicate-red-veil-level-1-sigil-red": "Red Veil Blades sigil (red)",
	"167 sigilsflair syndicate-red-veil-level-2-sigil-red": "Red Veil Cull sigil (red)",
	"168 sigilsflair syndicate-red-veil-level-3-sigil-red": "Red Veil Threat sigil (red)",
	"169 sigilsflair syndicate-red-veil-level-4-sigil-red": "Red Veil Maelstrom sigil (red)",
	"170 sigilsflair syndicate-red-veil-level-5-sigil-red": "Red Veil Lesion sigil (red)",
	"171 sigilsflair syndicate-red-veil-level-6-sigil-red": "Red Veil Ruin sigil (red)",
	"172 sigilsflair syndicate-red-veil-level-7-sigil-red": "Red Veil Viscera sigil (red)",
	"173 sigilsflair syndicate-red-veil-level-8-sigil-red": "Red Veil Malevolent sigil (red)",
	"174 sigilsflair syndicate-red-veil-level-9-sigil-red": "Red Veil Covert sigil (red)",
	"175 sigilsflair syndicate-red-veil-level-10-sigil-red": "Red Veil Assassin sigil (red)",
	"176 sigilsflair syndicate-steel-meridian-sigil-orange": "Steel Meridian sigil (orange)",
	"177 sigilsflair syndicate-steel-meridian-level-1-sigil-orange": "Steel Meridian Defiance sigil (orange)",
	"178 sigilsflair syndicate-steel-meridian-level-2-sigil-orange": "Steel Meridian Armada sigil (orange)",
	"179 sigilsflair syndicate-steel-meridian-level-3-sigil-orange": "Steel Meridian Vigilance sigil (orange)",
	"180 sigilsflair syndicate-steel-meridian-level-4-sigil-orange": "Steel Meridian Uprising sigil (orange)",
	"181 sigilsflair syndicate-steel-meridian-level-5-sigil-orange": "Steel Meridian Protectorate sigil (orange)",
	"182 sigilsflair syndicate-steel-meridian-level-6-sigil-orange": "Steel Meridian Freedom Fighter sigil (orange)",
	"183 sigilsflair syndicate-steel-meridian-level-7-sigil-orange": "Steel Meridian Armored sigil (orange)",
	"184 sigilsflair syndicate-steel-meridian-level-8-sigil-orange": "Steel Meridian Rebellion sigil (orange)",
	"185 sigilsflair syndicate-steel-meridian-level-9-sigil-orange": "Steel Meridian Unyielding sigil (orange)",
	"186 sigilsflair syndicate-steel-meridian-level-10-sigil-orange": "Steel Meridian Champion sigil (orange)",
	"187 sigilsflair syndicate-the-perrin-sequence-sigil-blue": "The Perrin Sequence sigil (blue)",
	"188 sigilsflair syndicate-the-perrin-sequence-level-1-sigil-blue": "The Perrin Sequence Progress sigil (blue)",
	"189 sigilsflair syndicate-the-perrin-sequence-level-2-sigil-blue": "The Perrin Sequence Opportunity sigil (blue)",
	"190 sigilsflair syndicate-the-perrin-sequence-level-3-sigil-blue": "The Perrin Sequence Calculating sigil (blue)",
	"191 sigilsflair syndicate-the-perrin-sequence-level-4-sigil-blue": "The Perrin Sequence Synergy sigil (blue)",
	"192 sigilsflair syndicate-the-perrin-sequence-level-5-sigil-blue": "The Perrin Sequence Directives sigil (blue)",
	"193 sigilsflair syndicate-the-perrin-sequence-level-6-sigil-blue": "The Perrin Sequence Strategy sigil (blue)",
	"194 sigilsflair syndicate-the-perrin-sequence-level-7-sigil-blue": "The Perrin Sequence Tessilations [sic] sigil (blue)",
	"195 sigilsflair syndicate-the-perrin-sequence-level-8-sigil-blue": "The Perrin Sequence Optimum sigil (blue)",
	"196 sigilsflair syndicate-the-perrin-sequence-level-9-sigil-blue": "The Perrin Sequence Capital sigil (blue)",
	"197 sigilsflair syndicate-the-perrin-sequence-level-10-sigil-blue": "The Perrin Sequence Chairman sigil (blue)",
	"15 sigilsflair syndicate-arbiters-of-hexis-sigil": "Arbiters of Hexis sigil",
	"16 sigilsflair syndicate-arbiters-of-hexis-level-1-sigil": "Arbiters of Hexis Guiding Path sigil",
	"17 sigilsflair syndicate-arbiters-of-hexis-level-2-sigil": "Arbiters of Hexis Bending Will sigil",
	"18 sigilsflair syndicate-arbiters-of-hexis-level-3-sigil": "Arbiters of Hexis Discipline sigil",
	"19 sigilsflair syndicate-arbiters-of-hexis-level-4-sigil": "Arbiters of Hexis Will sigil",
	"20 sigilsflair syndicate-arbiters-of-hexis-level-5-sigil": "Arbiters of Hexis Choice sigil",
	"21 sigilsflair syndicate-arbiters-of-hexis-level-6-sigil": "Arbiters of Hexis Growth sigil",
	"22 sigilsflair syndicate-arbiters-of-hexis-level-7-sigil": "Arbiters of Hexis Potential sigil",
	"23 sigilsflair syndicate-arbiters-of-hexis-level-8-sigil": "Arbiters of Hexis Succession sigil",
	"24 sigilsflair syndicate-arbiters-of-hexis-level-9-sigil": "Arbiters of Hexis Surpassing sigil",
	"25 sigilsflair syndicate-arbiters-of-hexis-level-10-sigil": "Arbiters of Hexis Truth sigil",
	"26 sigilsflair syndicate-cephalon-simaris-sigil": "Cephalon Simaris sigil",
	"28 sigilsflair syndicate-cephalon-suda-sigil": "Cephalon Suda sigil",
	"29 sigilsflair syndicate-cephalon-suda-level-1-sigil": "Cephalon Suda Query sigil",
	"30 sigilsflair syndicate-cephalon-suda-level-2-sigil": "Cephalon Suda Searching sigil",
	"31 sigilsflair syndicate-cephalon-suda-level-3-sigil": "Cephalon Suda Pattern Match sigil",
	"32 sigilsflair syndicate-cephalon-suda-level-4-sigil": "Cephalon Suda Atomic sigil",
	"33 sigilsflair syndicate-cephalon-suda-level-5-sigil": "Cephalon Suda Manifold sigil",
	"34 sigilsflair syndicate-cephalon-suda-level-6-sigil": "Cephalon Suda Fractal sigil",
	"35 sigilsflair syndicate-cephalon-suda-level-7-sigil": "Cephalon Suda Multivariate sigil",
	"36 sigilsflair syndicate-cephalon-suda-level-8-sigil": "Cephalon Suda Labryinth sigil",
	"37 sigilsflair syndicate-cephalon-suda-level-9-sigil": "Cephalon Suda Hexan sigil",
	"38 sigilsflair syndicate-cephalon-suda-level-10-sigil": "Cephalon Suda Oracle sigil",
	"56 sigilsflair syndicate-new-loka-sigil": "New Loka sigil",
	"57 sigilsflair syndicate-new-loka-level-1-sigil": "New Loka Sacrifice sigil",
	"58 sigilsflair syndicate-new-loka-level-2-sigil": "New Loka Seed sigil",
	"59 sigilsflair syndicate-new-loka-level-3-sigil": "New Loka Rebirth sigil",
	"60 sigilsflair syndicate-new-loka-level-4-sigil": "New Loka Growth sigil",
	"61 sigilsflair syndicate-new-loka-level-5-sigil": "New Loka Clarity sigil",
	"62 sigilsflair syndicate-new-loka-level-6-sigil": "New Loka Bloom sigil",
	"63 sigilsflair syndicate-new-loka-level-7-sigil": "New Loka Purity sigil",
	"64 sigilsflair syndicate-new-loka-level-8-sigil": "New Loka Gaia sigil",
	"65 sigilsflair syndicate-new-loka-level-9-sigil": "New Loka Bounty sigil",
	"66 sigilsflair syndicate-new-loka-level-10-sigil": "New Loka Humanity sigil",
	"67 sigilsflair syndicate-red-veil-sigil": "Red Veil sigil",
	"68 sigilsflair syndicate-red-veil-level-1-sigil": "Red Veil Blades sigil",
	"69 sigilsflair syndicate-red-veil-level-2-sigil": "Red Veil Cull sigil",
	"70 sigilsflair syndicate-red-veil-level-3-sigil": "Red Veil Threat sigil",
	"71 sigilsflair syndicate-red-veil-level-4-sigil": "Red Veil Maelstrom sigil",
	"72 sigilsflair syndicate-red-veil-level-5-sigil": "Red Veil Lesion sigil",
	"73 sigilsflair syndicate-red-veil-level-6-sigil": "Red Veil Ruin sigil",
	"74 sigilsflair syndicate-red-veil-level-7-sigil": "Red Veil Viscera sigil",
	"75 sigilsflair syndicate-red-veil-level-8-sigil": "Red Veil Malevolent sigil",
	"76 sigilsflair syndicate-red-veil-level-9-sigil": "Red Veil Covert sigil",
	"77 sigilsflair syndicate-red-veil-level-10-sigil": "Red Veil Assassin sigil",
	"78 sigilsflair syndicate-steel-meridian-sigil": "Steel Meridian sigil",
	"79 sigilsflair syndicate-steel-meridian-level-1-sigil": "Steel Meridian Defiance sigil",
	"80 sigilsflair syndicate-steel-meridian-level-2-sigil": "Steel Meridian Armada sigil",
	"81 sigilsflair syndicate-steel-meridian-level-3-sigil": "Steel Meridian Vigilance sigil",
	"82 sigilsflair syndicate-steel-meridian-level-4-sigil": "Steel Meridian Uprising sigil",
	"83 sigilsflair syndicate-steel-meridian-level-5-sigil": "Steel Meridian Protectorate sigil",
	"84 sigilsflair syndicate-steel-meridian-level-6-sigil": "Steel Meridian Freedom Fighter sigil",
	"85 sigilsflair syndicate-steel-meridian-level-7-sigil": "Steel Meridian Armored sigil",
	"86 sigilsflair syndicate-steel-meridian-level-8-sigil": "Steel Meridian Rebellion sigil",
	"87 sigilsflair syndicate-steel-meridian-level-9-sigil": "Steel Meridian Unyielding sigil",
	"88 sigilsflair syndicate-steel-meridian-level-10-sigil": "Steel Meridian Champion sigil",
	"89 sigilsflair syndicate-the-perrin-sequence-sigil": "The Perrin Sequence sigil",
	"90 sigilsflair syndicate-the-perrin-sequence-level-1-sigil": "The Perrin Sequence Progress sigil",
	"91 sigilsflair syndicate-the-perrin-sequence-level-2-sigil": "The Perrin Sequence Opportunity sigil",
	"92 sigilsflair syndicate-the-perrin-sequence-level-3-sigil": "The Perrin Sequence Calculating sigil",
	"93 sigilsflair syndicate-the-perrin-sequence-level-4-sigil": "The Perrin Sequence Synergy sigil",
	"94 sigilsflair syndicate-the-perrin-sequence-level-5-sigil": "The Perrin Sequence Directives sigil",
	"95 sigilsflair syndicate-the-perrin-sequence-level-6-sigil": "The Perrin Sequence Strategy sigil",
	"96 sigilsflair syndicate-the-perrin-sequence-level-7-sigil": "The Perrin Sequence Tessilations [sic] sigil",
	"97 sigilsflair syndicate-the-perrin-sequence-level-8-sigil": "The Perrin Sequence Optimum sigil",
	"98 sigilsflair syndicate-the-perrin-sequence-level-9-sigil": "The Perrin Sequence Capital sigil",
	"99 sigilsflair syndicate-the-perrin-sequence-level-10-sigil": "The Perrin Sequence Chairman sigil",
	"100 sigilsflair prime-cycuta-sigil": "Cycuta Prime sigil",
	"101 sigilsflair prime-verlorum-sigil": "Verlorum Prime sigil",
	"102 sigilsflair banshee-soprana-sigil": "Banshee Soprana sigil",
	"103 sigilsflair blade-and-gun-sigil": "Blade and Gun sigil",
	"202 sigilsflair community-of-tenno-sigil-pink": "Community of Tenno sigil (pink)",
	"203 sigilsflair community-of-tenno-sigil": "Community of Tenno sigil",
	"104 sigilsflair cycle-one-sigil": "Cycle One sigil (PS4 exclusive)",
	"105 sigilsflair cycle-two-sigil": "Cycle Two sigil (PS4 exclusive)",
	"106 sigilsflair cycle-three-sigil": "Cycle Three sigil (PS4 exclusive)",
	"107 sigilsflair day-of-the-dead-sigil": "Day of the Dead sigil (Halloween exclusive)",
	"208 sigilsflair dawns-early-light-sigil": "Dawn's Early Light Sigil (The Great Eidolon Hunt Twitch event exclusive)",
	"108 sigilsflair festive-sigil": "Festive sigil (winter exclusive)",
	"109 sigilsflair festive-i-wreath-sigil": "Festive I (Wreath) sigil (winter exclusive)",
	"110 sigilsflair festive-ii-nistlebrush-sigil": "Festive II (Nistlebrush) sigil (winter exclusive)",
	"111 sigilsflair festive-iii-tolling-sigil": "Festive III (Tolling) sigil (winter exclusive)",
	"112 sigilsflair festive-iv-evergreen-sigil": "Festive IV (Evergreen) sigil (winter exclusive)",
	"114 sigilsflair kuria-gold-sigil": "Kuria sigil (gold)",
	"113 sigilsflair kuria-sigil": "Kuria sigil",
	"115 sigilsflair login-imminent-eclipse-sigil": "Imminent Eclipse sigil (login reward)",
	"116 sigilsflair login-awakened-luna-sigil": "Awakened Luna sigil (login reward)",
	"117 sigilsflair login-eternal-stasis-sigil": "Eternal Stasis sigil (login reward)",
	"118 sigilsflair login-solar-flare-sigil": "Solar Flare sigil (login reward)",
	"206 sigilsflair login-void-gate-sigil": "Void Gate sigil (login reward)",
	"207 sigilsflair login-lotus-deliverance-sigil": "Lotus Deliverance sigil (login reward)",
	"209 sigilsflair ostron-community-sigil": "Ostron Community sigil",
	"119 sigilsflair prisma-sigil": "Prisma sigil",
	"120 sigilsflair rhino-palatine-sigil": "Rhino Palatine sigil",
	"121 sigilsflair rift-sigil": "Rift sigil",
	"122 sigilsflair scar-sigil": "Scar sigil",
	"123 sigilsflair seal-of-honoring-sigil": "Seal of Honoring sigil (XB1 1st anniversary exclusive)",
	"124 sigilsflair seal-of-honoring-ii-sigil": "Seal of Honoring II sigil (XB1 2nd anniversary exclusive)",
	"210 sigilsflair seal-of-honoring-iii-sigil": "Seal of Honoring III sigil (XB1 3rd anniversary exclusive)",
	"125 sigilsflair solstice-i-sigil": "Solstice I sigil (winter exclusive)",
	"126 sigilsflair solstice-ii-sigil": "Solstice II sigil (winter exclusive)",
	"127 sigilsflair solstice-iii-sigil": "Solstice III sigil (winter exclusive)",
	"128 sigilsflair solstice-iv-sigil": "Solstice IV sigil (winter exclusive)",
	"129 sigilsflair solstice-v-sigil": "Solstice V sigil (winter exclusive)",
	"204 sigilsflair tennocon-2016-sigil": "TennoCon 2016 sigil",
	"205 sigilsflair tennolive/vip-sigil": "Tennolive/VIP sigil",
	"130 sigilsflair year-monquis-china-sigil": "Monquis sigil (China)",
	"131 sigilsflair year-monquis-world-sigil": "Monquis sigil (International)",
	
	
	/* noggles (0-74) */
	"8 nogglesflair acolyte-angst-noggle": "Acolyte Angst noggle",
	"9 nogglesflair acolyte-malice-noggle": "Acolyte Malice noggle",
	"10 nogglesflair acolyte-mania-noggle": "Acolyte Mania noggle",
	"11 nogglesflair acolyte-misery-noggle": "Acolyte Misery noggle",
	"12 nogglesflair acolyte-torment-noggle": "Acolyte Torment noggle",
	"13 nogglesflair acolyte-violence-noggle": "Acolyte Violence noggle",
	"0 nogglesflair alad-v-noggle": "Alad V noggle",
	"49 nogglesflair ambulas-noggle": "Ambulas noggle",
	"14 nogglesflair arid-seeker-noggle": "Arid Seeker noggle",
	"15 nogglesflair ash-noggle": "Ash noggle",
	"16 nogglesflair banshee-noggle": "Banshee noggle",
	"1 nogglesflair baro-ki-teer-noggle": "Baro Ki'Teer noggle",
	"17 nogglesflair battalyst-noggle": "Battalyst noggle",
	"2 nogglesflair captain-vor-noggle": "Captain Vor noggle",
	"3 nogglesflair clem-noggle": "Clem noggle",
	"18 nogglesflair conculyst-noggle": "Conculyst noggle",
	"19 nogglesflair elite-arid-lancer-noggle": "Elite Arid Lancer noggle",
	"20 nogglesflair ember-noggle": "Ember noggle",
	"25 nogglesflair excalibur-prime-noggle": "Excalibur Prime noggle (PC Founders exclusive)",
	"22 nogglesflair excalibur-noggle": "Excalibur noggle",
	"21 nogglesflair excalibur-jade-noggle": "Jade Excalibur noggle (XB1 exclusive)",
	"23 nogglesflair excalibur-obsidian-noggle": "Obsidian Excalibur noggle (PS4 exclusive)",
	"24 nogglesflair excalibur-obsidian-azura-noggle": "Obsidian Azura Excalibur noggle (PS4 exclusive)",
	"72 nogglesflair excalibur-prisma-skin-noggle": "Excalibur Prisma skin noggle",
	"73 nogglesflair excalibur-proto-skin-noggle": "Excalibur Proto skin noggle",
	"74 nogglesflair inaros-sarcophagus-noggle": "Inaros Sarcophagus noggle",
	"32 nogglesflair index-derim-zahn-noggle": "Index Claims Investigation Broker Derim Zahn noggle",
	"35 nogglesflair index-jen-dro-noggle": "Index Claims Investigation Broker Jen Dro noggle",
	"37 nogglesflair index-m-wam-noggle": "Index Claims Investigation Broker M-WAM noggle",
	"42 nogglesflair index-tia-mayn-noggle": "Index Claims Investigation Broker Tia Mayn noggle",
	"7 nogglesflair index-002-er-noggle": "Index Investor Relations Broker 002-ER noggle",
	"29 nogglesflair index-armis-ulta-noggle": "Index Investor Relations Broker Armis Ulta noggle",
	"33 nogglesflair index-dru-pesfor-noggle": "Index Investor Relations Broker Dru Pesfor noggle",
	"40 nogglesflair index-rana-del-noggle": "Index Investor Relations Broker Rana Del noggle",
	"36 nogglesflair index-lockjaw-and-sol-noggle": "Index Reclamation Unit Broker Lockjaw and Sol noggle",
	"38 nogglesflair index-nako-xol-noggle": "Index Reclamation Unit Broker Nako Xol noggle",
	"39 nogglesflair index-pelna-cade-noggle": "Index Reclamation Unit Broker Pelna Cade noggle",
	"43 nogglesflair index-ved-xol-noggle": "Index Reclamation Unit Broker Ved Xol noggle",
	"30 nogglesflair index-auditor-noggle": "Index Trading Group Broker Auditor noggle",
	"31 nogglesflair index-azoth-noggle": "Index Trading Group Broker Azoth noggle",
	"34 nogglesflair index-jad-teran-noggle": "Index Trading Group Broker Jad Teran noggle",
	"41 nogglesflair index-raptor-rx-noggle": "Index Trading Group Broker Raptor RX noggle",
	"55 nogglesflair rathuum-executioner-dhurnam-noggle": "Rathuum Executioner Dhurnam noggle",
	"56 nogglesflair rathuum-executioner-dok-thul-noggle": "Rathuum Executioner Dok Thul noggle",
	"57 nogglesflair rathuum-executioner-garesh-noggle": "Rathuum Executioner Garesh noggle",
	"58 nogglesflair rathuum-executioner-gorth-noggle": "Rathuum Executioner Gorth noggle",
	"59 nogglesflair rathuum-executioner-harkonar-noggle": "Rathuum Executioner Harkonar noggle",
	"60 nogglesflair rathuum-executioner-nok-noggle": "Rathuum Executioner Nok noggle",
	"61 nogglesflair rathuum-executioner-reth-noggle": "Rathuum Executioner Reth noggle",
	"62 nogglesflair rathuum-executioner-vay-molta-noggle": "Rathuum Executioner Vay Molta noggle",
	"63 nogglesflair rathuum-executioner-zura-noggle": "Rathuum Executioner Zura noggle",
	"26 nogglesflair frost-noggle": "Frost noggle",
	"4 nogglesflair general-sargas-ruk-noggle": "General Sargas Ruk noggle",
	"27 nogglesflair hydroid-noggle": "Hydroid noggle",
	"28 nogglesflair hyekka-noggle": "Hyekka noggle",
	"44 nogglesflair kela-de-thaym-noggle": "Kela De Thaym noggle",
	"45 nogglesflair lancer-noggle": "Lancer noggle",
	"46 nogglesflair loki-noggle": "Loki noggle",
	"5 nogglesflair the-lotus-noggle": "Lotus noggle",
	"47 nogglesflair mag-noggle": "Mag noggle",
	"48 nogglesflair mirage-noggle": "Mirage noggle",
	"50 nogglesflair nekros-noggle": "Nekros noggle",
	"51 nogglesflair nezha-noggle": "Nezha noggle",
	"52 nogglesflair nova-noggle": "Nova noggle",
	"53 nogglesflair nyx-noggle": "Nyx noggle",
	"54 nogglesflair oberon-noggle": "Oberon noggle",
	"64 nogglesflair rhino-noggle": "Rhino noggle",
	"65 nogglesflair saryn-noggle": "Saryn noggle",
	"66 nogglesflair trinity-noggle": "Trinity noggle",
	"67 nogglesflair valkyr-noggle": "Valkyr noggle",
	"68 nogglesflair vauban-noggle": "Vauban noggle",
	"69 nogglesflair volt-noggle": "Volt noggle",
	"70 nogglesflair wukong-noggle": "Wukong noggle",
	"71 nogglesflair zephyr-noggle": "Zephyr noggle",
	"6 nogglesflair stalker-noggle": "??????? noggle",
	
	
	/* Landing Crafts (70-103) */
	"70 landingcraftsflair liset-prime": "Liset Prime",
	"71 landingcraftsflair liset": "Liset",
	"72 landingcraftsflair mantis": "Mantis",
	"73 landingcraftsflair scimitar": "Scimitar",
	"74 landingcraftsflair xiphos": "Xiphos",
	"75 landingcraftsflair liset-day-of-the-dead-skin": "Liset Day of the Dead skin (Halloween exclusive)",
	"76 landingcraftsflair liset-hellkite-skin": "Liset Hellkite skin",
	"77 landingcraftsflair liset-hima-skin": "Liset Hima skin",
	"78 landingcraftsflair liset-jade-skin": "Liset Jade skin (XB1 exclusive)",
	"79 landingcraftsflair liset-kotara-skin": "Liset Kotara skin",
	"80 landingcraftsflair liset-kuva-skin": "Liset Kuva skin",
	"81 landingcraftsflair liset-kuza-skin": "Liset Kuza skin",
	"82 landingcraftsflair liset-maltzer-oculus-skin": "Liset Maltzer Oculus skin",
	"83 landingcraftsflair liset-obsidian-skin": "Liset Obsidian skin",
	"84 landingcraftsflair liset-pahta-skin": "Liset Pahta skin",
	"85 landingcraftsflair liset-prisma-skin": "Liset Prisma skin",
	"86 landingcraftsflair liset-quilate-skin": "Liset Quilate skin",
	"87 landingcraftsflair liset-zikha-skin": "Liset Zikha skin",
	"88 landingcraftsflair mantis-bajada-skin": "Mantis Bajada skin",
	"89 landingcraftsflair mantis-day-of-the-dead-skin": "Mantis Day of the Dead skin (Halloween exclusive)",
	"90 landingcraftsflair mantis-gloam-skin": "Mantis Gloam skin",
	"91 landingcraftsflair mantis-kuva-skin": "Mantis Kuva skin",
	"92 landingcraftsflair mantis-oscuro-skin": "Mantis Oscuro skin",
	"93 landingcraftsflair mantis-prisma-skin": "Mantis Prisma skin",
	"94 landingcraftsflair scimitar-echo-skin": "Scimitar Echo skin",
	"95 landingcraftsflair scimitar-kuva-skin": "Scimitar Kuva skin",
	"96 landingcraftsflair scimitar-magus-skin": "Scimitar Magus skin",
	"97 landingcraftsflair scimitar-nami-skin": "Scimitar Nami skin",
	"98 landingcraftsflair scimitar-prisma-skin": "Scimitar Prisma skin",
	"99 landingcraftsflair scimitar-sotz-skin": "Scimitar Sotz skin",
	"100 landingcraftsflair xiphos-henipa-skin": "Xiphos Henipa skin",
	"101 landingcraftsflair xiphos-ifrit-skin": "Xiphos Ifrit skin",
	"102 landingcraftsflair xiphos-kuva-skin": "Xiphos Kuva skin",
	"103 landingcraftsflair xiphos-prisma-skin": "Xiphos Prisma skin",

	
	/* Miscellaneous Flairs (0-69, 104-118) */
	"0 miscellaneousflair disciple": "Disciple Founder (PC Founders exclusive)",
	"1 miscellaneousflair hunter": "Hunter Founder (PC Founders exclusive)",
	"2 miscellaneousflair master": "Master Founder (PC Founders exclusive)",
	"3 miscellaneousflair grandmaster": "Grand Master Founder (PC Founders exclusive)",
	/*"4 miscellaneousflair revive": "Moderator",*/
	/*"5 miscellaneousflair lotus": "DE Employee",*/
	"16 miscellaneousflair pc": "PC",
	"17 miscellaneousflair ps4": "PS4",
	"18 miscellaneousflair xb1": "XB1",
	"119 miscellaneousflair mask-excalibur": "Excalibur mask",
	"120 miscellaneousflair mask-mag": "Mag mask",
	"121 miscellaneousflair mask-trinity": "Trinity mask",
	"122 miscellaneousflair mask-volt": "Volt mask",
	"123 miscellaneousflair mask-grineer": "Grineer mask",
	"31 miscellaneousflair ayatan-anasa-sculpture": "Ayatan Anasa sculpture",
	"32 miscellaneousflair ayatan-ayr-sculpture": "Ayatan Ayr sculpture",
	"33 miscellaneousflair ayatan-orta-sculpture": "Ayatan Orta sculpture",
	"34 miscellaneousflair ayatan-piv-sculpture": "Ayatan Piv sculpture",
	"35 miscellaneousflair ayatan-sah-sculpture": "Ayatan sah sculpture",
	"36 miscellaneousflair ayatan-vaya-sculpture": "Ayatan Vaya sculpture",
	"37 miscellaneousflair ayatan-valana-sculpture": "Ayatan Valana sculpture",
	"38 miscellaneousflair ayatan-amber-star": "Ayatan amber star",
	"39 miscellaneousflair ayatan-cyan-star": "Ayatan cyan star",
	"45 miscellaneousflair kuria": "Kuria",
	"124 miscellaneousflair prominence-wisp-totem": "Prominence Wisp Totem",
	"46 miscellaneousflair sacred-vessel": "Sacred vessel",
	"51 miscellaneousflair exilus-adapter": "Exilus adapter",
	"27 miscellaneousflair forma": "Forma",
	"54 miscellaneousflair legendary-core": "Legendary core",
	"55 miscellaneousflair module": "Module",
	"29 miscellaneousflair orokin-catalyst": "Orokin catalyst",
	"30 miscellaneousflair orokin-reactor": "Orokin reactor",
	"126 miscellaneousflair brilliant-eidolon-shard": "Brilliant Eidolon shard",
	"125 miscellaneousflair cetus-wisp": "Cetus wisp",
	"48 miscellaneousflair credits": "Credits",
	"49 miscellaneousflair ducats": "Ducats",
	"50 miscellaneousflair endo": "Endo",
	"56 miscellaneousflair platinum": "Platinum",
	"58 miscellaneousflair maxim-medallion": "Maxim medallion",
	"59 miscellaneousflair genius-datum": "Genius datum",
	"60 miscellaneousflair flawless-seed": "Flawless seed",
	"61 miscellaneousflair partner-quittance": "Partner quittance",
	"62 miscellaneousflair exalted-mark": "Exalted mark",
	"63 miscellaneousflair general-insignia": "General insignia",
	"64 miscellaneousflair medallion": "Medallion",
	"65 miscellaneousflair datum": "Datum",
	"66 miscellaneousflair seed": "Seed",
	"67 miscellaneousflair quittance": "Quittance",
	"68 miscellaneousflair mark": "Mark",
	"69 miscellaneousflair insignia": "Insignia",
	"47 miscellaneousflair argon-crystal": "Argon crystal",
	"52 miscellaneousflair kubrow-egg": "Kubrow egg",
	"53 miscellaneousflair kuva": "Kuva",
	"28 miscellaneousflair nitain-extract": "Nitain extract",
	"57 miscellaneousflair void-trace": "Void trace",
	"40 miscellaneousflair ghost-clan-emblem": "Ghost clan emblem",
	"41 miscellaneousflair shadow-clan-emblem": "Shadow clan emblem",
	"42 miscellaneousflair storm-clan-emblem": "Storm clan emblem",
	"43 miscellaneousflair mountain-clan-emblem": "Mountain clan emblem",
	"44 miscellaneousflair moon-clan-emblem": "Moon clan emblem",
	"104 miscellaneousflair moon-icon": "Moon icon",
	"105 miscellaneousflair sun-icon": "Sun icon",
	"106 miscellaneousflair impact-damage-icon": "Impact damage icon",
	"107 miscellaneousflair puncture-damage-icon": "Puncture damage icon",
	"108 miscellaneousflair slash-damage-icon": "Slash damage icon",
	"109 miscellaneousflair cold-damage-icon": "Cold damage icon",
	"110 miscellaneousflair electricity-damage-icon": "Electricity damage icon",
	"111 miscellaneousflair heat-damage-icon": "Heat damage icon",
	"112 miscellaneousflair toxin-damage-icon": "Toxin damage icon",
	"113 miscellaneousflair blast-damage-icon": "Blast damage icon",
	"114 miscellaneousflair corrosive-damage-icon": "Corrosive damage icon",
	"115 miscellaneousflair gas-damage-icon": "Gas damage icon",
	"116 miscellaneousflair magnetic-damage-icon": "Magnetic damage icon",
	"117 miscellaneousflair radiation-damage-icon": "Radiation damage icon",
	"118 miscellaneousflair viral-damage-icon": "Viral damage icon"
};
