/* FLAIR MASTER CONFIG | auto-generated at 2016-12-21T02:13:37-0800 (ISO-8601) */ 
flair.load__by_id = function() {
    for (var key in flair.names) {
        if (flair.names.hasOwnProperty(key)) {
            var data = key.split(' ');
            
            var orig_id = data[2];
            
            if (orig_id.substring(0, 'a'.length) === 'a') {
                orig_id = orig_id.substring(1);
            }
            if (orig_id.substring(orig_id.length - 'm'.length) === 'm') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 'o'.length) === 'o') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 'x'.length) === 'x') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 'y'.length) === 'y') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 1).match(/[a-z]/i) &&
                orig_id.substring(0, orig_id.length - 1).match(/^\d+$/)) {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            
            flair.by_id[data[2]] = {
                key: key,
                spritepos: data[0],
                sheet: data[1],
                flair_id: data[2],
                orig_id: orig_id,
                flair_name: flair.names[key],
                flair_class: ' flair-'+data[0] + ' flair-'+data[1] + ' flair-'+data[2]
            }
        }
    }
}
flair.by_id = {}
flair.names = {
/* [STANDARD] */

    /* Remove Flair*/
    "0 removeflair none": "Remove Flair",
    
    /* Prime Warframes (0-14) */
    "0 primewarframesflair ash-prime": "Ash Prime",
    "1 primewarframesflair ember-prime": "Ember Prime",
    "2 primewarframesflair excalibur-prime": "Excalibur Prime (PC Founders exclusive)",
    "3 primewarframesflair frost-prime": "Frost Prime",
    "4 primewarframesflair loki-prime": "Loki Prime",
    "5 primewarframesflair mag-prime": "Mag Prime",
    "6 primewarframesflair nekros-prime": "Nekros Prime",
    "7 primewarframesflair nova-prime": "Nova Prime",
    "8 primewarframesflair nyx-prime": "Nyx Prime",
    "9 primewarframesflair rhino-prime": "Rhino Prime",
    "10 primewarframesflair saryn-prime": "Saryn Prime",
    "11 primewarframesflair trinity-prime": "Trinity Prime",
    "12 primewarframesflair vauban-prime": "Vauban Prime",
    "13 primewarframesflair volt-prime": "Volt Prime",
    "14 primewarframesflair valkyr-prime": "Valkyr Prime",
    
    
    /* Regular Warframes (0-30) */
    "0 regularwarframesflair ash": "Ash",
    "1 regularwarframesflair atlas": "Atlas",
    "2 regularwarframesflair banshee": "Banshee",
    "3 regularwarframesflair chroma": "Chroma",
    "4 regularwarframesflair ember": "Ember",
    "5 regularwarframesflair equinox": "Equinox",
    "6 regularwarframesflair excalibur": "Excalibur",
    "7 regularwarframesflair frost": "Frost",
    "8 regularwarframesflair hydroid": "Hydroid",
    "9 regularwarframesflair inaros": "Inaros",
    "10 regularwarframesflair ivara": "Ivara",
    "11 regularwarframesflair limbo": "Limbo",
    "12 regularwarframesflair loki": "Loki",
    "13 regularwarframesflair mag": "Mag",
    "14 regularwarframesflair mesa": "Mesa",
    "15 regularwarframesflair mirage": "Mirage",
    "16 regularwarframesflair nekros": "Nekros",
    "17 regularwarframesflair nezha": "Nezha",
    "18 regularwarframesflair nidus": "Nidus",
    "19 regularwarframesflair nova": "Nova",
    "20 regularwarframesflair nyx": "Nyx",
    "21 regularwarframesflair oberon": "Oberon",
    "22 regularwarframesflair rhino": "Rhino",
    "23 regularwarframesflair saryn": "Saryn",
    "24 regularwarframesflair titania": "Titania",
    "25 regularwarframesflair trinity": "Trinity",
    "26 regularwarframesflair valkyr": "Valkyr",
    "27 regularwarframesflair vauban": "Vauban",
    "28 regularwarframesflair volt": "Volt",
    "29 regularwarframesflair wukong": "Wukong",
    "30 regularwarframesflair zephyr": "Zephyr",
    
    
    /* Deluxe Warframe Skins (0-10)*/
    "0 deluxewarframeskinsflair ash-koga-skin": "Ash (Koga)",
    "1 deluxewarframeskinsflair banshee-soprana-skin": "Banshee (Soprana)",
    "2 deluxewarframeskinsflair excalibur-proto-skin": "Excalibur (Proto)",
    "3 deluxewarframeskinsflair loki-knave-skin": "Loki (Knave)",
    "4 deluxewarframeskinsflair nova-asuri-skin": "Nova (Asuri)",
    "5 deluxewarframeskinsflair nyx-nemesis-skin": "Nyx (Nemesis)",
    "6 deluxewarframeskinsflair oberon-feyarch-skin": "Oberon (Feyarch)",
    "7 deluxewarframeskinsflair rhino-palatine-skin": "Rhino (Palatine)",
    "8 deluxewarframeskinsflair saryn-orphid-skin": "Saryn (Orphid)",
    "9 deluxewarframeskinsflair trinity-strega-skin": "Trinity (Strega)",
    "10 deluxewarframeskinsflair valkyr-gersemi-skin": "Valkyr (Gersemi)",
    
    
    /* TennoGen Warframe Skins (0-32)*/
    "0 tennogenwarframeskinsflair chroma-drevni-skin": "Chroma (Drevni by Volkovyi - Steam exclusive)",
    "1 tennogenwarframeskinsflair chroma-vojnik-skin": "Chroma (Vojnik Battle-Damaged by Volkovyi - Steam exclusive)",
    "2 tennogenwarframeskinsflair ember-graxx-skin": "Ember (Graxx by Faven_PS - Steam exclusive)",
    "3 tennogenwarframeskinsflair excalibur-apex-skin": "Excalibur (Apex by antoineflemming - Steam exclusive)",
    "4 tennogenwarframeskinsflair excalibur-caduto-skin": "Excalibur (Caduto by Hitsu San - Steam exclusive)",
    "5 tennogenwarframeskinsflair excalibur-graxx-skin": "Excalibur (Graxx by Faven_PS - Steam exclusive)",
    "6 tennogenwarframeskinsflair excalibur-sentient slayer-skin": "Excalibur (Sentient Slayer by CommanderApocalypse - Steam exclusive)",
    "7 tennogenwarframeskinsflair excalibur-vespula gold-skin": "Excalibur (Vespula Gold by polygonmonster - Steam exclusive)",
    "8 tennogenwarframeskinsflair frost-emperor-skin": "Frost (Emperor by Hitsu San - Steam exclusive)",
    "9 tennogenwarframeskinsflair frost-grost-skin": "Frost (Grost by Faven_PS - Steam exclusive)",
    "10 tennogenwarframeskinsflair frost-hailstorm-skin": "Frost (Hailstorm by Arsenal - Steam exclusive)",
    "11 tennogenwarframeskinsflair frost-vojnik-skin": "Frost (Vojnik Battle-Damaged by Volkovyi - Steam exclusive)",
    "12 tennogenwarframeskinsflair mag-alata-skin": "Mag (Alata by Hitsu San - Steam exclusive)",
    "13 tennogenwarframeskinsflair mag-knaita-skin": "Mag (Knaita by prosetisen - Steam exclusive)",
    "14 tennogenwarframeskinsflair mag-orbit-skin": "Mag (Orbit by Del - Steam exclusive)",
    "15 tennogenwarframeskinsflair mirage-graxx-skin": "Mirage (Graxx by Faven_PS - Steam exclusive)",
    "16 tennogenwarframeskinsflair mirage-sigyn-skin": "Mirage (Sigyn by Novabjorn - Steam exclusive)",
    "17 tennogenwarframeskinsflair nova-cygni-skin": "Nova (Cygni by Arsenal - Steam exclusive)",
    "18 tennogenwarframeskinsflair nova-device-skin": "Nova (Device by posetisen - Steam exclusive)",
    "19 tennogenwarframeskinsflair nova-gnova-skin": "Nova (Gnova by Faven_PS - Steam exclusive)",
    "20 tennogenwarframeskinsflair nova-lamia-skin": "Nova (Lamia by Mz-3 - Steam exclusive)",
    "21 tennogenwarframeskinsflair nova-stinger-skin": "Nova (Stinger by Cheshire - Steam exclusive)",
    "22 tennogenwarframeskinsflair nova-visage-skin": "Nova (Visage by Hitsu San - Steam exclusive)",
    "23 tennogenwarframeskinsflair nyx-athena-skin": "Nyx (Athena by prosetisen - Steam exclusive)",
    "24 tennogenwarframeskinsflair nyx-graxx-skin": "Nyx (Graxx by Faven_PS - Steam exclusive)",
    "25 tennogenwarframeskinsflair rhino-graxx-skin": "Rhino (Graxx by Faven_PS - Steam exclusive)",
    "26 tennogenwarframeskinsflair rhino-vojnik-skin": "Rhino (Vojnik Battle-Damaged by Volkovyi - Steam exclusive)",
    "27 tennogenwarframeskinsflair saryn-graxx-skin": "Saryn (Graxx by Faven_PS - Steam exclusive)",
    "28 tennogenwarframeskinsflair valkyr-graxx-skin": "Valkyr (Graxx by Faven_PS - Steam exclusive)",
    "29 tennogenwarframeskinsflair volt-amp-skin": "Volt (Amp by Faven_PS - Steam exclusive)",
    "30 tennogenwarframeskinsflair volt-graxx-skin": "Volt (Graxx by Faven_PS - Steam exclusive)",
    "31 tennogenwarframeskinsflair zephyr-hagoromo-skin": "Zephyr (Hagoromo by Hitsu San - Steam exclusive)",
    "32 tennogenwarframeskinsflair zephyr-skeiron-skin": "Zephyr (Skeiron by novadragon01 - Steam exclusive)",

    
    
    /* Immortal Warframe Skins (0-16) */
    "0 immortalwarframeskinsflair ash-immortal-skin": "Ash (Immortal)",
    "1 immortalwarframeskinsflair banshee-immortal-skin": "Banshee (Immortal)",
    "2 immortalwarframeskinsflair ember-immortal-skin": "Ember (Immortal)",
    "3 immortalwarframeskinsflair excalibur-immortal-skin": "Excalibur (Immortal)",
    "4 immortalwarframeskinsflair frost-immortal-skin": "Frost (Immortal)",
    "5 immortalwarframeskinsflair loki-immortal-skin": "Loki (Immortal)",
    "6 immortalwarframeskinsflair mag-immortal-skin": "Mag (Immortal)",
    "7 immortalwarframeskinsflair nekros-immortal-skin": "Nekros (Immortal)",
    "8 immortalwarframeskinsflair nova-immortal-skin": "Nova (Immortal)",
    "9 immortalwarframeskinsflair nyx-immortal-skin": "Nyx (Immortal)",
    "10 immortalwarframeskinsflair oberon-immortal-skin": "Oberon (Immortal)",
    "11 immortalwarframeskinsflair rhino-immortal-skin": "Rhino (Immortal)",
    "12 immortalwarframeskinsflair saryn-immortal-skin": "Saryn (Immortal)",
    "13 immortalwarframeskinsflair trinity-immortal-skin": "Trinity (Immortal)",
    "14 immortalwarframeskinsflair valkyr-immortal-skin": "Valkyr (Immortal)",
    "15 immortalwarframeskinsflair vauban-immortal-skin": "Vauban (Immortal)",
    "16 immortalwarframeskinsflair volt-immortal-skin": "Volt (Immortal)",
    
    /* Other Warframe Skins (0-6) */
    "0 otherwarframeskinsflair excalibur-jade-skin": "Excalibur (Jade - XB1 exclusive)",
    "1 otherwarframeskinsflair excalibur-obsidian-skin": "Excalibur (Obsidian - PS4 exclusive)",
    "2 otherwarframeskinsflair excalibur-obsidian-azura-skin": "Excalibur (Obsidian Azura - PS4 exclusive)",
    "3 otherwarframeskinsflair excalibur-proto-skin": "Excalibur (Proto)",
    "4 otherwarframeskinsflair rhino-rubedo-skin": "Rhino (Rubedo - Steam exclusive)",
    "5 otherwarframeskinsflair titania-solstice-skin": "Titania (Solstice)",
    "6 otherwarframeskinsflair vauban-phased-skin": "Vauban (Phased - Steam exclusive)",
        
        
    /* Deluxe Warframe Helmets (50-60)*/
    "50 deluxewarframeskinsflair ash-koga-helmet": "Ash (Koga)",
    "51 deluxewarframeskinsflair banshee-soprana-helmet": "Banshee (Soprana)",
    "52 deluxewarframeskinsflair excalibur-proto-helmet": "Excalibur (Proto)",
    "53 deluxewarframeskinsflair loki-knave-helmet": "Loki (Knave)",
    "54 deluxewarframeskinsflair nova-asuri-helmet": "Nova (Asuri)",
    "55 deluxewarframeskinsflair nyx-nemesis-helmet": "Nyx (Nemesis)",
    "56 deluxewarframeskinsflair oberon-feyarch-helmet": "Oberon (Feyarch)",
    "57 deluxewarframeskinsflair rhino-palatine-helmet": "Rhino (Palatine)",
    "58 deluxewarframeskinsflair saryn-orphid-helmet": "Saryn (Orphid)",
    "59 deluxewarframeskinsflair trinity-strega-helmet": "Trinity (Strega)",
    "60 deluxewarframeskinsflair valkyr-gersemi-helmet": "Valkyr (Gersemi)",
    
    
    /* TennoGen Warframe Helmets (0-66)*/
    "0 tennogenwarframehelmetsflair ash-carabid-helmet": "Ash (Carabid by artarrwen - Steam exclusive)",
    "1 tennogenwarframehelmetsflair atlas-arhat-helmet": "Atlas (Arhat by Rekkou - Steam exclusive)",
    "2 tennogenwarframehelmetsflair atlas-telamon-helmet": "Atlas (Telamon by artarrwen - Steam exclusive)",
    "3 tennogenwarframehelmetsflair banshee-echo-helmet": "Banshee (Echo by Rekkou - Steam exclusive)",
    "4 tennogenwarframehelmetsflair chroma-drevni-helmet": "Chroma (Drevni by Volkovyi - Steam exclusive)",
    "5 tennogenwarframehelmetsflair chroma-kaiju-helmet": "Chroma (Kaiju by [k a z] - Steam exclusive)",
    "6 tennogenwarframehelmetsflair chroma-tarrasque-helmet": "Chroma (Tarrasque by artarrwen - Steam exclusive)",
    "7 tennogenwarframehelmetsflair chroma-vojnik-helmet": "Chroma (Vojnik Battle-Damaged by Volkovyi - Steam exclusive)",
    "8 tennogenwarframehelmetsflair ember-graxx-helmet": "Ember (Graxx by Faven_PS - Steam exclusive)",
    "9 tennogenwarframehelmetsflair excalibur-apex-helmet": "Excalibur (Apex by antoineflemming - Steam exclusive)",
    "10 tennogenwarframehelmetsflair excalibur-arturius-helmet": "Excalibur (Arturius by [k a z] - Steam exclusive)",
    "11 tennogenwarframehelmetsflair excalibur-caduto-helmet": "Excalibur (Caduto by Hitsu San - Steam exclusive)",
    "12 tennogenwarframehelmetsflair excalibur-graxx-helmet": "Excalibur (Graxx by Faven_PS - Steam exclusive)",
    "13 tennogenwarframehelmetsflair excalibur-graxx-alt-helmet": "Excalibur (Graxx Alt by Faven_PS - Steam exclusive)",
    "14 tennogenwarframehelmetsflair excalibur-isurus-helmet": "Excalibur (Isurus by Coridium - Steam exclusive)",
    "15 tennogenwarframehelmetsflair excalibur-ogrant-helmet": "Excalibur (Ogrant by lokimonkeye - Steam exclusive)",
    "16 tennogenwarframehelmetsflair excalibur-sentient-slayer-helmet": "Excalibur (Sentient Slayer by CommanderApocalypse - Steam exclusive)",
    "17 tennogenwarframehelmetsflair excalibur-vespula-gold-helmet": "Excalibur (Vespula Gold by polygonmonster - Steam exclusive)",
    "18 tennogenwarframehelmetsflair frost-emperor-helmet": "Frost (Emperor by Hitsu San - Steam exclusive)",
    "19 tennogenwarframehelmetsflair frost-grost-helmet": "Frost (Grost by Faven_PS - Steam exclusive)",
    "20 tennogenwarframehelmetsflair frost-hailstorm-helmet": "Frost (Hailstorm by Arsenal - Steam exclusive)",
    "21 tennogenwarframehelmetsflair frost-jotun-helmet": "Frost (Jotun by malayu - Steam exclusive)",
    "22 tennogenwarframehelmetsflair frost-summit-helmet": "Frost (Summit by artarrwen - Steam exclusive)",
    "23 tennogenwarframehelmetsflair frost-vojnik-helmet": "Frost (Vojnik Battle-Damaged by Volkovyi - Steam exclusive)",
    "24 tennogenwarframehelmetsflair frost-zastruga-helmet": "Frost (Zastruga by Rekkou - Steam exclusive)",
    "25 tennogenwarframehelmetsflair loki-ersatz-helmet": "Loki (Ersatz by Rekkou - Steam exclusive)",
    "26 tennogenwarframehelmetsflair loki-rogue-helmet": "Loki (Rogue by artarrwen - Steam exclusive)",
    "27 tennogenwarframehelmetsflair mag-alata-helmet": "Mag (Alata by Hitsu San - Steam exclusive)",
    "28 tennogenwarframehelmetsflair mag-anthro-helmet": "Mag (Anthro by Pior - Steam exclusive)",
    "29 tennogenwarframehelmetsflair mag-induction-helmet": "Mag (Induction by Pior - Steam exclusive)",
    "30 tennogenwarframehelmetsflair mag-knaita-helmet": "Mag (Knaita by prosetisen - Steam exclusive)",
    "31 tennogenwarframehelmetsflair mag-orbit-helmet": "Mag (Orbit by Del - Steam exclusive)",
    "32 tennogenwarframehelmetsflair mag-toroidal-helmet": "Mag (Toroidal by prosetisen - Steam exclusive)",
    "33 tennogenwarframehelmetsflair mesa-deadeye-helmet": "Mesa (Deadeye by NotYou - Steam exclusive)",
    "34 tennogenwarframehelmetsflair mesa-falcon-helmet": "Mesa (Falcon by prosetisen - Steam exclusive)",
    "35 tennogenwarframehelmetsflair mirage-graxx-helmet": "Mirage (Graxx by Faven_PS - Steam exclusive)",
    "36 tennogenwarframehelmetsflair mirage-jolli-helmet": "Mirage (Jolli by Cheshire - Steam exclusive)",
    "37 tennogenwarframehelmetsflair mirage-sigyn-helmet": "Mirage (Sigyn by Novabjorn - Steam exclusive)",
    "38 tennogenwarframehelmetsflair nekros-lazarus-helmet": "Nekros (Lazarus by [k a z] - Steam exclusive)",
    "39 tennogenwarframehelmetsflair nova-cygni-helmet": "Nova (Cygni by Arsenal - Steam exclusive)",
    "40 tennogenwarframehelmetsflair nova-device-helmet": "Nova (Device by posetisen - Steam exclusive)",
    "41 tennogenwarframehelmetsflair nova-fusion-helmet": "Nova (Fusion by Coridium - Steam exclusive)",
    "42 tennogenwarframehelmetsflair nova-gnova-helmet": "Nova (Gnova by Faven_PS - Steam exclusive)",
    "43 tennogenwarframehelmetsflair nova-lamia-helmet": "Nova (Lamia by Mz-3 - Steam exclusive)",
    "44 tennogenwarframehelmetsflair nova-stinger-helmet": "Nova (Stinger by Cheshire - Steam exclusive)",
    "45 tennogenwarframehelmetsflair nova-tachyon-helmet": "Nova (Tachyon by Rekkou - Steam exclusive)",
    "46 tennogenwarframehelmetsflair nova-visage-helmet": "Nova (Visage by Hitsu San - Steam exclusive)",
    "47 tennogenwarframehelmetsflair nyx-athena-helmet": "Nyx (Athena by prosetisen - Steam exclusive)",
    "48 tennogenwarframehelmetsflair nyx-graxx-helmet": "Nyx (Graxx by Faven_PS - Steam exclusive)",
    "49 tennogenwarframehelmetsflair oberon-destrier-helmet": "Oberon (Destrier by Rekkou - Steam exclusive)",
    "50 tennogenwarframehelmetsflair rhino-graxx-helmet": "Rhino (Graxx by Faven_PS - Steam exclusive)",
    "51 tennogenwarframehelmetsflair rhino-vojnik-helmet": "Rhino (Vojnik Battle-Damaged by Volkovyi - Steam exclusive)",
    "52 tennogenwarframehelmetsflair saryn-graxx-helmet": "Saryn (Graxx by Faven_PS - Steam exclusive)",
    "53 tennogenwarframehelmetsflair trinity-messiah-helmet": "Trinity (Messiah by Cheshire - Steam exclusive)",
    "54 tennogenwarframehelmetsflair valkyr-cheetah-helmet": "Valkyr (Cheetah by Cheshire - Steam exclusive)",
    "55 tennogenwarframehelmetsflair valkyr-graxx-helmet": "Valkyr (Graxx by Faven_PS - Steam exclusive)",
    "56 tennogenwarframehelmetsflair vauban-chapelon-helmet": "Vauban (Chapelon by Rekkou - Steam exclusive)",
    "57 tennogenwarframehelmetsflair volt-amp-helmet": "Volt (Amp by Faven_PS - Steam exclusive)",
    "58 tennogenwarframehelmetsflair volt-arrester-helmet": "Volt (Arrester by Rekkou - Steam exclusive)",
    "59 tennogenwarframehelmetsflair volt-graxx-helmet": "Volt (Graxx by Faven_PS - Steam exclusive)",
    "60 tennogenwarframehelmetsflair volt-relay-helmet": "Volt (Relay by DespicableCheese - Steam exclusive)",
    "61 tennogenwarframehelmetsflair volt-thales-helmet": "Volt (Thales by Arsenal - Steam exclusive)",
    "62 tennogenwarframehelmetsflair wukong-xingzhe-helmet": "Wukong (Xingzhe by Rekkou - Steam exclusive)",
    "63 tennogenwarframehelmetsflair zephyr-hagoromo-helmet": "Zephyr (Hagoromo by Hitsu San - Steam exclusive)",
    "64 tennogenwarframehelmetsflair zephyr-migisi-helmet": "Zephyr (Migisi by FrellingHazmot - Steam exclusive)",
    "65 tennogenwarframehelmetsflair zephyr-monsoon-helmet": "Zephyr (Monsoon by artarrwen - Steam exclusive)",
    "66 tennogenwarframehelmetsflair zephyr-skeiron-helmet": "Zephyr (Skeiron by novadragon01 - Steam exclusive)",

        
    /* Other Warframe Helmets (0-66) */
    "0 otherwarframehelmetsflair ash-locust-helmet": "Ash (Locust)",
    "1 otherwarframehelmetsflair ash-scorpion-helmet": "Ash (Scorpion)",
    "2 otherwarframehelmetsflair atlas-shikoro-helmet": "Atlas (Shikoro)",
    "3 otherwarframehelmetsflair atlas-tartarus-helmet": "Atlas (Tartarus)",
    "4 otherwarframehelmetsflair banshee-chorus-helmet": "Banshee (Chorus)",
    "5 otherwarframehelmetsflair banshee-reverb-helmet": "Banshee (Reverb)",
    "6 otherwarframehelmetsflair chroma-amaru-helmet": "Chroma (Amaru)",
    "7 otherwarframehelmetsflair chroma-drac-helmet": "Chroma (Drac)",
    "8 otherwarframehelmetsflair ember-backdraft-helmet": "Ember (Backdraft)",
    "9 otherwarframehelmetsflair ember-phoenix-helmet": "Ember (Phoenix)",
    "10 otherwarframehelmetsflair equinox-solstice-helmet": "Equinox (Solstice)",
    "11 otherwarframehelmetsflair excalibur-avalon-helmet": "Excalibur (Avalon)",
    "13 otherwarframehelmetsflair excalibur-jade-helmet": "Excalibur (Jade - XB1 exclusive)",
    "14 otherwarframehelmetsflair excalibur-mordred-helmet": "Excalibur (Mordred)",
    "15 otherwarframehelmetsflair excalibur-obsidian-helmet": "Excalibur (Obsidian)",
    "16 otherwarframehelmetsflair excalibur-obsidian-azura-helmet": "Excalibur (Obsidian Azura)",
    "17 otherwarframehelmetsflair excalibur-pendragon-helmet": "Excalibur (Pendragon)",
    "18 otherwarframehelmetsflair excalibur-prisma-helmet": "Excalibur (Prisma)",
    "19 otherwarframehelmetsflair excalibur-prisma-avalon-helmet": "Excalibur (Prisma Avalon)",
    "20 otherwarframehelmetsflair excalibur-prisma-pendragon-helmet": "Excalibur (Prisma Pendragon)",
    "21 otherwarframehelmetsflair frost-aurora-helmet": "Frost (Aurora)",
    "22 otherwarframehelmetsflair frost-squall-helmet": "Frost (Squall)",
    "23 otherwarframehelmetsflair hydroid-ketos-helmet": "Hydroid (Ketos)",
    "24 otherwarframehelmetsflair hydroid-triton-helmet": "Hydroid (Triton)",
    "25 otherwarframehelmetsflair inaros-anubis-helmet": "Inaros (Anubis)",
    "26 otherwarframehelmetsflair ivara-loxley-helmet": "Ivara (Loxley)",
    "27 otherwarframehelmetsflair limbo-aristeas-helmet": "Limbo (Aristeas)",
    "28 otherwarframehelmetsflair limbo-magrite-helmet": "Limbo (Magrite)",
    "29 otherwarframehelmetsflair loki-enigma-helmet": "Loki (Enigma)",
    "30 otherwarframehelmetsflair loki-essence-helmet": "Loki (Essence)",
    "31 otherwarframehelmetsflair loki-swindle-helmet": "Loki (Swindle)",
    "32 otherwarframehelmetsflair mag-coil-helmet": "Mag (Coil)",
    "33 otherwarframehelmetsflair mag-gauss-helmet": "Mag (Gauss)",
    "34 otherwarframehelmetsflair mesa-longhorn-helmet": "Mesa (Longhorn)",
    "35 otherwarframehelmetsflair mesa-ovis-helmet": "Mesa (Ovis)",
    "36 otherwarframehelmetsflair mirage-harlequin-helmet": "Mirage (Harlequin)",
    "37 otherwarframehelmetsflair mirage-trivelin-helmet": "Mirage (Trivelin)",
    "38 otherwarframehelmetsflair nekros-raknis-helmet": "Nekros (Raknis)",
    "39 otherwarframehelmetsflair nekros-shroud-helmet": "Nekros (Shroud)",
    "40 otherwarframehelmetsflair nezha-circa-helmet": "Nezha (Circa)",
    "41 otherwarframehelmetsflair nidus-prion-helmet": "Nidus (Prion)",
    "42 otherwarframehelmetsflair nova-flux-helmet": "Nova (Flux)",
    "43 otherwarframehelmetsflair nova-quantum-helmet": "Nova (Quantum)",
    "44 otherwarframehelmetsflair nova-slipstream-helmet": "Nova (Slipstream)",
    "45 otherwarframehelmetsflair nyx-menticide-helmet": "Nyx (Menticide)",
    "46 otherwarframehelmetsflair nyx-vespa-helmet": "Nyx (Vespa)",
    "47 otherwarframehelmetsflair oberon-markhor-helmet": "Oberon (Markhor)",
    "48 otherwarframehelmetsflair oberon-oryx-helmet": "Oberon (Oryx)",
    "49 otherwarframehelmetsflair rhino-rubedo-helmet": "Rhino (Rubedo - Steam exclusive)",
    "50 otherwarframehelmetsflair rhino-thrak-helmet": "Rhino (Thrak)",
    "51 otherwarframehelmetsflair rhino-vanguard-helmet": "Rhino (Vanguard)",
    "52 otherwarframehelmetsflair saryn-chlora-helmet": "Saryn (Chlora)",
    "53 otherwarframehelmetsflair saryn-hemlock-helmet": "Saryn (Hemlock)",
    "54 otherwarframehelmetsflair titania-aurai-helmet": "Titania (Aurai)",
    "55 otherwarframehelmetsflair trinity-aura-helmet": "Trinity (Aura)",
    "56 otherwarframehelmetsflair trinity-meridian-helmet": "Trinity (Meridian)",
    "57 otherwarframehelmetsflair valkyr-bastet-helmet": "Valkyr (Bastet)",
    "58 otherwarframehelmetsflair valkyr-kara-helmet": "Valkyr (Kara)",
    "59 otherwarframehelmetsflair vauban-armistice-helmet": "Vauban (Armistice)",
    "60 otherwarframehelmetsflair vauban-esprit-helmet": "Vauban (Esprit)",
    "61 otherwarframehelmetsflair vauban-gambit-helmet": "Vauban (Gambit)",
    "62 otherwarframehelmetsflair volt-pulse-helmet": "Volt (Pulse)",
    "63 otherwarframehelmetsflair volt-storm-helmet": "Volt (Storm)",
    "64 otherwarframehelmetsflair wukong-dasheng-helmet": "Wukong (Dasheng)",
    "65 otherwarframehelmetsflair zephyr-cierzo-helmet": "Zephyr (Cierzo)",
    "66 otherwarframehelmetsflair zephyr-tengu-helmet": "Zephyr (Tengu)",
        
        
    /* Glyphs (0-51) */
    "0 glyphsflair ash-in-action-glyph": "Ash in Action Glyph",
    "1 glyphsflair blood-lotus-glyph": "Blood Lotus Glyph",
    "2 glyphsflair butterfly-varna-glyph": "Butterfly Varna Glyph",
    "3 glyphsflair ceph-pinacoid-glyph": "Ceph Pinacoid Glyph",
    "4 glyphsflair clem-in-action-glyph": "Clem in Action Glyph",
    "5 glyphsflair ember-in-action-glyph": "Ember in Action Glyph",
    "6 glyphsflair excalibur-in-action-glyph": "Excalibur in Action Glyph",
    "7 glyphsflair excalibur-noggle-glyph": "Excalibur Noggle Glyph",
    "8 glyphsflair ginger-kubrow-varna-glyph": "Ginger Kubrow Varna Glyph",
    "9 glyphsflair grey-kubrow-varna-glyph": "Grey Kubrow Varna Glyph",
    "10 glyphsflair grineer-queens-glyph": "Grineer Queens Glyph",
    "11 glyphsflair hydroid-submerged-glyph": "Hydroid Submerged Glyph",
    "12 glyphsflair isochronon-glyph": "Isochronon Glyph",
    "13 glyphsflair kavat-enamel-glyph": "Kavat Enamel Glyph",
    "14 glyphsflair kubrow-enamel-glyph": "Kubrow Enamel Glyph",
    "15 glyphsflair kuria-glyph": "Kuria Glyph",
    "16 glyphsflair kuria-idolized-glyph": "Kuria Idolized Glyph",
    "17 glyphsflair loki-in-action-glyph": "Loki in Action Glyph",
    "18 glyphsflair loki-noggle-glyph": "Loki Noggle Glyph",
    "19 glyphsflair lotus-balance-glyph": "Lotus Balance Glyph",
    "20 glyphsflair lotus-noggle-glyph": "Lotus Noggle Glyph",
    "21 glyphsflair lunaro-glyph": "Lunaro Glyph",
    "22 glyphsflair mag-in-action-glyph": "Mag in Action Glyph",
    "23 glyphsflair mag-noggle-glyph": "Mag Noggle Glyph",
    "24 glyphsflair mesa-fixated-glyph": "Mesa Fixated Glyph",
    "25 glyphsflair moon-crest-glyph": "Moon Crest Glyph",
    "26 glyphsflair mythic-balance-glyph": "Mythic Balance Glyph",
    "27 glyphsflair nekros-day-of-the-dead-glyph": "Nekros Day Of The Dead Glyph",
    "28 glyphsflair orbital-cathode-glyph": "Orbital Cathode Glyph",
    "29 glyphsflair rhino-in-action-glyph": "Rhino in Action Glyph",
    "30 glyphsflair rhino-noggle-glyph": "Rhino Noggle Glyph",
    "31 glyphsflair scarab-varna-glyph": "Scarab Varna Glyph",
    "32 glyphsflair solstice-i-glyph": "Solstice Glyph I",
    "33 glyphsflair solstice-ii-glyph": "Solstice Glyph II",
    "34 glyphsflair solstice-iii-glyph": "Solstice Glyph III",
    "35 glyphsflair solstice-iv-glyph": "Solstice Glyph IV",
    "36 glyphsflair solunar-glyph": "Solunar Glyph",
    "37 glyphsflair sooty-kubrow-varna-glyph": "Sooty Kubrow Varna Glyph",
    "38 glyphsflair sun-crest-glyph": "Sun Crest Glyph",
    "39 glyphsflair tenno-refractal-glyph": "Tenno Refractal Glyph",
    "40 glyphsflair teshin-glyph": "Teshin Glyph",
    "41 glyphsflair threshcone-varna-glyph": "Threshcone Varna Glyph",
    "42 glyphsflair trinity-in-action-glyph": "Trinity in Action Glyph",
    "43 glyphsflair volt-in-action-glyph": "Volt in Action Glyph",
    "44 glyphsflair vor-varna-glyph": "Vor Varna Glyph",
    "45 glyphsflair winter-i-glyph": "Winter Glyph I",
    "46 glyphsflair winter-ii-glyph": "Winter Glyph II",
    "47 glyphsflair winter-iii-glyph": "Winter Glyph III",
    "48 glyphsflair winter-iv-glyph": "Winter Glyph IV",
    "49 glyphsflair winter-v-glyph": "Winter Glyph V",
    "50 glyphsflair winter-vi-glyph": "Winter Glyph VI",
    "51 glyphsflair winter-vii-glyph": "Winter Glyph VII",
    
    
    /* Noggles (0-71) */
    "8 nogglesflair acolyte-angst-noggle": "Acolyte Angst Noggle",
    "9 nogglesflair acolyte-malice-noggle": "Acolyte Malice Noggle",
    "10 nogglesflair acolyte-mania-noggle": "Acolyte Mania Noggle",
    "11 nogglesflair acolyte-misery-noggle": "Acolyte Misery Noggle",
    "12 nogglesflair acolyte-torment-noggle": "Acolyte Torment Noggle",
    "13 nogglesflair acolyte-violence-noggle": "Acolyte Violence Noggle",
    "0 nogglesflair alad-v-noggle": "Alad V Noggle",
    "14 nogglesflair arid-seeker-noggle": "Arid Seeker Noggle",
    "15 nogglesflair ash-noggle": "Ash Noggle",
    "16 nogglesflair banshee-noggle": "Banshee Noggle",
    "1 nogglesflair baro-ki-teer-noggle": "Baro Ki'Teer Noggle",
    "17 nogglesflair battalyst-noggle": "Battalyst Noggle",
    "2 nogglesflair captain-vor-noggle": "Captain Vor Noggle",
    "3 nogglesflair clem-noggle": "Clem Noggle",
    "18 nogglesflair conculyst-noggle": "Conculyst Noggle",
    "19 nogglesflair elite-arid-lancer-noggle": "Elite Arid Lancer Noggle",
    "20 nogglesflair ember-noggle": "Ember Noggle",
    "25 nogglesflair excalibur-prime-noggle": "Excalibur Prime Noggle (PC Founders exclusive)",
    "22 nogglesflair excalibur-noggle": "Excalibur Noggle",
    "21 nogglesflair excalibur-jade-noggle": "Excalibur (Jade) Noggle (XB1 exclusive)",
    "25 nogglesflair excalibur-obsidian-noggle": "Excalibur (Obsidian) Noggle (PS4 exclusive)",
    "24 nogglesflair excalibur-obsidian-azura-noggle": "Excalibur (Obsidian Azura) Noggle (PS4 exclusive)",
    "32 nogglesflair index-derim-zahn-noggle": "Index Claims Investigation Broker Derim Zahn Noggle",
    "35 nogglesflair index-jen-dro-noggle": "Index Claims Investigation Broker Jen Dro Noggle",
    "37 nogglesflair index-m-wam-noggle": "Index Claims Investigation Broker M-WAM Noggle",
    "42 nogglesflair index-tia-mayn-noggle": "Index Claims Investigation Broker Tia Mayn Noggle",
    "7 nogglesflair index-002-er-noggle": "Index Investor Relations Broker 002-ER Noggle",
    "29 nogglesflair index-armis-ulta-noggle": "Index Investor Relations Broker Armis Ulta Noggle",
    "33 nogglesflair index-dru-pesfor-noggle": "Index Investor Relations Broker Dru Pesfor Noggle",
    "40 nogglesflair index-rana-del-noggle": "Index Investor Relations Broker Rana Del Noggle",
    "36 nogglesflair index-lockjaw-and-sol-noggle": "Index Reclamation Unit Broker Lockjaw and Sol Noggle",
    "38 nogglesflair index-nako-xol-noggle": "Index Reclamation Unit Broker Nako Xol Noggle",
    "39 nogglesflair index-pelna-cade-noggle": "Index Reclamation Unit Broker Pelna Cade Noggle",
    "43 nogglesflair index-ved-xol-noggle": "Index Reclamation Unit Broker Ved Xol Noggle",
    "30 nogglesflair index-auditor-noggle": "Index Trading Group Broker Auditor Noggle",
    "31 nogglesflair index-azoth-noggle": "Index Trading Group Broker Azoth Noggle",
    "34 nogglesflair index-jad-teran-noggle": "Index Trading Group Broker Jad Teran Noggle",
    "41 nogglesflair index-raptor-rx-noggle": "Index Trading Group Broker Raptor RX Noggle",
    "55 nogglesflair rathuum-executioner-dhurnam-noggle": "Rathuum Executioner Dhurnam Noggle",
    "56 nogglesflair rathuum-executioner-dok-thul-noggle": "Rathuum Executioner Dok Thul Noggle",
    "57 nogglesflair rathuum-executioner-garesh-noggle": "Rathuum Executioner Garesh Noggle",
    "58 nogglesflair rathuum-executioner-gorth-noggle": "Rathuum Executioner Gorth Noggle",
    "59 nogglesflair rathuum-executioner-harkonar-noggle": "Rathuum Executioner Harkonar Noggle",
    "60 nogglesflair rathuum-executioner-nok-noggle": "Rathuum Executioner Nok Noggle",
    "61 nogglesflair rathuum-executioner-reth-noggle": "Rathuum Executioner Reth Noggle",
    "62 nogglesflair rathuum-executioner-vay-molta-noggle": "Rathuum Executioner Vay Molta Noggle",
    "63 nogglesflair rathuum-executioner-zura-noggle": "Rathuum Executioner Zura Noggle",
    "26 nogglesflair frost-noggle": "Frost Noggle",
    "4 nogglesflair general-sargas-ruk-noggle": "General Sargas Ruk Noggle",
    "27 nogglesflair hydroid-noggle": "Hydroid Noggle",
    "28 nogglesflair hyekka-noggle": "Hyekka Noggle",
    "44 nogglesflair kela-de-thaym-noggle": "Kela De Thaym Noggle",
    "45 nogglesflair lancer-noggle": "Lancer Noggle",
    "46 nogglesflair loki-noggle": "Loki Noggle",
    "5 nogglesflair the-lotus-noggle": "Lotus Noggle",
    "47 nogglesflair mag-noggle": "Mag Noggle",
    "48 nogglesflair mirage-noggle": "Mirage Noggle",
    "50 nogglesflair nekros-noggle": "Nekros Noggle",
    "51 nogglesflair nezha-noggle": "Nezha Noggle",
    "52 nogglesflair nova-noggle": "Nova Noggle",
    "53 nogglesflair nyx-noggle": "Nyx Noggle",
    "54 nogglesflair oberon-noggle": "Oberon Noggle",
    "64 nogglesflair rhino-noggle": "Rhino Noggle",
    "65 nogglesflair saryn-noggle": "Saryn Noggle",
    "66 nogglesflair trinity-noggle": "Trinity Noggle",
    "67 nogglesflair valkyr-noggle": "Valkyr Noggle",
    "68 nogglesflair vauban-noggle": "Vauban Noggle",
    "69 nogglesflair volt-noggle": "Volt Noggle",
    "70 nogglesflair wukong-noggle": "Wukong Noggle",
    "71 nogglesflair zephyr-noggle": "Zephyr Noggle",
    "6 nogglesflair stalker-noggle": "??????? Noggle",
    
    
    /* Sigils */
    "0 sigilsflair boss-alad-v-sigil": "Alad V",
    "1 sigilsflair boss-ambulas-sigil": "Ambulas",
    "2 sigilsflair boss-captain-vor-sigil": "Captain Vor",
    "3 sigilsflair boss-hyena-pack-sigil": "Hyena Pack",
    "4 sigilsflair boss-jackal-sigil": "Jackal",
    "5 sigilsflair boss-kela-de-thaym-sigil": "Kela De Thaym",
    "6 sigilsflair boss-lephantis-sigil": "Lephantis",
    "7 sigilsflair boss-lynx-sigil": "Lynx",
    "8 sigilsflair boss-nef-anyo-sigil": "Nef Anyo",
    "9 sigilsflair boss-phorid-sigil": "Phorid",
    "10 sigilsflair boss-raptor-sigil": "Raptor",
    "11 sigilsflair boss-tyl-regor-sigil": "Tyl Regor",
    "12 sigilsflair boss-councilor-vey-hek-sigil": "Councilor Vey Hek",
    "13 sigilsflair boss-general-sargas-ruk-sigil": "General Sargas Ruk",
    "14 sigilsflair boss-lieutenant-lech-kril-sigil": "Lieutenant Lech Kril",
    "15 sigilsflair syndicate-arbiters-of-hexis-sigil": "Arbiters of Hexis",
    "16 sigilsflair syndicate-arbiters-of-hexis-level-1-sigil": "Guiding Path (Arbiters of Hexis)",
    "17 sigilsflair syndicate-arbiters-of-hexis-level-2-sigil": "Bending Will (Arbiters of Hexis)",
    "18 sigilsflair syndicate-arbiters-of-hexis-level-3-sigil": "Discipline (Arbiters of Hexis)",
    "19 sigilsflair syndicate-arbiters-of-hexis-level-4-sigil": "Will (Arbiters of Hexis)",
    "20 sigilsflair syndicate-arbiters-of-hexis-level-5-sigil": "Choice (Arbiters of Hexis)",
    "21 sigilsflair syndicate-arbiters-of-hexis-level-6-sigil": "Growth (Arbiters of Hexis)",
    "22 sigilsflair syndicate-arbiters-of-hexis-level-7-sigil": "Potential (Arbiters of Hexis)",
    "23 sigilsflair syndicate-arbiters-of-hexis-level-8-sigil": "Succession (Arbiters of Hexis)",
    "24 sigilsflair syndicate-arbiters-of-hexis-level-9-sigil": "Surpassing (Arbiters of Hexis)",
    "25 sigilsflair syndicate-arbiters-of-hexis-level-10-sigil": "Truth (Arbiters of Hexis)",
    "26 sigilsflair syndicate-cephalon-simaris-sigil": "Cephalon Simaris",
    "27 sigilsflair syndicate-cephalon-simaris-gold-sigil": "Cephalon Simaris (Gold)",
    "28 sigilsflair syndicate-cephalon-suda-sigil": "Cephalon Suda",
    "29 sigilsflair syndicate-cephalon-suda-level-1-sigil": "Query (Cephalon Suda)",
    "30 sigilsflair syndicate-cephalon-suda-level-2-sigil": "Searching (Cephalon Suda)",
    "31 sigilsflair syndicate-cephalon-suda-level-3-sigil": "Pattern Match (Cephalon Suda)",
    "32 sigilsflair syndicate-cephalon-suda-level-4-sigil": "Atomic (Cephalon Suda)",
    "33 sigilsflair syndicate-cephalon-suda-level-5-sigil": "Manifold (Cephalon Suda)",
    "34 sigilsflair syndicate-cephalon-suda-level-6-sigil": "Fractal (Cephalon Suda)",
    "35 sigilsflair syndicate-cephalon-suda-level-7-sigil": "Multivariate (Cephalon Suda)",
    "36 sigilsflair syndicate-cephalon-suda-level-8-sigil": "Labryinth (Cephalon Suda)",
    "37 sigilsflair syndicate-cephalon-suda-level-9-sigil": "Hexan (Cephalon Suda)",
    "38 sigilsflair syndicate-cephalon-suda-level-10-sigil": "Oracle (Cephalon Suda)",
    "39 sigilsflair syndicate-conclave-sigil": "Conclave",
    "40 sigilsflair syndicate-conclave-level-1-sigil": "Awakening (Conclave)",
    "41 sigilsflair syndicate-conclave-level-2-sigil": "Perception (Conclave)",
    "42 sigilsflair syndicate-conclave-level-3-sigil": "Awareness (Conclave)",
    "43 sigilsflair syndicate-conclave-level-4-sigil": "Revelation (Conclave)",
    "44 sigilsflair syndicate-conclave-level-5-sigil": "Diligence (Conclave)",
    "45 sigilsflair syndicate-conclave-level-6-sigil": "Enlightenment (Conclave)",
    "46 sigilsflair syndicate-conclave-level-7-sigil": "Prudence (Conclave)",
    "47 sigilsflair syndicate-conclave-level-8-sigil": "Discretion (Conclave)",
    "48 sigilsflair syndicate-conclave-level-9-sigil": "Ambition (Conclave)",
    "49 sigilsflair syndicate-conclave-level-10-sigil": "Volition (Conclave)",
    "50 sigilsflair syndicate-conclave-level-11-sigil": "Discovery (Conclave)",
    "51 sigilsflair syndicate-conclave-level-12-sigil": "Accord (Conclave)",
    "52 sigilsflair syndicate-conclave-level-13-sigil": "Insight (Conclave)",
    "53 sigilsflair syndicate-conclave-level-14-sigil": "Empathy (Conclave)",
    "54 sigilsflair syndicate-conclave-level-15-sigil": "Unity (Conclave)",
    "55 sigilsflair syndicate-conclave-level-16-sigil": "Freedom (Conclave)",
    "56 sigilsflair syndicate-new-loka-sigil": "New Loka",
    "57 sigilsflair syndicate-new-loka-level-1-sigil": "Sacrifice (New Loka)",
    "58 sigilsflair syndicate-new-loka-level-2-sigil": "Seed (New Loka)",
    "59 sigilsflair syndicate-new-loka-level-3-sigil": "Rebirth (New Loka)",
    "60 sigilsflair syndicate-new-loka-level-4-sigil": "Growth (New Loka)",
    "61 sigilsflair syndicate-new-loka-level-5-sigil": "Clarity (New Loka)",
    "62 sigilsflair syndicate-new-loka-level-6-sigil": "Bloom (New Loka)",
    "63 sigilsflair syndicate-new-loka-level-7-sigil": "Purity (New Loka)",
    "64 sigilsflair syndicate-new-loka-level-8-sigil": "Gaia (New Loka)",
    "65 sigilsflair syndicate-new-loka-level-9-sigil": "Bounty (New Loka)",
    "66 sigilsflair syndicate-new-loka-level-10-sigil": "Humanity (New Loka)",
    "67 sigilsflair syndicate-red-veil-sigil": "Red Veil",
    "68 sigilsflair syndicate-red-veil-level-1-sigil": "Blades (Red Veil)",
    "69 sigilsflair syndicate-red-veil-level-2-sigil": "Cull (Red Veil)",
    "70 sigilsflair syndicate-red-veil-level-3-sigil": "Threat (Red Veil)",
    "71 sigilsflair syndicate-red-veil-level-4-sigil": "Maelstrom (Red Veil)",
    "72 sigilsflair syndicate-red-veil-level-5-sigil": "Lesion (Red Veil)",
    "73 sigilsflair syndicate-red-veil-level-6-sigil": "Ruin (Red Veil)",
    "74 sigilsflair syndicate-red-veil-level-7-sigil": "Viscera (Red Veil)",
    "75 sigilsflair syndicate-red-veil-level-8-sigil": "Malevolent (Red Veil)",
    "76 sigilsflair syndicate-red-veil-level-9-sigil": "Covert (Red Veil)",
    "77 sigilsflair syndicate-red-veil-level-10-sigil": "Assassin (Red Veil)",
    "78 sigilsflair syndicate-steel-meridian-sigil": "Steel Meridian",
    "79 sigilsflair syndicate-steel-meridian-level-1-sigil": "Defiance (Steel Meridian)",
    "80 sigilsflair syndicate-steel-meridian-level-2-sigil": "Armada (Steel Meridian)",
    "81 sigilsflair syndicate-steel-meridian-level-3-sigil": "Vigilance (Steel Meridian)",
    "82 sigilsflair syndicate-steel-meridian-level-4-sigil": "Uprising (Steel Meridian)",
    "83 sigilsflair syndicate-steel-meridian-level-5-sigil": "Protectorate (Steel Meridian)",
    "84 sigilsflair syndicate-steel-meridian-level-6-sigil": "Freedom Fighter (Steel Meridian)",
    "85 sigilsflair syndicate-steel-meridian-level-7-sigil": "Armored (Steel Meridian)",
    "86 sigilsflair syndicate-steel-meridian-level-8-sigil": "Rebellion (Steel Meridian)",
    "87 sigilsflair syndicate-steel-meridian-level-9-sigil": "Unyielding (Steel Meridian)",
    "88 sigilsflair syndicate-steel-meridian-level-10-sigil": "Champion (Steel Meridian)",
    "89 sigilsflair syndicate-the-perrin-sequence-sigil": "The Perrin Sequence",
    "90 sigilsflair syndicate-the-perrin-sequence-level-1-sigil": "Progress (The Perrin Sequence)",
    "91 sigilsflair syndicate-the-perrin-sequence-level-2-sigil": "Opportunity (The Perrin Sequence)",
    "92 sigilsflair syndicate-the-perrin-sequence-level-3-sigil": "Calculating (The Perrin Sequence)",
    "93 sigilsflair syndicate-the-perrin-sequence-level-4-sigil": "Synergy (The Perrin Sequence)",
    "94 sigilsflair syndicate-the-perrin-sequence-level-5-sigil": "Directives (The Perrin Sequence)",
    "95 sigilsflair syndicate-the-perrin-sequence-level-6-sigil": "Strategy (The Perrin Sequence)",
    "96 sigilsflair syndicate-the-perrin-sequence-level-7-sigil": "Tessilations [sic] (The Perrin Sequence)",
    "97 sigilsflair syndicate-the-perrin-sequence-level-8-sigil": "Optimum (The Perrin Sequence)",
    "98 sigilsflair syndicate-the-perrin-sequence-level-9-sigil": "Capital (The Perrin Sequence)",
    "99 sigilsflair syndicate-the-perrin-sequence-level-10-sigil": "Chairman (The Perrin Sequence)",
    "100 sigilsflair prime-cycuta-sigil": "Cycuta Prime",
    "101 sigilsflair prime-verlorum-sigil": "Verlorum Prime",
    "102 sigilsflair banshee-soprana-sigil": "Banshee Soprana",
    "103 sigilsflair blade-and-gun-sigil": "Blade and Gun",
    "104 sigilsflair cycle-one-sigil": "Cycle One (PS4 exclusive)",
    "105 sigilsflair cycle-three-sigil": "Cycle Three (PS4 exclusive)",
    "106 sigilsflair cycle-two-sigil": "Cycle Two (PS4 exclusive)",
    "107 sigilsflair day-of-the-dead-sigil": "Day of the Dead",
    "108 sigilsflair festive-sigil": "Festive",
    "109 sigilsflair festive-i-wreath-sigil": "Festive I (Wreath)",
    "110 sigilsflair festive-ii-nistlebrush-sigil": "Festive II (Nistlebrush)",
    "111 sigilsflair festive-iii-tolling-sigil": "Festive III (Tolling)",
    "112 sigilsflair festive-iv-evergreen-sigil": "Festive IV (Evergreen)",
    "113 sigilsflair kuria-sigil": "Kuria",
    "114 sigilsflair kuria-gold-sigil": "Kuria (Gold)",
    "115 sigilsflair login-a-imminent-eclipse-sigil": "Imminent Eclipse (Login)",
    "116 sigilsflair login-b-awakened-luna-sigil": "Awakened Luna (Login)",
    "117 sigilsflair login-c-eternal-stasis-sigil": "Eternal Stasis (Login)",
    "118 sigilsflair login-d-solar-flare-sigil": "Solar Flare (Login)",
    "119 sigilsflair prisma-sigil": "Prisma",
    "120 sigilsflair rhino-palatine-sigil": "Rhino Palatine",
    "121 sigilsflair rift-sigil": "Rift",
    "122 sigilsflair scar-sigil": "Scar",
    "123 sigilsflair seal-of-honoring-sigil": "Seal of Honoring (XB1 exclusive)",
    "124 sigilsflair seal-of-honoring-ii-sigil": "Seal of Honoring II (XB1 exclusive)",
    "125 sigilsflair solstice-i-sigil": "Solstice I",
    "126 sigilsflair solstice-ii-sigil": "Solstice II",
    "127 sigilsflair solstice-iii-sigil": "Solstice III",
    "128 sigilsflair solstice-iv-sigil": "Solstice IV",
    "129 sigilsflair solstice-v-sigil": "Solstice V",
    "130 sigilsflair year-monquis-china-sigil": "Monquis (China)",
    "131 sigilsflair year-monquis-world-sigil": "Monquis (International)",
    
    
    /* Miscellaneous Flairs (0-26) */
    "0 miscellaneousflair disciple": "Disciple Founder (PC Founders exclusive)",
    "1 miscellaneousflair hunter": "Hunter Founder (PC Founders exclusive)",
    "2 miscellaneousflair master": "Master Founder (PC Founders exclusive)",
    "3 miscellaneousflair grandmaster": "Grand Master Founder (PC Founders exclusive)",
    /*"4 miscellaneousflair revive": "Moderator",*/
    /*"5 miscellaneousflair lotus": "DE Employee",*/
    "6 miscellaneousflair kubrow": "Kubrow",
    "7 miscellaneousflair kubrow-chesa": "Kubrow (Chesa)",
    "8 miscellaneousflair kubrow-huras": "Kubrow (Huras)",
    "9 miscellaneousflair kubrow-raksa": "Kubrow (Raksa)",
    "10 miscellaneousflair kubrow-sahasa": "Kubrow (Sahasa)",
    "11 miscellaneousflair kubrow-sunika": "Kubrow (Sunika)",
    "12 miscellaneousflair kavat-a": "Kavat",
    "13 miscellaneousflair kavat": "Kavat",
    "14 miscellaneousflair kavat-c": "Kavat",
    "15 miscellaneousflair kavat-d": "Kavat",
    "16 miscellaneousflair pc": "PC",
    "17 miscellaneousflair ps4": "PS4",
    "18 miscellaneousflair xb1": "XB1"
};
