/* FLAIR MASTER CONFIG | auto-generated at 2016-12-21T02:13:37-0800 (ISO-8601) */ 
flair.load__by_id = function() {
    for (var key in flair.names) {
        if (flair.names.hasOwnProperty(key)) {
            var data = key.split(' ');
            
            var orig_id = data[2];
            
            if (orig_id.substring(0, 'a'.length) === 'a') {
                orig_id = orig_id.substring(1);
            }
            if (orig_id.substring(orig_id.length - 'm'.length) === 'm') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 'o'.length) === 'o') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 'x'.length) === 'x') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 'y'.length) === 'y') {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            if (orig_id.substring(orig_id.length - 1).match(/[a-z]/i) &&
                orig_id.substring(0, orig_id.length - 1).match(/^\d+$/)) {
                orig_id = orig_id.substring(0, orig_id.length - 1);
            }
            
            flair.by_id[data[2]] = {
                key: key,
                spritepos: data[0],
                sheet: data[1],
                flair_id: data[2],
                orig_id: orig_id,
                flair_name: flair.names[key],
                flair_class: ' flair-'+data[0] + ' flair-'+data[1] + ' flair-'+data[2]
            }
        }
    }
}
flair.by_id = {}
flair.names = {
/* [STANDARD] */

    /* Remove Flair*/
    "0 removeflair none": "Remove Flair",
    
    /* Prime Warframes (0-14) */
    "0 primewarframesflair ash-prime": "Ash Prime",
    "1 primewarframesflair ember-prime": "Ember",
    "2 primewarframesflair excalibur-prime": "Excalibur Prime (PC Founders exclusive)",
    "3 primewarframesflair frost-prime": "Frost Prime",
    "4 primewarframesflair loki-prime": "Loki Prime",
    "5 primewarframesflair mag-prime": "Mag Prime",
    "6 primewarframesflair nekros-prime": "Nekros Prime",
    "7 primewarframesflair nova-prime": "Nova Prime",
    "8 primewarframesflair nyx-prime": "Nyx Prime",
    "9 primewarframesflair rhino-prime": "Rhino Prime",
    "10 primewarframesflair saryn-prime": "Saryn Prime",
    "11 primewarframesflair trinity-prime": "Trinity Prime",
    "12 primewarframesflair vauban-prime": "Vauban Prime",
    "13 primewarframesflair volt-prime": "Volt Prime",
    "14 primewarframesflair valkyr-prime": "Valkyr Prime",
    
    
    /* Regular Warframes (0-30) */
    "0 regularwarframesflair ash": "Ash",
    "1 regularwarframesflair atlas": "Atlas",
    "2 regularwarframesflair banshee": "Banshee",
    "3 regularwarframesflair chroma": "Chroma",
    "4 regularwarframesflair ember": "Ember",
    "5 regularwarframesflair equinox": "Equinox",
    "6 regularwarframesflair excalibur": "Excalibur",
    "7 regularwarframesflair frost": "Frost",
    "8 regularwarframesflair hydroid": "Hydroid",
    "9 regularwarframesflair inaros": "Inaros",
    "10 regularwarframesflair ivara": "Ivara",
    "11 regularwarframesflair limbo": "Limbo",
    "12 regularwarframesflair loki": "Loki",
    "13 regularwarframesflair mag": "Mag",
    "14 regularwarframesflair mesa": "Mesa",
    "15 regularwarframesflair mirage": "Mirage",
    "16 regularwarframesflair nekros": "Nekros",
    "17 regularwarframesflair nezha": "Nezha",
    "18 regularwarframesflair nidus": "Nidus",
    "19 regularwarframesflair nova": "Nova",
    "20 regularwarframesflair nyx": "Nyx",
    "21 regularwarframesflair oberon": "Oberon",
    "22 regularwarframesflair rhino": "Rhino",
    "23 regularwarframesflair saryn": "Saryn",
    "24 regularwarframesflair titania": "Titania",
    "25 regularwarframesflair trinity": "Trinity",
    "26 regularwarframesflair valkyr": "Valkyr",
    "27 regularwarframesflair vauban": "Vauban",
    "28 regularwarframesflair volt": "Volt",
    "29 regularwarframesflair wukong": "Wukong",
    "30 regularwarframesflair zephyr": "Zephyr",
    
    
    /* Deluxe Warframe Helmets (50-60)*/
    "50 deluxewarframeskinsflair ash-koga": "Ash (Koga)",
    "51 deluxewarframeskinsflair banshee-soprana": "Banshee (Soprana)",
    "52 deluxewarframeskinsflair excalibur-proto": "Excalibur (Proto)",
    "53 deluxewarframeskinsflair loki-knave": "Loki (Knave)",
    "54 deluxewarframeskinsflair nova-asuri": "Nova (Asuri)",
    "55 deluxewarframeskinsflair nyx-nemesis": "Nyx (Nemesis)",
    "56 deluxewarframeskinsflair oberon-feyarch": "Oberon (Feyarch)",
    "57 deluxewarframeskinsflair rhino-palatine": "Rhino (Palatine)",
    "58 deluxewarframeskinsflair saryn-orphid": "Saryn (Orphid)",
    "59 deluxewarframeskinsflair trinity-strega": "Trinity (Strega)",
    "60 deluxewarframeskinsflair valkyr-gersemi": "Valkyr (Gersemi)",
    
    
    /* TennoGen Warframe Helmets (0-66)*/
    "0 tennogenwarframehelmetsflair ash-carabid": "Ash (Carabid by artarrwen — Steam exclusive)",
    "1 tennogenwarframehelmetsflair atlas-arhat": "Atlas (Arhat by Rekkou — Steam exclusive)",
    "2 tennogenwarframehelmetsflair atlas-telamon": "Atlas (Telamon by artarrwen — Steam exclusive)",
    "3 tennogenwarframehelmetsflair banshee-echo": "Banshee (Echo by Rekkou — Steam exclusive)",
    "4 tennogenwarframehelmetsflair chroma-drevni": "Chroma (Drevni by Volkovyi — Steam exclusive)",
    "5 tennogenwarframehelmetsflair chroma-kaiju": "Chroma (Kaiju by [k a z] — Steam exclusive)",
    "6 tennogenwarframehelmetsflair chroma-tarrasque": "Chroma (Tarrasque by artarrwen — Steam exclusive)",
    "7 tennogenwarframehelmetsflair chroma-vojnik": "Chroma (Vojnik Battle-Damaged by Volkovyi — Steam exclusive)",
    "8 tennogenwarframehelmetsflair ember-graxx": "Ember (Graxx by Faven_PS — Steam exclusive)",
    "9 tennogenwarframehelmetsflair excalibur-apex": "Excalibur (Apex by antoineflemming — Steam exclusive)",
    "10 tennogenwarframehelmetsflair excalibur-arturius": "Excalibur (Arturius by [k a z] — Steam exclusive)",
    "11 tennogenwarframehelmetsflair excalibur-caduto": "Excalibur (Caduto by Hitsu San — Steam exclusive)",
    "12 tennogenwarframehelmetsflair excalibur-graxx": "Excalibur (Graxx by Faven_PS — Steam exclusive)",
    "13 tennogenwarframehelmetsflair excalibur-graxx-alt": "Excalibur (Graxx Alt by Faven_PS — Steam exclusive)",
    "14 tennogenwarframehelmetsflair excalibur-isurus": "Excalibur (Isurus by Coridium — Steam exclusive)",
    "15 tennogenwarframehelmetsflair excalibur-ogrant": "Excalibur (Ogrant by lokimonkeye — Steam exclusive)",
    "16 tennogenwarframehelmetsflair excalibur-sentient-slayer": "Excalibur (Sentient Slayer by CommanderApocalypse — Steam exclusive)",
    "17 tennogenwarframehelmetsflair excalibur-vespula-gold": "Excalibur (Vespula Gold by polygonmonster — Steam exclusive)",
    "18 tennogenwarframehelmetsflair frost-emperor": "Frost (Emperor by Hitsu San — Steam exclusive)",
    "19 tennogenwarframehelmetsflair frost-grost": "Frost (Grost by Faven_PS — Steam exclusive)",
    "20 tennogenwarframehelmetsflair frost-hailstorm": "Frost (Hailstorm by Arsenal — Steam exclusive)",
    "21 tennogenwarframehelmetsflair frost-jotun": "Frost (Jotun by malayu — Steam exclusive)",
    "22 tennogenwarframehelmetsflair frost-summit": "Frost (Summit by artarrwen — Steam exclusive)",
    "23 tennogenwarframehelmetsflair frost-vojnik": "Frost (Vojnik Battle-Damaged by Volkovyi — Steam exclusive)",
    "24 tennogenwarframehelmetsflair frost-zastruga": "Frost (Zastruga by Rekkou — Steam exclusive)",
    "25 tennogenwarframehelmetsflair loki-ersatz": "Loki (Ersatz by Rekkou — Steam exclusive)",
    "26 tennogenwarframehelmetsflair loki-rogue": "Loki (Rogue by artarrwen — Steam exclusive)",
    "27 tennogenwarframehelmetsflair mag-alata": "Mag (Alata by Hitsu San — Steam exclusive)",
    "28 tennogenwarframehelmetsflair mag-anthro": "Mag (Anthro by Pior — Steam exclusive)",
    "29 tennogenwarframehelmetsflair mag-induction": "Mag (Induction by Pior — Steam exclusive)",
    "30 tennogenwarframehelmetsflair mag-knaita": "Mag (Knaita by prosetisen — Steam exclusive)",
    "31 tennogenwarframehelmetsflair mag-orbit": "Mag (Orbit by Del — Steam exclusive)",
    "32 tennogenwarframehelmetsflair mag-toroidal": "Mag (Toroidal by prosetisen — Steam exclusive)",
    "33 tennogenwarframehelmetsflair mesa-deadeye": "Mesa (Deadeye by NotYou — Steam exclusive)",
    "34 tennogenwarframehelmetsflair mesa-falcon": "Mesa (Falcon by prosetisen — Steam exclusive)",
    "35 tennogenwarframehelmetsflair mirage-graxx": "Mirage (Graxx by Faven_PS — Steam exclusive)",
    "36 tennogenwarframehelmetsflair mirage-jolli": "Mirage (Jolli by Cheshire — Steam exclusive)",
    "37 tennogenwarframehelmetsflair mirage-sigyn": "Mirage (Sigyn by Novabjorn — Steam exclusive)",
    "38 tennogenwarframehelmetsflair nekros-lazarus": "Nekros (Lazarus by [k a z] — Steam exclusive)",
    "39 tennogenwarframehelmetsflair nova-cygni": "Nova (Cygni by Arsenal — Steam exclusive)",
    "40 tennogenwarframehelmetsflair nova-device": "Nova (Device by posetisen — Steam exclusive)",
    "41 tennogenwarframehelmetsflair nova-fusion": "Nova (Fusion by Coridium — Steam exclusive)",
    "42 tennogenwarframehelmetsflair nova-gnova": "Nova (Gnova by Faven_PS — Steam exclusive)",
    "43 tennogenwarframehelmetsflair nova-lamia": "Nova (Lamia by Mz-3 — Steam exclusive)",
    "44 tennogenwarframehelmetsflair nova-stinger": "Nova (Stinger by Cheshire — Steam exclusive)",
    "45 tennogenwarframehelmetsflair nova-tachyon": "Nova (Tachyon by Rekkou — Steam exclusive)",
    "46 tennogenwarframehelmetsflair nova-visage": "Nova (Visage by Hitsu San — Steam exclusive)",
    "47 tennogenwarframehelmetsflair nyx-athena": "Nyx (Athena by prosetisen — Steam exclusive)",
    "48 tennogenwarframehelmetsflair nyx-graxx": "Nyx (Graxx by Faven_PS — Steam exclusive)",
    "49 tennogenwarframehelmetsflair oberon-destrier": "Oberon (Destrier by Rekkou — Steam exclusive)",
    "50 tennogenwarframehelmetsflair rhino-graxx": "Rhino (Graxx by Faven_PS — Steam exclusive)",
    "51 tennogenwarframehelmetsflair rhino-vojnik": "Rhino (Vojnik Battle-Damaged by Volkovyi — Steam exclusive)",
    "52 tennogenwarframehelmetsflair saryn-graxx": "Saryn (Graxx by Faven_PS — Steam exclusive)",
    "53 tennogenwarframehelmetsflair trinity-messiah": "Trinity (Messiah by Cheshire — Steam exclusive)",
    "54 tennogenwarframehelmetsflair valkyr-cheetah": "Valkyr (Cheetah by Cheshire — Steam exclusive)",
    "55 tennogenwarframehelmetsflair valkyr-graxx": "Valkyr (Graxx by Faven_PS — Steam exclusive)",
    "56 tennogenwarframehelmetsflair vauban-chapelon": "Vauban (Chapelon by Rekkou — Steam exclusive)",
    "57 tennogenwarframehelmetsflair volt-amp": "Volt (Amp by Faven_PS — Steam exclusive)",
    "58 tennogenwarframehelmetsflair volt-arrester": "Volt (Arrester by Rekkou — Steam exclusive)",
    "59 tennogenwarframehelmetsflair volt-graxx": "Volt (Graxx by Faven_PS — Steam exclusive)",
    "60 tennogenwarframehelmetsflair volt-relay": "Volt (Relay by DespicableCheese — Steam exclusive)",
    "61 tennogenwarframehelmetsflair volt-thales": "Volt (Thales by Arsenal — Steam exclusive)",
    "62 tennogenwarframehelmetsflair wukong-xingzhe": "Wukong (Xingzhe by Rekkou — Steam exclusive)",
    "63 tennogenwarframehelmetsflair zephyr-hagoromo": "Zephyr (Hagoromo by Hitsu San — Steam exclusive)",
    "64 tennogenwarframehelmetsflair zephyr-migisi": "Zephyr (Migisi by FrellingHazmot — Steam exclusive)",
    "65 tennogenwarframehelmetsflair zephyr-monsoon": "Zephyr (Monsoon by artarrwen — Steam exclusive)",
    "66 tennogenwarframehelmetsflair zephyr-skeiron": "Zephyr (Skeiron by novadragon01 — Steam exclusive)",

        
    /* Other Warframe Helmets (0–66) */
    "0 otherwarframehelmetsflair ash-locust": "Ash (Locust)",
    "1 otherwarframehelmetsflair ash-scorpion": "Ash (Scorpion)",
    "2 otherwarframehelmetsflair atlas-shikoro": "Atlas (Shikoro)",
    "3 otherwarframehelmetsflair atlas-tartarus": "Atlas (Tartarus)",
    "4 otherwarframehelmetsflair banshee-chorus": "Banshee (Chorus)",
    "5 otherwarframehelmetsflair banshee-reverb": "Banshee (Reverb)",
    "6 otherwarframehelmetsflair chroma-amaru": "Chroma (Amaru)",
    "7 otherwarframehelmetsflair chroma-drac": "Chroma (Drac)",
    "8 otherwarframehelmetsflair ember-backdraft": "Ember (Backdraft)",
    "9 otherwarframehelmetsflair ember-phoenix": "Ember (Phoenix)",
    "10 otherwarframehelmetsflair equinox-solstice": "Equinox (Solstice)",
    "11 otherwarframehelmetsflair excalibur-avalon": "Excalibur (Avalon)",
    "13 otherwarframehelmetsflair excalibur-jade": "Excalibur (Jade — XB1 exclusive)",
    "14 otherwarframehelmetsflair excalibur-mordred": "Excalibur (Mordred)",
    "15 otherwarframehelmetsflair excalibur-obsidian": "Excalibur (Obsidian)",
    "16 otherwarframehelmetsflair excalibur-obsidian-azura": "Excalibur (Obsidian Azura)",
    "17 otherwarframehelmetsflair excalibur-pendragon": "Excalibur (Pendragon)",
    "18 otherwarframehelmetsflair excalibur-prisma": "Excalibur (Prisma)",
    "19 otherwarframehelmetsflair excalibur-prisma-avalon": "Excalibur (Prisma Avalon)",
    "20 otherwarframehelmetsflair excalibur-prisma-pendragon": "Excalibur (Prisma Pendragon)",
    "21 otherwarframehelmetsflair frost-aurora": "Frost (Aurora)",
    "22 otherwarframehelmetsflair frost-squall": "Frost (Squall)",
    "23 otherwarframehelmetsflair hydroid-ketos": "Hydroid (Ketos)",
    "24 otherwarframehelmetsflair hydroid-triton": "Hydroid (Triton)",
    "25 otherwarframehelmetsflair inaros-anubis": "Inaros (Anubis)",
    "26 otherwarframehelmetsflair ivara-loxley": "Ivara (Loxley)",
    "27 otherwarframehelmetsflair limbo-aristeas": "Limbo (Aristeas)",
    "28 otherwarframehelmetsflair limbo-magrite": "Limbo (Magrite)",
    "29 otherwarframehelmetsflair loki-enigma": "Loki (Enigma)",
    "30 otherwarframehelmetsflair loki-essence": "Loki (Essence)",
    "31 otherwarframehelmetsflair loki-swindle": "Loki (Swindle)",
    "32 otherwarframehelmetsflair mag-coil": "Mag (Coil)",
    "33 otherwarframehelmetsflair mag-gauss": "Mag (Gauss)",
    "34 otherwarframehelmetsflair mesa-longhorn": "Mesa (Longhorn)",
    "35 otherwarframehelmetsflair mesa-ovis": "Mesa (Ovis)",
    "36 otherwarframehelmetsflair mirage-harlequin": "Mirage (Harlequin)",
    "37 otherwarframehelmetsflair mirage-trivelin": "Mirage (Trivelin)",
    "38 otherwarframehelmetsflair nekros-raknis": "Nekros (Raknis)",
    "39 otherwarframehelmetsflair nekros-shroud": "Nekros (Shroud)",
    "40 otherwarframehelmetsflair nezha-circa": "Nezha (Circa)",
    "41 otherwarframehelmetsflair nidus-prion": "Nidus (Prion)",
    "42 otherwarframehelmetsflair nova-flux": "Nova (Flux)",
    "43 otherwarframehelmetsflair nova-quantum": "Nova (Quantum)",
    "44 otherwarframehelmetsflair nova-slipstream": "Nova (Slipstream)",
    "45 otherwarframehelmetsflair nyx-menticide": "Nyx (Menticide)",
    "46 otherwarframehelmetsflair nyx-vespa": "Nyx (Vespa)",
    "47 otherwarframehelmetsflair oberon-markhor": "Oberon (Markhor)",
    "48 otherwarframehelmetsflair oberon-oryx": "Oberon (Oryx)",
    "49 otherwarframehelmetsflair rhino-rubedo": "Rhino (Rubedo — Steam exclusive)",
    "50 otherwarframehelmetsflair rhino-thrak": "Rhino (Thrak)",
    "51 otherwarframehelmetsflair rhino-vanguard": "Rhino (Vanguard)",
    "52 otherwarframehelmetsflair saryn-chlora": "Saryn (Chlora)",
    "53 otherwarframehelmetsflair saryn-hemlock": "Saryn (Hemlock)",
    "54 otherwarframehelmetsflair titania-aurai": "Titania (Aurai)",
    "55 otherwarframehelmetsflair trinity-aura": "Trinity (Aura)",
    "56 otherwarframehelmetsflair trinity-meridian": "Trinity (Meridian)",
    "57 otherwarframehelmetsflair valkyr-bastet": "Valkyr (Bastet)",
    "58 otherwarframehelmetsflair valkyr-kara": "Valkyr (Kara)",
    "59 otherwarframehelmetsflair vauban-armistice": "Vauban (Armistice)",
    "60 otherwarframehelmetsflair vauban-esprit": "Vauban (Esprit)",
    "61 otherwarframehelmetsflair vauban-gambit": "Vauban (Gambit)",
    "62 otherwarframehelmetsflair volt-pulse": "Volt (Pulse)",
    "63 otherwarframehelmetsflair volt-storm": "Volt (Storm)",
    "64 otherwarframehelmetsflair wukong-dasheng": "Wukong (Dasheng)",
    "65 otherwarframehelmetsflair zephyr-cierzo": "Zephyr (Cierzo)",
    "66 otherwarframehelmetsflair zephyr-tengu": "Zephyr (Tengu)",
    
    
    /* Deluxe Warframe Skins (0–10)*/
    "0 deluxewarframeskinsflair ash-koga": "Ash (Koga)",
    "1 deluxewarframeskinsflair banshee-soprana": "Banshee (Soprana)",
    "2 deluxewarframeskinsflair excalibur-proto": "Excalibur (Proto)",
    "3 deluxewarframeskinsflair loki-knave": "Loki (Knave)",
    "4 deluxewarframeskinsflair nova-asuri": "Nova (Asuri)",
    "5 deluxewarframeskinsflair nyx-nemesis": "Nyx (Nemesis)",
    "6 deluxewarframeskinsflair oberon-feyarch": "Oberon (Feyarch)",
    "7 deluxewarframeskinsflair rhino-palatine": "Rhino (Palatine)",
    "8 deluxewarframeskinsflair saryn-orphid": "Saryn (Orphid)",
    "9 deluxewarframeskinsflair trinity-strega": "Trinity (Strega)",
    "10 deluxewarframeskinsflair valkyr-gersemi": "Valkyr (Gersemi)",
    
    
    /* TennoGen Warframe Skins (0-32)*/
    "0 tennogenwarframeskinsflair chroma-drevni": "Chroma (Drevni by Volkovyi — Steam exclusive)",
    "1 tennogenwarframeskinsflair chroma-vojnik": "Chroma (Vojnik Battle-Damaged by Volkovyi — Steam exclusive)",
    "2 tennogenwarframeskinsflair ember-graxx": "Ember (Graxx by Faven_PS — Steam exclusive)",
    "3 tennogenwarframeskinsflair excalibur-apex": "Excalibur (Apex by antoineflemming — Steam exclusive)",
    "4 tennogenwarframeskinsflair excalibur-caduto": "Excalibur (Caduto by Hitsu San — Steam exclusive)",
    "5 tennogenwarframeskinsflair excalibur-graxx": "Excalibur (Graxx by Faven_PS — Steam exclusive)",
    "6 tennogenwarframeskinsflair excalibur-sentient slayer": "Excalibur (Sentient Slayer by CommanderApocalypse — Steam exclusive)",
    "7 tennogenwarframeskinsflair excalibur-vespula gold": "Excalibur (Vespula Gold by polygonmonster — Steam exclusive)",
    "8 tennogenwarframeskinsflair frost-emperor": "Frost (Emperor by Hitsu San — Steam exclusive)",
    "9 tennogenwarframeskinsflair frost-grost": "Frost (Grost by Faven_PS — Steam exclusive)",
    "10 tennogenwarframeskinsflair frost-hailstorm": "Frost (Hailstorm by Arsenal — Steam exclusive)",
    "11 tennogenwarframeskinsflair frost-vojnik": "Frost (Vojnik Battle-Damaged by Volkovyi — Steam exclusive)",
    "12 tennogenwarframeskinsflair mag-alata": "Mag (Alata by Hitsu San — Steam exclusive)",
    "13 tennogenwarframeskinsflair mag-knaita": "Mag (Knaita by prosetisen — Steam exclusive)",
    "14 tennogenwarframeskinsflair mag-orbit": "Mag (Orbit by Del — Steam exclusive)",
    "15 tennogenwarframeskinsflair mirage-graxx": "Mirage (Graxx by Faven_PS — Steam exclusive)",
    "16 tennogenwarframeskinsflair mirage-sigyn": "Mirage (Sigyn by Novabjorn — Steam exclusive)",
    "17 tennogenwarframeskinsflair nova-cygni": "Nova (Cygni by Arsenal — Steam exclusive)",
    "18 tennogenwarframeskinsflair nova-device": "Nova (Device by posetisen — Steam exclusive)",
    "19 tennogenwarframeskinsflair nova-gnova": "Nova (Gnova by Faven_PS — Steam exclusive)",
    "20 tennogenwarframeskinsflair nova-lamia": "Nova (Lamia by Mz-3 — Steam exclusive)",
    "21 tennogenwarframeskinsflair nova-stinger": "Nova (Stinger by Cheshire — Steam exclusive)",
    "22 tennogenwarframeskinsflair nova-visage": "Nova (Visage by Hitsu San — Steam exclusive)",
    "23 tennogenwarframeskinsflair nyx-athena": "Nyx (Athena by prosetisen — Steam exclusive)",
    "24 tennogenwarframeskinsflair nyx-graxx": "Nyx (Graxx by Faven_PS — Steam exclusive)",
    "25 tennogenwarframeskinsflair rhino-graxx": "Rhino (Graxx by Faven_PS — Steam exclusive)",
    "26 tennogenwarframeskinsflair rhino-vojnik": "Rhino (Vojnik Battle-Damaged by Volkovyi — Steam exclusive)",
    "27 tennogenwarframeskinsflair saryn-graxx": "Saryn (Graxx by Faven_PS — Steam exclusive)",
    "28 tennogenwarframeskinsflair valkyr-graxx": "Valkyr (Graxx by Faven_PS — Steam exclusive)",
    "29 tennogenwarframeskinsflair volt-amp": "Volt (Amp by Faven_PS — Steam exclusive)",
    "30 tennogenwarframeskinsflair volt-graxx": "Volt (Graxx by Faven_PS — Steam exclusive)",
    "31 tennogenwarframeskinsflair zephyr-hagoromo": "Zephyr (Hagoromo by Hitsu San — Steam exclusive)",
    "32 tennogenwarframeskinsflair zephyr-skeiron": "Zephyr (Skeiron by novadragon01 — Steam exclusive)",

    
    
    /* Immortal Warframe Skins (0–16) */
    "0 immortalwarframeskinsflair ": "Ash (Immortal)",
    "1 immortalwarframeskinsflair ": "Banshee (Immortal)",
    "2 immortalwarframeskinsflair ": "Ember (Immortal)",
    "3 immortalwarframeskinsflair ": "Excalibur (Immortal)",
    "4 immortalwarframeskinsflair ": "Frost (Immortal)",
    "5 immortalwarframeskinsflair ": "Loki (Immortal)",
    "6 immortalwarframeskinsflair ": "Mag (Immortal)",
    "7 immortalwarframeskinsflair ": "Nekros (Immortal)",
    "8 immortalwarframeskinsflair ": "Nova (Immortal)",
    "9 immortalwarframeskinsflair ": "Nyx (Immortal)",
    "10 immortalwarframeskinsflair ": "Oberon (Immortal)",
    "11 immortalwarframeskinsflair ": "Rhino (Immortal)",
    "12 immortalwarframeskinsflair ": "Saryn (Immortal)",
    "13 immortalwarframeskinsflair ": "Trinity (Immortal)",
    "14 immortalwarframeskinsflair ": "Valkyr (Immortal)",
    "15 immortalwarframeskinsflair ": "Vauban (Immortal)",
    "16 immortalwarframeskinsflair ": "Volt (Immortal)",
    
    /* Other Warframe Skins (0–6) */
    "0 otherwarframeskinsflair excalibur-jade": "Excalibur (Jade — XB1 exclusive)",
    "1 otherwarframeskinsflair excalibur-obsidian": "Excalibur (Obsidian — PS4 exclusive)",
    "2 otherwarframeskinsflair excalibur-obsidian-azura": "Excalibur (Obsidian Azura — PS4 exclusive)",
    "3 otherwarframeskinsflair excalibur-proto": "Excalibur (Proto)",
    "4 otherwarframeskinsflair rhino-rubedo": "Rhino (Rubedo — Steam exclusive)",
    "5 otherwarframeskinsflair titania-solstice": "Titania (Solstice)",
    "6 otherwarframeskinsflair vauban-phased": "Vauban (Phased — Steam exclusive)",
    
        
    /* Glyphs (0-51) */
    "0 glyphsflair ash-in-action": "Ash in Action Glyph",
    "1 glyphsflair blood-lotus": "Blood Lotus Glyph",
    "2 glyphsflair butterfly-varna": "Butterfly Varna Glyph",
    "3 glyphsflair ceph-pinacoid": "Ceph Pinacoid Glyph",
    "4 glyphsflair clem-in-action": "Clem in Action Glyph",
    "5 glyphsflair ember-in-action": "Ember in Action Glyph",
    "6 glyphsflair excalibur-in-action": "Excalibur in Action Glyph",
    "7 glyphsflair excalibur-noggle": "Excalibur Noggle Glyph",
    "8 glyphsflair ginger-kubrow-varna": "Ginger Kubrow Varna Glyph",
    "9 glyphsflair grey-kubrow-varna": "Grey Kubrow Varna Glyph",
    "10 glyphsflair grineer-queens": "Grineer Queens Glyph",
    "11 glyphsflair hydroid-submerged": "Hydroid Submerged Glyph",
    "12 glyphsflair isochronon": "Isochronon Glyph",
    "13 glyphsflair kavat-enamel": "Kavat Enamel Glyph",
    "14 glyphsflair kubrow-enamel": "Kubrow Enamel Glyph",
    "15 glyphsflair kuria": "Kuria Glyph",
    "16 glyphsflair kuria-idolized": "Kuria Idolized Glyph",
    "17 glyphsflair loki-in-action": "Loki in Action Glyph",
    "18 glyphsflair loki-noggle": "Loki Noggle Glyph",
    "19 glyphsflair lotus-balance": "Lotus Balance Glyph",
    "20 glyphsflair lotus-noggle": "Lotus Noggle Glyph",
    "21 glyphsflair lunaro": "Lunaro Glyph",
    "22 glyphsflair mag-in-action": "Mag in Action Glyph",
    "23 glyphsflair mag-noggle": "Mag Noggle Glyph",
    "24 glyphsflair mesa-fixated": "Mesa Fixated Glyph",
    "25 glyphsflair moon-crest": "Moon Crest Glyph",
    "26 glyphsflair mythic-balance": "Mythic Balance Glyph",
    "27 glyphsflair nekros-day-of-the-dead": "Nekros Day Of The Dead Glyph",
    "28 glyphsflair orbital-cathode": "Orbital Cathode Glyph",
    "29 glyphsflair rhino-in-action": "Rhino in Action Glyph",
    "30 glyphsflair rhino-noggle": "Rhino Noggle Glyph",
    "31 glyphsflair scarab-varna": "Scarab Varna Glyph",
    "32 glyphsflair solstice-i": "Solstice Glyph I",
    "33 glyphsflair solstice-ii": "Solstice Glyph II",
    "34 glyphsflair solstice-iii": "Solstice Glyph III",
    "35 glyphsflair solstice-iv": "Solstice Glyph IV",
    "36 glyphsflair solunar": "Solunar Glyph",
    "37 glyphsflair sooty-kubrow-varna": "Sooty Kubrow Varna Glyph",
    "38 glyphsflair sun-crest": "Sun Crest Glyph",
    "39 glyphsflair tenno-refractal": "Tenno Refractal Glyph",
    "40 glyphsflair teshin": "Teshin Glyph",
    "41 glyphsflair threshcone-varna": "Threshcone Varna Glyph",
    "42 glyphsflair trinity-in-action": "Trinity in Action Glyph",
    "43 glyphsflair volt-in-action": "Volt in Action Glyph",
    "44 glyphsflair vor-varna": "Vor Varna Glyph",
    "45 glyphsflair winter-i": "Winter Glyph I",
    "46 glyphsflair winter-ii": "Winter Glyph II",
    "47 glyphsflair winter-iii": "Winter Glyph III",
    "48 glyphsflair winter-iv": "Winter Glyph IV",
    "49 glyphsflair winter-v": "Winter Glyph V",
    "50 glyphsflair winter-vi": "Winter Glyph VI",
    "51 glyphsflair winter-vii": "Winter Glyph VII",
    
    
    /* Noggles (0-71) */
    "8 nogglesflair acolyte-angst": "Acolyte Angst Noggle",
    "9 nogglesflair acolyte-malice": "Acolyte Malice Noggle",
    "10 nogglesflair acolyte-mania": "Acolyte Mania Noggle",
    "11 nogglesflair acolyte-misery": "Acolyte Misery Noggle",
    "12 nogglesflair acolyte-torment": "Acolyte Torment Noggle",
    "13 nogglesflair acolyte-violence": "Acolyte Violence Noggle",
    "0 nogglesflair alad-v": "Alad V Noggle",
    "14 nogglesflair arid-seeker": "Arid Seeker Noggle",
    "15 nogglesflair ash": "Ash Noggle",
    "16 nogglesflair banshee": "Banshee Noggle",
    "1 nogglesflair baro-ki-teer": "Baro Ki'Teer Noggle",
    "17 nogglesflair battalyst": "Battalyst Noggle",
    "2 nogglesflair captain-vor": "Captain Vor Noggle",
    "3 nogglesflair clem": "Clem Noggle",
    "18 nogglesflair conculyst": "Conculyst Noggle",
    "19 nogglesflair elite-arid-lancer": "Elite Arid Lancer Noggle",
    "20 nogglesflair ember": "Ember Noggle",
    "25 nogglesflair excalibur-prime": "Excalibur Prime Noggle (PC Founders exclusive)",
    "22 nogglesflair excalibur": "Excalibur Noggle",
    "21 nogglesflair excalibur-jade": "Excalibur (Jade) Noggle (XB1 exclusive)",
    "25 nogglesflair excalibur-obsidian": "Excalibur (Obsidian) Noggle (PS4 exclusive)",
    "24 nogglesflair excalibur-obsidian-azura": "Excalibur (Obsidian Azura) Noggle (PS4 exclusive)",
    "32 nogglesflair index-derim-zahn": "Index Claims Investigation Broker Derim Zahn Noggle",
    "35 nogglesflair index-jen-dro": "Index Claims Investigation Broker Jen Dro Noggle",
    "37 nogglesflair index-m-wam": "Index Claims Investigation Broker M-WAM Noggle",
    "42 nogglesflair index-tia-mayn": "Index Claims Investigation Broker Tia Mayn Noggle",
    "7 nogglesflair index-002-er": "Index Investor Relations Broker 002-ER Noggle",
    "29 nogglesflair index-armis-ulta": "Index Investor Relations Broker Armis Ulta Noggle",
    "33 nogglesflair index-dru-pesfor": "Index Investor Relations Broker Dru Pesfor Noggle",
    "40 nogglesflair index-rana-del": "Index Investor Relations Broker Rana Del Noggle",
    "36 nogglesflair index-lockjaw-and-sol": "Index Reclamation Unit Broker Lockjaw and Sol Noggle",
    "38 nogglesflair index-nako-xol": "Index Reclamation Unit Broker Nako Xol Noggle",
    "39 nogglesflair index-pelna-cade": "Index Reclamation Unit Broker Pelna Cade Noggle",
    "43 nogglesflair index-ved-xol": "Index Reclamation Unit Broker Ved Xol Noggle",
    "30 nogglesflair index-auditor": "Index Trading Group Broker Auditor Noggle",
    "31 nogglesflair index-azoth": "Index Trading Group Broker Azoth Noggle",
    "34 nogglesflair index-jad-teran": "Index Trading Group Broker Jad Teran Noggle",
    "41 nogglesflair index-raptor-rx": "Index Trading Group Broker Raptor RX Noggle",
    "55 nogglesflair rathuum-executioner-dhurnam": "Rathuum Executioner Dhurnam Noggle",
    "56 nogglesflair rathuum-executioner-dok-thul": "Rathuum Executioner Dok Thul Noggle",
    "57 nogglesflair rathuum-executioner-garesh": "Rathuum Executioner Garesh Noggle",
    "58 nogglesflair rathuum-executioner-gorth": "Rathuum Executioner Gorth Noggle",
    "59 nogglesflair rathuum-executioner-harkonar": "Rathuum Executioner Harkonar Noggle",
    "60 nogglesflair rathuum-executioner-nok": "Rathuum Executioner Nok Noggle",
    "61 nogglesflair rathuum-executioner-reth": "Rathuum Executioner Reth Noggle",
    "62 nogglesflair rathuum-executioner-vay-molta": "Rathuum Executioner Vay Molta Noggle",
    "63 nogglesflair rathuum-executioner-zura": "Rathuum Executioner Zura Noggle",
    "26 nogglesflair frost": "Frost Noggle",
    "4 nogglesflair general-sargas-ruk": "General Sargas Ruk Noggle",
    "27 nogglesflair hydroid": "Hydroid Noggle",
    "28 nogglesflair hyekka": "Hyekka Noggle",
    "44 nogglesflair kela-de-thaym": "Kela De Thaym Noggle",
    "45 nogglesflair lancer": "Lancer Noggle",
    "46 nogglesflair loki": "Loki Noggle",
    "5 nogglesflair the-lotus": "Lotus Noggle",
    "47 nogglesflair mag": "Mag Noggle",
    "48 nogglesflair mirage": "Mirage Noggle",
    "50 nogglesflair nekros": "Nekros Noggle",
    "51 nogglesflair nezha": "Nezha Noggle",
    "52 nogglesflair nova": "Nova Noggle",
    "53 nogglesflair nyx": "Nyx Noggle",
    "54 nogglesflair oberon": "Oberon Noggle",
    "64 nogglesflair rhino": "Rhino Noggle",
    "65 nogglesflair saryn": "Saryn Noggle",
    "66 nogglesflair trinity": "Trinity Noggle",
    "67 nogglesflair valkyr": "Valkyr Noggle",
    "68 nogglesflair vauban": "Vauban Noggle",
    "69 nogglesflair volt": "Volt Noggle",
    "70 nogglesflair wukong": "Wukong Noggle",
    "71 nogglesflair zephyr": "Zephyr Noggle",
    "6 nogglesflair stalker": "??????? Noggle",
    
    
    /* Sigils */
    "0 sigilsflair boss-alad-v": "Alad V",
    "1 sigilsflair boss-ambulas": "Ambulas",
    "2 sigilsflair boss-captain-vor": "Captain Vor",
    "3 sigilsflair boss-hyena-pack": "Hyena Pack",
    "4 sigilsflair boss-jackal": "Jackal",
    "5 sigilsflair boss-kela-de-thaym": "Kela De Thaym",
    "6 sigilsflair boss-lephantis": "Lephantis",
    "7 sigilsflair boss-lynx": "Lynx",
    "8 sigilsflair boss-nef-anyo": "Nef Anyo",
    "9 sigilsflair boss-phorid": "Phorid",
    "10 sigilsflair boss-raptor": "Raptor",
    "11 sigilsflair boss-tyl-regor": "Tyl Regor",
    "12 sigilsflair boss-councilor-vey-hek": "Councilor Vey Hek",
    "13 sigilsflair boss-general-sargas-ruk": "General Sargas Ruk",
    "14 sigilsflair boss-lieutenant-lech-kril": "Lieutenant Lech Kril",
    "15 sigilsflair syndicate-arbiters-of-hexis": "Arbiters of Hexis",
    "16 sigilsflair syndicate-arbiters-of-hexis-level-1": "Guiding Path (Arbiters of Hexis)",
    "17 sigilsflair syndicate-arbiters-of-hexis-level-2": "Bending Will (Arbiters of Hexis)",
    "18 sigilsflair syndicate-arbiters-of-hexis-level-3": "Discipline (Arbiters of Hexis)",
    "19 sigilsflair syndicate-arbiters-of-hexis-level-4": "Will (Arbiters of Hexis)",
    "20 sigilsflair syndicate-arbiters-of-hexis-level-5": "Choice (Arbiters of Hexis)",
    "21 sigilsflair syndicate-arbiters-of-hexis-level-6": "Growth (Arbiters of Hexis)",
    "22 sigilsflair syndicate-arbiters-of-hexis-level-7": "Potential (Arbiters of Hexis)",
    "23 sigilsflair syndicate-arbiters-of-hexis-level-8": "Succession (Arbiters of Hexis)",
    "24 sigilsflair syndicate-arbiters-of-hexis-level-9": "Surpassing (Arbiters of Hexis)",
    "25 sigilsflair syndicate-arbiters-of-hexis-level-10": "Truth (Arbiters of Hexis)",
    "26 sigilsflair syndicate-cephalon-simaris": "Cephalon Simaris",
    "27 sigilsflair syndicate-cephalon-simaris-gold": "Cephalon Simaris (Gold)",
    "28 sigilsflair syndicate-cephalon-suda": "Cephalon Suda",
    "29 sigilsflair syndicate-cephalon-suda-level-1": "Query (Cephalon Suda)",
    "30 sigilsflair syndicate-cephalon-suda-level-2": "Searching (Cephalon Suda)",
    "31 sigilsflair syndicate-cephalon-suda-level-3": "Pattern Match (Cephalon Suda)",
    "32 sigilsflair syndicate-cephalon-suda-level-4": "Atomic (Cephalon Suda)",
    "33 sigilsflair syndicate-cephalon-suda-level-5": "Manifold (Cephalon Suda)",
    "34 sigilsflair syndicate-cephalon-suda-level-6": "Fractal (Cephalon Suda)",
    "35 sigilsflair syndicate-cephalon-suda-level-7": "Multivariate (Cephalon Suda)",
    "36 sigilsflair syndicate-cephalon-suda-level-8": "Labryinth (Cephalon Suda)",
    "37 sigilsflair syndicate-cephalon-suda-level-9": "Hexan (Cephalon Suda)",
    "38 sigilsflair syndicate-cephalon-suda-level-10": "Oracle (Cephalon Suda)",
    "39 sigilsflair syndicate-conclave": "Conclave",
    "40 sigilsflair syndicate-conclave-level-1": "Awakening (Conclave)",
    "41 sigilsflair syndicate-conclave-level-2": "Perception (Conclave)",
    "42 sigilsflair syndicate-conclave-level-3": "Awareness (Conclave)",
    "43 sigilsflair syndicate-conclave-level-4": "Revelation (Conclave)",
    "44 sigilsflair syndicate-conclave-level-5": "Diligence (Conclave)",
    "45 sigilsflair syndicate-conclave-level-6": "Enlightenment (Conclave)",
    "46 sigilsflair syndicate-conclave-level-7": "Prudence (Conclave)",
    "47 sigilsflair syndicate-conclave-level-8": "Discretion (Conclave)",
    "48 sigilsflair syndicate-conclave-level-9": "Ambition (Conclave)",
    "49 sigilsflair syndicate-conclave-level-10": "Volition (Conclave)",
    "50 sigilsflair syndicate-conclave-level-11": "Discovery (Conclave)",
    "51 sigilsflair syndicate-conclave-level-12": "Accord (Conclave)",
    "52 sigilsflair syndicate-conclave-level-13": "Insight (Conclave)",
    "53 sigilsflair syndicate-conclave-level-14": "Empathy (Conclave)",
    "54 sigilsflair syndicate-conclave-level-15": "Unity (Conclave)",
    "55 sigilsflair syndicate-conclave-level-16": "Freedom (Conclave)",
    "56 sigilsflair syndicate-new-loka": "New Loka",
    "57 sigilsflair syndicate-new-loka-level-1": "Sacrifice (New Loka)",
    "58 sigilsflair syndicate-new-loka-level-2": "Seed (New Loka)",
    "59 sigilsflair syndicate-new-loka-level-3": "Rebirth (New Loka)",
    "60 sigilsflair syndicate-new-loka-level-4": "Growth (New Loka)",
    "61 sigilsflair syndicate-new-loka-level-5": "Clarity (New Loka)",
    "62 sigilsflair syndicate-new-loka-level-6": "Bloom (New Loka)",
    "63 sigilsflair syndicate-new-loka-level-7": "Purity (New Loka)",
    "64 sigilsflair syndicate-new-loka-level-8": "Gaia (New Loka)",
    "65 sigilsflair syndicate-new-loka-level-9": "Bounty (New Loka)",
    "66 sigilsflair syndicate-new-loka-level-10": "Humanity (New Loka)",
    "67 sigilsflair syndicate-red-veil": "Red Veil",
    "68 sigilsflair syndicate-red-veil-level-1": "Blades (Red Veil)",
    "69 sigilsflair syndicate-red-veil-level-2": "Cull (Red Veil)",
    "70 sigilsflair syndicate-red-veil-level-3": "Threat (Red Veil)",
    "71 sigilsflair syndicate-red-veil-level-4": "Maelstrom (Red Veil)",
    "72 sigilsflair syndicate-red-veil-level-5": "Lesion (Red Veil)",
    "73 sigilsflair syndicate-red-veil-level-6": "Ruin (Red Veil)",
    "74 sigilsflair syndicate-red-veil-level-7": "Viscera (Red Veil)",
    "75 sigilsflair syndicate-red-veil-level-8": "Malevolent (Red Veil)",
    "76 sigilsflair syndicate-red-veil-level-9": "Covert (Red Veil)",
    "77 sigilsflair syndicate-red-veil-level-10": "Assassin (Red Veil)",
    "78 sigilsflair syndicate-steel-meridian": "Steel Meridian",
    "79 sigilsflair syndicate-steel-meridian-level-1": "Defiance (Steel Meridian)",
    "80 sigilsflair syndicate-steel-meridian-level-2": "Armada (Steel Meridian)",
    "81 sigilsflair syndicate-steel-meridian-level-3": "Vigilance (Steel Meridian)",
    "82 sigilsflair syndicate-steel-meridian-level-4": "Uprising (Steel Meridian)",
    "83 sigilsflair syndicate-steel-meridian-level-5": "Protectorate (Steel Meridian)",
    "84 sigilsflair syndicate-steel-meridian-level-6": "Freedom Fighter (Steel Meridian)",
    "85 sigilsflair syndicate-steel-meridian-level-7": "Armored (Steel Meridian)",
    "86 sigilsflair syndicate-steel-meridian-level-8": "Rebellion (Steel Meridian)",
    "87 sigilsflair syndicate-steel-meridian-level-9": "Unyielding (Steel Meridian)",
    "88 sigilsflair syndicate-steel-meridian-level-10": "Champion (Steel Meridian)",
    "89 sigilsflair syndicate-the-perrin-sequence": "The Perrin Sequence",
    "90 sigilsflair syndicate-the-perrin-sequence-level-1": "Progress (The Perrin Sequence)",
    "91 sigilsflair syndicate-the-perrin-sequence-level-2": "Opportunity (The Perrin Sequence)",
    "92 sigilsflair syndicate-the-perrin-sequence-level-3": "Calculating (The Perrin Sequence)",
    "93 sigilsflair syndicate-the-perrin-sequence-level-4": "Synergy (The Perrin Sequence)",
    "94 sigilsflair syndicate-the-perrin-sequence-level-5": "Directives (The Perrin Sequence)",
    "95 sigilsflair syndicate-the-perrin-sequence-level-6": "Strategy (The Perrin Sequence)",
    "96 sigilsflair syndicate-the-perrin-sequence-level-7": "Tessilations [sic] (The Perrin Sequence)",
    "97 sigilsflair syndicate-the-perrin-sequence-level-8": "Optimum (The Perrin Sequence)",
    "98 sigilsflair syndicate-the-perrin-sequence-level-9": "Capital (The Perrin Sequence)",
    "99 sigilsflair syndicate-the-perrin-sequence-level-10": "Chairman (The Perrin Sequence)",
    "100 sigilsflair prime-cycuta": "Cycuta Prime",
    "101 sigilsflair prime-verlorum": "Verlorum Prime",
    "102 sigilsflair banshee-soprana": "Banshee Soprana",
    "103 sigilsflair blade-and-gun": "Blade and Gun",
    "104 sigilsflair cycle-one": "Cycle One (PS4 exclusive)",
    "105 sigilsflair cycle-three": "Cycle Three (PS4 exclusive)",
    "106 sigilsflair cycle-two": "Cycle Two (PS4 exclusive)",
    "107 sigilsflair day-of-the-dead": "Day of the Dead",
    "108 sigilsflair festive": "Festive",
    "109 sigilsflair festive-i-wreath": "Festive I (Wreath)",
    "110 sigilsflair festive-ii-nistlebrush": "Festive II (Nistlebrush)",
    "111 sigilsflair festive-iii-tolling": "Festive III (Tolling)",
    "112 sigilsflair festive-iv-evergreen": "Festive IV (Evergreen)",
    "113 sigilsflair kuria": "Kuria",
    "114 sigilsflair kuria-gold": "Kuria (Gold)",
    "115 sigilsflair login-a-imminent-eclipse": "Imminent Eclipse (Login)",
    "116 sigilsflair login-b-awakened-luna": "Awakened Luna (Login)",
    "117 sigilsflair login-c-eternal-stasis": "Eternal Stasis (Login)",
    "118 sigilsflair login-d-solar-flare": "Solar Flare (Login)",
    "119 sigilsflair prisma": "Prisma",
    "120 sigilsflair rhino-palatine": "Rhino Palatine",
    "121 sigilsflair rift": "Rift",
    "122 sigilsflair scar": "Scar",
    "123 sigilsflair seal-of-honoring": "Seal of Honoring (XB1 exclusive)",
    "124 sigilsflair seal-of-honoring-ii": "Seal of Honoring II (XB1 exclusive)",
    "125 sigilsflair solstice-i": "Solstice I",
    "126 sigilsflair solstice-ii": "Solstice II",
    "127 sigilsflair solstice-iii": "Solstice III",
    "128 sigilsflair solstice-iv": "Solstice IV",
    "129 sigilsflair solstice-v": "Solstice V",
    "130 sigilsflair year-monquis-china": "Monquis (China)",
    "131 sigilsflair year-monquis-world": "Monquis (International)",
    
    
    /* Miscellaneous Flairs (0-26) */
    "0 miscellaneousflair disciple": "Disciple Founder (PC Founders exclusive)",
    "1 miscellaneousflair hunter": "Hunter Founder (PC Founders exclusive)",
    "2 miscellaneousflair master": "Master Founder (PC Founders exclusive)",
    "3 miscellaneousflair grandmaster": "Grand Master Founder (PC Founders exclusive)",
    /*"4 miscellaneousflair revive": "Moderator",*/
    /*"5 miscellaneousflair lotus": "DE Employee",*/
    "6 miscellaneousflair kubrow": "Kubrow",
    "7 miscellaneousflair kubrow-chesa": "Kubrow (Chesa)",
    "8 miscellaneousflair kubrow-huras": "Kubrow (Huras)",
    "9 miscellaneousflair kubrow-raksa": "Kubrow (Raksa)",
    "10 miscellaneousflair kubrow-sahasa": "Kubrow (Sahasa)",
    "11 miscellaneousflair kubrow-sunika": "Kubrow (Sunika)",
    "12 miscellaneousflair kavat-a": "Kavat",
    "13 miscellaneousflair kavat": "Kavat",
    "14 miscellaneousflair kavat-c": "Kavat",
    "15 miscellaneousflair kavat-d": "Kavat",
    "16 miscellaneousflair pc": "PC",
    "17 miscellaneousflair ps4": "PS4",
    "18 miscellaneousflair xb1": "XB1"
};
